// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rove/asset_svc.g.proto

package rove

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetService_Add_FullMethodName   = "/rove.AssetService/Add"
	AssetService_Get_FullMethodName   = "/rove.AssetService/Get"
	AssetService_Patch_FullMethodName = "/rove.AssetService/Patch"
	AssetService_Apply_FullMethodName = "/rove.AssetService/Apply"
	AssetService_Erase_FullMethodName = "/rove.AssetService/Erase"
	AssetService_List_FullMethodName  = "/rove.AssetService/List"
	AssetService_Watch_FullMethodName = "/rove.AssetService/Watch"
)

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetServiceClient interface {
	// Add creates a new Asset
	Add(ctx context.Context, in *AssetAddRequest, opts ...grpc.CallOption) (*Asset, error)
	// Get retrieves a Asset
	Get(ctx context.Context, in *AssetGetRequest, opts ...grpc.CallOption) (*Asset, error)
	// Patch updates an existing Asset
	Patch(ctx context.Context, in *AssetPatchRequest, opts ...grpc.CallOption) (*Asset, error)
	// Apply applies a patch document to an existing Asset
	Apply(ctx context.Context, in *AssetApplyRequest, opts ...grpc.CallOption) (*Asset, error)
	// Erase deletes a Asset
	Erase(ctx context.Context, in *AssetRef, opts ...grpc.CallOption) (*AssetEraseResponse, error)
	// List reads Assets a page at a time.
	List(ctx context.Context, in *AssetListRequest, opts ...grpc.CallOption) (*AssetListResponse, error)
	// Watch the Assets this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(ctx context.Context, in *AssetWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AssetWatchResponse], error)
}

type assetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetServiceClient(cc grpc.ClientConnInterface) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) Add(ctx context.Context, in *AssetAddRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) Get(ctx context.Context, in *AssetGetRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) Patch(ctx context.Context, in *AssetPatchRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) Apply(ctx context.Context, in *AssetApplyRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) Erase(ctx context.Context, in *AssetRef, opts ...grpc.CallOption) (*AssetEraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetEraseResponse)
	err := c.cc.Invoke(ctx, AssetService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) List(ctx context.Context, in *AssetListRequest, opts ...grpc.CallOption) (*AssetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetListResponse)
	err := c.cc.Invoke(ctx, AssetService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) Watch(ctx context.Context, in *AssetWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AssetWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AssetService_ServiceDesc.Streams[0], AssetService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AssetWatchRequest, AssetWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssetService_WatchClient = grpc.ServerStreamingClient[AssetWatchResponse]

// AssetServiceServer is the server API for AssetService service.
// All implementations must embed UnimplementedAssetServiceServer
// for forward compatibility.
type AssetServiceServer interface {
	// Add creates a new Asset
	Add(context.Context, *AssetAddRequest) (*Asset, error)
	// Get retrieves a Asset
	Get(context.Context, *AssetGetRequest) (*Asset, error)
	// Patch updates an existing Asset
	Patch(context.Context, *AssetPatchRequest) (*Asset, error)
	// Apply applies a patch document to an existing Asset
	Apply(context.Context, *AssetApplyRequest) (*Asset, error)
	// Erase deletes a Asset
	Erase(context.Context, *AssetRef) (*AssetEraseResponse, error)
	// List reads Assets a page at a time.
	List(context.Context, *AssetListRequest) (*AssetListResponse, error)
	// Watch the Assets this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(*AssetWatchRequest, grpc.ServerStreamingServer[AssetWatchResponse]) error
	mustEmbedUnimplementedAssetServiceServer()
}

// UnimplementedAssetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetServiceServer struct{}

func (UnimplementedAssetServiceServer) Add(context.Context, *AssetAddRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAssetServiceServer) Get(context.Context, *AssetGetRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAssetServiceServer) Patch(context.Context, *AssetPatchRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedAssetServiceServer) Apply(context.Context, *AssetApplyRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedAssetServiceServer) Erase(context.Context, *AssetRef) (*AssetEraseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedAssetServiceServer) List(context.Context, *AssetListRequest) (*AssetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAssetServiceServer) Watch(*AssetWatchRequest, grpc.ServerStreamingServer[AssetWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedAssetServiceServer) mustEmbedUnimplementedAssetServiceServer() {}
func (UnimplementedAssetServiceServer) testEmbeddedByValue()                      {}

// UnsafeAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetServiceServer will
// result in compilation errors.
type UnsafeAssetServiceServer interface {
	mustEmbedUnimplementedAssetServiceServer()
}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

func _AssetService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Add(ctx, req.(*AssetAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Get(ctx, req.(*AssetGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Patch(ctx, req.(*AssetPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Apply(ctx, req.(*AssetApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Erase(ctx, req.(*AssetRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).List(ctx, req.(*AssetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AssetWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AssetServiceServer).Watch(m, &grpc.GenericServerStream[AssetWatchRequest, AssetWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssetService_WatchServer = grpc.ServerStreamingServer[AssetWatchResponse]

// AssetService_ServiceDesc is the grpc.ServiceDesc for AssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rove.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AssetService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AssetService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _AssetService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _AssetService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _AssetService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AssetService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _AssetService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rove/asset_svc.g.proto",
}

const (
	TreeLockService_Add_FullMethodName   = "/rove.TreeLockService/Add"
	TreeLockService_Get_FullMethodName   = "/rove.TreeLockService/Get"
	TreeLockService_Patch_FullMethodName = "/rove.TreeLockService/Patch"
	TreeLockService_Apply_FullMethodName = "/rove.TreeLockService/Apply"
	TreeLockService_Erase_FullMethodName = "/rove.TreeLockService/Erase"
)

// TreeLockServiceClient is the client API for TreeLockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TreeLockServiceClient interface {
	// Add creates a new TreeLock
	Add(ctx context.Context, in *TreeLockAddRequest, opts ...grpc.CallOption) (*TreeLock, error)
	// Get retrieves a TreeLock
	Get(ctx context.Context, in *TreeLockGetRequest, opts ...grpc.CallOption) (*TreeLock, error)
	// Patch updates an existing TreeLock
	Patch(ctx context.Context, in *TreeLockPatchRequest, opts ...grpc.CallOption) (*TreeLock, error)
	// Apply applies a patch document to an existing TreeLock
	Apply(ctx context.Context, in *TreeLockApplyRequest, opts ...grpc.CallOption) (*TreeLock, error)
	// Erase deletes a TreeLock
	Erase(ctx context.Context, in *TreeLockRef, opts ...grpc.CallOption) (*TreeLockEraseResponse, error)
}

type treeLockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTreeLockServiceClient(cc grpc.ClientConnInterface) TreeLockServiceClient {
	return &treeLockServiceClient{cc}
}

func (c *treeLockServiceClient) Add(ctx context.Context, in *TreeLockAddRequest, opts ...grpc.CallOption) (*TreeLock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TreeLock)
	err := c.cc.Invoke(ctx, TreeLockService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeLockServiceClient) Get(ctx context.Context, in *TreeLockGetRequest, opts ...grpc.CallOption) (*TreeLock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TreeLock)
	err := c.cc.Invoke(ctx, TreeLockService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeLockServiceClient) Patch(ctx context.Context, in *TreeLockPatchRequest, opts ...grpc.CallOption) (*TreeLock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TreeLock)
	err := c.cc.Invoke(ctx, TreeLockService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeLockServiceClient) Apply(ctx context.Context, in *TreeLockApplyRequest, opts ...grpc.CallOption) (*TreeLock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TreeLock)
	err := c.cc.Invoke(ctx, TreeLockService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeLockServiceClient) Erase(ctx context.Context, in *TreeLockRef, opts ...grpc.CallOption) (*TreeLockEraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TreeLockEraseResponse)
	err := c.cc.Invoke(ctx, TreeLockService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TreeLockServiceServer is the server API for TreeLockService service.
// All implementations must embed UnimplementedTreeLockServiceServer
// for forward compatibility.
type TreeLockServiceServer interface {
	// Add creates a new TreeLock
	Add(context.Context, *TreeLockAddRequest) (*TreeLock, error)
	// Get retrieves a TreeLock
	Get(context.Context, *TreeLockGetRequest) (*TreeLock, error)
	// Patch updates an existing TreeLock
	Patch(context.Context, *TreeLockPatchRequest) (*TreeLock, error)
	// Apply applies a patch document to an existing TreeLock
	Apply(context.Context, *TreeLockApplyRequest) (*TreeLock, error)
	// Erase deletes a TreeLock
	Erase(context.Context, *TreeLockRef) (*TreeLockEraseResponse, error)
	mustEmbedUnimplementedTreeLockServiceServer()
}

// UnimplementedTreeLockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTreeLockServiceServer struct{}

func (UnimplementedTreeLockServiceServer) Add(context.Context, *TreeLockAddRequest) (*TreeLock, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedTreeLockServiceServer) Get(context.Context, *TreeLockGetRequest) (*TreeLock, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTreeLockServiceServer) Patch(context.Context, *TreeLockPatchRequest) (*TreeLock, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedTreeLockServiceServer) Apply(context.Context, *TreeLockApplyRequest) (*TreeLock, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedTreeLockServiceServer) Erase(context.Context, *TreeLockRef) (*TreeLockEraseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedTreeLockServiceServer) mustEmbedUnimplementedTreeLockServiceServer() {}
func (UnimplementedTreeLockServiceServer) testEmbeddedByValue()                         {}

// UnsafeTreeLockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TreeLockServiceServer will
// result in compilation errors.
type UnsafeTreeLockServiceServer interface {
	mustEmbedUnimplementedTreeLockServiceServer()
}

func RegisterTreeLockServiceServer(s grpc.ServiceRegistrar, srv TreeLockServiceServer) {
	// If the following call panics, it indicates UnimplementedTreeLockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TreeLockService_ServiceDesc, srv)
}

func _TreeLockService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreeLockAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeLockServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeLockService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeLockServiceServer).Add(ctx, req.(*TreeLockAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeLockService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreeLockGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeLockServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeLockService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeLockServiceServer).Get(ctx, req.(*TreeLockGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeLockService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreeLockPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeLockServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeLockService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeLockServiceServer).Patch(ctx, req.(*TreeLockPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeLockService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreeLockApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeLockServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeLockService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeLockServiceServer).Apply(ctx, req.(*TreeLockApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeLockService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreeLockRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeLockServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeLockService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeLockServiceServer).Erase(ctx, req.(*TreeLockRef))
	}
	return interceptor(ctx, in, info, handler)
}

// TreeLockService_ServiceDesc is the grpc.ServiceDesc for TreeLockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TreeLockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rove.TreeLockService",
	HandlerType: (*TreeLockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _TreeLockService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TreeLockService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _TreeLockService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _TreeLockService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _TreeLockService_Erase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rove/asset_svc.g.proto",
}

const (
	TenantDomainService_Add_FullMethodName   = "/rove.TenantDomainService/Add"
	TenantDomainService_Get_FullMethodName   = "/rove.TenantDomainService/Get"
	TenantDomainService_Patch_FullMethodName = "/rove.TenantDomainService/Patch"
	TenantDomainService_Apply_FullMethodName = "/rove.TenantDomainService/Apply"
	TenantDomainService_Erase_FullMethodName = "/rove.TenantDomainService/Erase"
	TenantDomainService_List_FullMethodName  = "/rove.TenantDomainService/List"
	TenantDomainService_Watch_FullMethodName = "/rove.TenantDomainService/Watch"
)

// TenantDomainServiceClient is the client API for TenantDomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantDomainServiceClient interface {
	// Add creates a new TenantDomain
	Add(ctx context.Context, in *TenantDomainAddRequest, opts ...grpc.CallOption) (*TenantDomain, error)
	// Get retrieves a TenantDomain
	Get(ctx context.Context, in *TenantDomainGetRequest, opts ...grpc.CallOption) (*TenantDomain, error)
	// Patch updates an existing TenantDomain
	Patch(ctx context.Context, in *TenantDomainPatchRequest, opts ...grpc.CallOption) (*TenantDomain, error)
	// Apply applies a patch document to an existing TenantDomain
	Apply(ctx context.Context, in *TenantDomainApplyRequest, opts ...grpc.CallOption) (*TenantDomain, error)
	// Erase deletes a TenantDomain
	Erase(ctx context.Context, in *TenantDomainRef, opts ...grpc.CallOption) (*TenantDomainEraseResponse, error)
	// List reads TenantDomains a page at a time.
	List(ctx context.Context, in *TenantDomainListRequest, opts ...grpc.CallOption) (*TenantDomainListResponse, error)
	// Watch the TenantDomains this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(ctx context.Context, in *TenantDomainWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TenantDomainWatchResponse], error)
}

type tenantDomainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantDomainServiceClient(cc grpc.ClientConnInterface) TenantDomainServiceClient {
	return &tenantDomainServiceClient{cc}
}

func (c *tenantDomainServiceClient) Add(ctx context.Context, in *TenantDomainAddRequest, opts ...grpc.CallOption) (*TenantDomain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantDomain)
	err := c.cc.Invoke(ctx, TenantDomainService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantDomainServiceClient) Get(ctx context.Context, in *TenantDomainGetRequest, opts ...grpc.CallOption) (*TenantDomain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantDomain)
	err := c.cc.Invoke(ctx, TenantDomainService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantDomainServiceClient) Patch(ctx context.Context, in *TenantDomainPatchRequest, opts ...grpc.CallOption) (*TenantDomain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantDomain)
	err := c.cc.Invoke(ctx, TenantDomainService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantDomainServiceClient) Apply(ctx context.Context, in *TenantDomainApplyRequest, opts ...grpc.CallOption) (*TenantDomain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantDomain)
	err := c.cc.Invoke(ctx, TenantDomainService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantDomainServiceClient) Erase(ctx context.Context, in *TenantDomainRef, opts ...grpc.CallOption) (*TenantDomainEraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantDomainEraseResponse)
	err := c.cc.Invoke(ctx, TenantDomainService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantDomainServiceClient) List(ctx context.Context, in *TenantDomainListRequest, opts ...grpc.CallOption) (*TenantDomainListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantDomainListResponse)
	err := c.cc.Invoke(ctx, TenantDomainService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantDomainServiceClient) Watch(ctx context.Context, in *TenantDomainWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TenantDomainWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TenantDomainService_ServiceDesc.Streams[0], TenantDomainService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TenantDomainWatchRequest, TenantDomainWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TenantDomainService_WatchClient = grpc.ServerStreamingClient[TenantDomainWatchResponse]

// TenantDomainServiceServer is the server API for TenantDomainService service.
// All implementations must embed UnimplementedTenantDomainServiceServer
// for forward compatibility.
type TenantDomainServiceServer interface {
	// Add creates a new TenantDomain
	Add(context.Context, *TenantDomainAddRequest) (*TenantDomain, error)
	// Get retrieves a TenantDomain
	Get(context.Context, *TenantDomainGetRequest) (*TenantDomain, error)
	// Patch updates an existing TenantDomain
	Patch(context.Context, *TenantDomainPatchRequest) (*TenantDomain, error)
	// Apply applies a patch document to an existing TenantDomain
	Apply(context.Context, *TenantDomainApplyRequest) (*TenantDomain, error)
	// Erase deletes a TenantDomain
	Erase(context.Context, *TenantDomainRef) (*TenantDomainEraseResponse, error)
	// List reads TenantDomains a page at a time.
	List(context.Context, *TenantDomainListRequest) (*TenantDomainListResponse, error)
	// Watch the TenantDomains this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(*TenantDomainWatchRequest, grpc.ServerStreamingServer[TenantDomainWatchResponse]) error
	mustEmbedUnimplementedTenantDomainServiceServer()
}

// UnimplementedTenantDomainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantDomainServiceServer struct{}

func (UnimplementedTenantDomainServiceServer) Add(context.Context, *TenantDomainAddRequest) (*TenantDomain, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedTenantDomainServiceServer) Get(context.Context, *TenantDomainGetRequest) (*TenantDomain, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTenantDomainServiceServer) Patch(context.Context, *TenantDomainPatchRequest) (*TenantDomain, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedTenantDomainServiceServer) Apply(context.Context, *TenantDomainApplyRequest) (*TenantDomain, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedTenantDomainServiceServer) Erase(context.Context, *TenantDomainRef) (*TenantDomainEraseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedTenantDomainServiceServer) List(context.Context, *TenantDomainListRequest) (*TenantDomainListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTenantDomainServiceServer) Watch(*TenantDomainWatchRequest, grpc.ServerStreamingServer[TenantDomainWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedTenantDomainServiceServer) mustEmbedUnimplementedTenantDomainServiceServer() {}
func (UnimplementedTenantDomainServiceServer) testEmbeddedByValue()                             {}

// UnsafeTenantDomainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantDomainServiceServer will
// result in compilation errors.
type UnsafeTenantDomainServiceServer interface {
	mustEmbedUnimplementedTenantDomainServiceServer()
}

func RegisterTenantDomainServiceServer(s grpc.ServiceRegistrar, srv TenantDomainServiceServer) {
	// If the following call panics, it indicates UnimplementedTenantDomainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantDomainService_ServiceDesc, srv)
}

func _TenantDomainService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantDomainAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantDomainServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantDomainService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantDomainServiceServer).Add(ctx, req.(*TenantDomainAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantDomainService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantDomainGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantDomainServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantDomainService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantDomainServiceServer).Get(ctx, req.(*TenantDomainGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantDomainService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantDomainPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantDomainServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantDomainService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantDomainServiceServer).Patch(ctx, req.(*TenantDomainPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantDomainService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantDomainApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantDomainServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantDomainService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantDomainServiceServer).Apply(ctx, req.(*TenantDomainApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantDomainService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantDomainRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantDomainServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantDomainService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantDomainServiceServer).Erase(ctx, req.(*TenantDomainRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantDomainService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantDomainListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantDomainServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantDomainService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantDomainServiceServer).List(ctx, req.(*TenantDomainListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantDomainService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TenantDomainWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TenantDomainServiceServer).Watch(m, &grpc.GenericServerStream[TenantDomainWatchRequest, TenantDomainWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TenantDomainService_WatchServer = grpc.ServerStreamingServer[TenantDomainWatchResponse]

// TenantDomainService_ServiceDesc is the grpc.ServiceDesc for TenantDomainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantDomainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rove.TenantDomainService",
	HandlerType: (*TenantDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _TenantDomainService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TenantDomainService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _TenantDomainService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _TenantDomainService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _TenantDomainService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TenantDomainService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _TenantDomainService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rove/asset_svc.g.proto",
}

const (
	LabelService_Add_FullMethodName   = "/rove.LabelService/Add"
	LabelService_Get_FullMethodName   = "/rove.LabelService/Get"
	LabelService_Patch_FullMethodName = "/rove.LabelService/Patch"
	LabelService_Apply_FullMethodName = "/rove.LabelService/Apply"
	LabelService_Erase_FullMethodName = "/rove.LabelService/Erase"
	LabelService_List_FullMethodName  = "/rove.LabelService/List"
	LabelService_Watch_FullMethodName = "/rove.LabelService/Watch"
)

// LabelServiceClient is the client API for LabelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LabelServiceClient interface {
	// Add creates a new Label
	Add(ctx context.Context, in *LabelAddRequest, opts ...grpc.CallOption) (*Label, error)
	// Get retrieves a Label
	Get(ctx context.Context, in *LabelGetRequest, opts ...grpc.CallOption) (*Label, error)
	// Patch updates an existing Label
	Patch(ctx context.Context, in *LabelPatchRequest, opts ...grpc.CallOption) (*Label, error)
	// Apply applies a patch document to an existing Label
	Apply(ctx context.Context, in *LabelApplyRequest, opts ...grpc.CallOption) (*Label, error)
	// Erase deletes a Label
	Erase(ctx context.Context, in *LabelRef, opts ...grpc.CallOption) (*LabelEraseResponse, error)
	// List reads Labels a page at a time.
	List(ctx context.Context, in *LabelListRequest, opts ...grpc.CallOption) (*LabelListResponse, error)
	// Watch the Labels this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(ctx context.Context, in *LabelWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LabelWatchResponse], error)
}

type labelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLabelServiceClient(cc grpc.ClientConnInterface) LabelServiceClient {
	return &labelServiceClient{cc}
}

func (c *labelServiceClient) Add(ctx context.Context, in *LabelAddRequest, opts ...grpc.CallOption) (*Label, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Label)
	err := c.cc.Invoke(ctx, LabelService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelServiceClient) Get(ctx context.Context, in *LabelGetRequest, opts ...grpc.CallOption) (*Label, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Label)
	err := c.cc.Invoke(ctx, LabelService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelServiceClient) Patch(ctx context.Context, in *LabelPatchRequest, opts ...grpc.CallOption) (*Label, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Label)
	err := c.cc.Invoke(ctx, LabelService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelServiceClient) Apply(ctx context.Context, in *LabelApplyRequest, opts ...grpc.CallOption) (*Label, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Label)
	err := c.cc.Invoke(ctx, LabelService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelServiceClient) Erase(ctx context.Context, in *LabelRef, opts ...grpc.CallOption) (*LabelEraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LabelEraseResponse)
	err := c.cc.Invoke(ctx, LabelService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelServiceClient) List(ctx context.Context, in *LabelListRequest, opts ...grpc.CallOption) (*LabelListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LabelListResponse)
	err := c.cc.Invoke(ctx, LabelService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelServiceClient) Watch(ctx context.Context, in *LabelWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LabelWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LabelService_ServiceDesc.Streams[0], LabelService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LabelWatchRequest, LabelWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LabelService_WatchClient = grpc.ServerStreamingClient[LabelWatchResponse]

// LabelServiceServer is the server API for LabelService service.
// All implementations must embed UnimplementedLabelServiceServer
// for forward compatibility.
type LabelServiceServer interface {
	// Add creates a new Label
	Add(context.Context, *LabelAddRequest) (*Label, error)
	// Get retrieves a Label
	Get(context.Context, *LabelGetRequest) (*Label, error)
	// Patch updates an existing Label
	Patch(context.Context, *LabelPatchRequest) (*Label, error)
	// Apply applies a patch document to an existing Label
	Apply(context.Context, *LabelApplyRequest) (*Label, error)
	// Erase deletes a Label
	Erase(context.Context, *LabelRef) (*LabelEraseResponse, error)
	// List reads Labels a page at a time.
	List(context.Context, *LabelListRequest) (*LabelListResponse, error)
	// Watch the Labels this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(*LabelWatchRequest, grpc.ServerStreamingServer[LabelWatchResponse]) error
	mustEmbedUnimplementedLabelServiceServer()
}

// UnimplementedLabelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLabelServiceServer struct{}

func (UnimplementedLabelServiceServer) Add(context.Context, *LabelAddRequest) (*Label, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedLabelServiceServer) Get(context.Context, *LabelGetRequest) (*Label, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLabelServiceServer) Patch(context.Context, *LabelPatchRequest) (*Label, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedLabelServiceServer) Apply(context.Context, *LabelApplyRequest) (*Label, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedLabelServiceServer) Erase(context.Context, *LabelRef) (*LabelEraseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedLabelServiceServer) List(context.Context, *LabelListRequest) (*LabelListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedLabelServiceServer) Watch(*LabelWatchRequest, grpc.ServerStreamingServer[LabelWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedLabelServiceServer) mustEmbedUnimplementedLabelServiceServer() {}
func (UnimplementedLabelServiceServer) testEmbeddedByValue()                      {}

// UnsafeLabelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LabelServiceServer will
// result in compilation errors.
type UnsafeLabelServiceServer interface {
	mustEmbedUnimplementedLabelServiceServer()
}

func RegisterLabelServiceServer(s grpc.ServiceRegistrar, srv LabelServiceServer) {
	// If the following call panics, it indicates UnimplementedLabelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LabelService_ServiceDesc, srv)
}

func _LabelService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabelAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabelService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelServiceServer).Add(ctx, req.(*LabelAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabelService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabelGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabelService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelServiceServer).Get(ctx, req.(*LabelGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabelService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabelPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabelService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelServiceServer).Patch(ctx, req.(*LabelPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabelService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabelApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabelService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelServiceServer).Apply(ctx, req.(*LabelApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabelService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabelRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabelService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelServiceServer).Erase(ctx, req.(*LabelRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabelService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabelListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabelService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelServiceServer).List(ctx, req.(*LabelListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabelService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LabelWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LabelServiceServer).Watch(m, &grpc.GenericServerStream[LabelWatchRequest, LabelWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LabelService_WatchServer = grpc.ServerStreamingServer[LabelWatchResponse]

// LabelService_ServiceDesc is the grpc.ServiceDesc for LabelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LabelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rove.LabelService",
	HandlerType: (*LabelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _LabelService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _LabelService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _LabelService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _LabelService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _LabelService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _LabelService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _LabelService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rove/asset_svc.g.proto",
}

const (
	AttachmentService_Add_FullMethodName   = "/rove.AttachmentService/Add"
	AttachmentService_Get_FullMethodName   = "/rove.AttachmentService/Get"
	AttachmentService_Patch_FullMethodName = "/rove.AttachmentService/Patch"
	AttachmentService_Apply_FullMethodName = "/rove.AttachmentService/Apply"
	AttachmentService_Erase_FullMethodName = "/rove.AttachmentService/Erase"
	AttachmentService_List_FullMethodName  = "/rove.AttachmentService/List"
	AttachmentService_Watch_FullMethodName = "/rove.AttachmentService/Watch"
)

// AttachmentServiceClient is the client API for AttachmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttachmentServiceClient interface {
	// Add creates a new Attachment
	Add(ctx context.Context, in *AttachmentAddRequest, opts ...grpc.CallOption) (*Attachment, error)
	// Get retrieves a Attachment
	Get(ctx context.Context, in *AttachmentGetRequest, opts ...grpc.CallOption) (*Attachment, error)
	// Patch updates an existing Attachment
	Patch(ctx context.Context, in *AttachmentPatchRequest, opts ...grpc.CallOption) (*Attachment, error)
	// Apply applies a patch document to an existing Attachment
	Apply(ctx context.Context, in *AttachmentApplyRequest, opts ...grpc.CallOption) (*Attachment, error)
	// Erase deletes a Attachment
	Erase(ctx context.Context, in *AttachmentRef, opts ...grpc.CallOption) (*AttachmentEraseResponse, error)
	// List reads Attachments a page at a time.
	List(ctx context.Context, in *AttachmentListRequest, opts ...grpc.CallOption) (*AttachmentListResponse, error)
	// Watch the Attachments this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(ctx context.Context, in *AttachmentWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AttachmentWatchResponse], error)
}

type attachmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttachmentServiceClient(cc grpc.ClientConnInterface) AttachmentServiceClient {
	return &attachmentServiceClient{cc}
}

func (c *attachmentServiceClient) Add(ctx context.Context, in *AttachmentAddRequest, opts ...grpc.CallOption) (*Attachment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attachment)
	err := c.cc.Invoke(ctx, AttachmentService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attachmentServiceClient) Get(ctx context.Context, in *AttachmentGetRequest, opts ...grpc.CallOption) (*Attachment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attachment)
	err := c.cc.Invoke(ctx, AttachmentService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attachmentServiceClient) Patch(ctx context.Context, in *AttachmentPatchRequest, opts ...grpc.CallOption) (*Attachment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attachment)
	err := c.cc.Invoke(ctx, AttachmentService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attachmentServiceClient) Apply(ctx context.Context, in *AttachmentApplyRequest, opts ...grpc.CallOption) (*Attachment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attachment)
	err := c.cc.Invoke(ctx, AttachmentService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attachmentServiceClient) Erase(ctx context.Context, in *AttachmentRef, opts ...grpc.CallOption) (*AttachmentEraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachmentEraseResponse)
	err := c.cc.Invoke(ctx, AttachmentService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attachmentServiceClient) List(ctx context.Context, in *AttachmentListRequest, opts ...grpc.CallOption) (*AttachmentListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachmentListResponse)
	err := c.cc.Invoke(ctx, AttachmentService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attachmentServiceClient) Watch(ctx context.Context, in *AttachmentWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AttachmentWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AttachmentService_ServiceDesc.Streams[0], AttachmentService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachmentWatchRequest, AttachmentWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttachmentService_WatchClient = grpc.ServerStreamingClient[AttachmentWatchResponse]

// AttachmentServiceServer is the server API for AttachmentService service.
// All implementations must embed UnimplementedAttachmentServiceServer
// for forward compatibility.
type AttachmentServiceServer interface {
	// Add creates a new Attachment
	Add(context.Context, *AttachmentAddRequest) (*Attachment, error)
	// Get retrieves a Attachment
	Get(context.Context, *AttachmentGetRequest) (*Attachment, error)
	// Patch updates an existing Attachment
	Patch(context.Context, *AttachmentPatchRequest) (*Attachment, error)
	// Apply applies a patch document to an existing Attachment
	Apply(context.Context, *AttachmentApplyRequest) (*Attachment, error)
	// Erase deletes a Attachment
	Erase(context.Context, *AttachmentRef) (*AttachmentEraseResponse, error)
	// List reads Attachments a page at a time.
	List(context.Context, *AttachmentListRequest) (*AttachmentListResponse, error)
	// Watch the Attachments this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(*AttachmentWatchRequest, grpc.ServerStreamingServer[AttachmentWatchResponse]) error
	mustEmbedUnimplementedAttachmentServiceServer()
}

// UnimplementedAttachmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttachmentServiceServer struct{}

func (UnimplementedAttachmentServiceServer) Add(context.Context, *AttachmentAddRequest) (*Attachment, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAttachmentServiceServer) Get(context.Context, *AttachmentGetRequest) (*Attachment, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAttachmentServiceServer) Patch(context.Context, *AttachmentPatchRequest) (*Attachment, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedAttachmentServiceServer) Apply(context.Context, *AttachmentApplyRequest) (*Attachment, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedAttachmentServiceServer) Erase(context.Context, *AttachmentRef) (*AttachmentEraseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedAttachmentServiceServer) List(context.Context, *AttachmentListRequest) (*AttachmentListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAttachmentServiceServer) Watch(*AttachmentWatchRequest, grpc.ServerStreamingServer[AttachmentWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedAttachmentServiceServer) mustEmbedUnimplementedAttachmentServiceServer() {}
func (UnimplementedAttachmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeAttachmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttachmentServiceServer will
// result in compilation errors.
type UnsafeAttachmentServiceServer interface {
	mustEmbedUnimplementedAttachmentServiceServer()
}

func RegisterAttachmentServiceServer(s grpc.ServiceRegistrar, srv AttachmentServiceServer) {
	// If the following call panics, it indicates UnimplementedAttachmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttachmentService_ServiceDesc, srv)
}

func _AttachmentService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttachmentServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttachmentService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttachmentServiceServer).Add(ctx, req.(*AttachmentAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttachmentService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttachmentServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttachmentService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttachmentServiceServer).Get(ctx, req.(*AttachmentGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttachmentService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttachmentServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttachmentService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttachmentServiceServer).Patch(ctx, req.(*AttachmentPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttachmentService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttachmentServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttachmentService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttachmentServiceServer).Apply(ctx, req.(*AttachmentApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttachmentService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttachmentServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttachmentService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttachmentServiceServer).Erase(ctx, req.(*AttachmentRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttachmentService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttachmentServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttachmentService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttachmentServiceServer).List(ctx, req.(*AttachmentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttachmentService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AttachmentWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AttachmentServiceServer).Watch(m, &grpc.GenericServerStream[AttachmentWatchRequest, AttachmentWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttachmentService_WatchServer = grpc.ServerStreamingServer[AttachmentWatchResponse]

// AttachmentService_ServiceDesc is the grpc.ServiceDesc for AttachmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttachmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rove.AttachmentService",
	HandlerType: (*AttachmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AttachmentService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AttachmentService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _AttachmentService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _AttachmentService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _AttachmentService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AttachmentService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _AttachmentService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rove/asset_svc.g.proto",
}
