// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package rove

import (
	bytes "bytes"
)

func (x *BookableRef) Pick() *BookableGetRequest {
	return BookableGetRequest_builder{Ref: x}.Build()
}

func (x *Bookable) Ref() *BookableRef {
	if v := x.GetId(); len(v) > 0 {
		return BookableById(v)
	}
	{
		v1 := x.GetAsset()
		if v1 != nil {
			return BookableByAsset(v1.Ref())
		}
	}

	return nil
}

func (x *Bookable) Pick() *BookableGetRequest {
	return x.Ref().Pick()
}

func (x *BookableRef) Picks(v *Bookable) bool {
	switch x.WhichKey() {
	case BookableRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case BookableRef_Asset_case:
		x := x.GetAsset()
		return (x.GetAsset().Picks(v.GetAsset()))
	default:
		return false
	}
}

func (x *BookableGetRequest) WithSelect(f func(s *BookableSelect)) *BookableGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&BookableSelect{})
	}
	f(x.GetSelect())
	return x
}

func BookableById(v []byte) *BookableRef {
	x := &BookableRef{}
	x.SetId(v)
	return x
}

func BookableGetById(v []byte) *BookableGetRequest {
	return BookableGetRequest_builder{Ref: BookableById(v)}.Build()
}

func BookableByAsset(asset *AssetRef) *BookableRef {
	x := &BookableRefByAsset{}
	x.SetAsset(asset)
	return BookableRef_builder{Asset: x}.Build()
}

func BookableGetByAsset(asset *AssetRef) *BookableGetRequest {
	return BookableGetRequest_builder{Ref: BookableByAsset(asset)}.Build()
}

func (x *ReservationRef) Pick() *ReservationGetRequest {
	return ReservationGetRequest_builder{Ref: x}.Build()
}

func (x *Reservation) Ref() *ReservationRef {
	if v := x.GetId(); len(v) > 0 {
		return ReservationById(v)
	}

	return nil
}

func (x *Reservation) Pick() *ReservationGetRequest {
	return x.Ref().Pick()
}

func (x *ReservationRef) Picks(v *Reservation) bool {
	switch x.WhichKey() {
	case ReservationRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *ReservationGetRequest) WithSelect(f func(s *ReservationSelect)) *ReservationGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&ReservationSelect{})
	}
	f(x.GetSelect())
	return x
}

func ReservationById(v []byte) *ReservationRef {
	x := &ReservationRef{}
	x.SetId(v)
	return x
}

func ReservationGetById(v []byte) *ReservationGetRequest {
	return ReservationGetRequest_builder{Ref: ReservationById(v)}.Build()
}

func (x *ReservationItemRef) Pick() *ReservationItemGetRequest {
	return ReservationItemGetRequest_builder{Ref: x}.Build()
}

func (x *ReservationItem) Ref() *ReservationItemRef {
	if v := x.GetId(); len(v) > 0 {
		return ReservationItemById(v)
	}

	return nil
}

func (x *ReservationItem) Pick() *ReservationItemGetRequest {
	return x.Ref().Pick()
}

func (x *ReservationItemRef) Picks(v *ReservationItem) bool {
	switch x.WhichKey() {
	case ReservationItemRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *ReservationItemGetRequest) WithSelect(f func(s *ReservationItemSelect)) *ReservationItemGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&ReservationItemSelect{})
	}
	f(x.GetSelect())
	return x
}

func ReservationItemById(v []byte) *ReservationItemRef {
	x := &ReservationItemRef{}
	x.SetId(v)
	return x
}

func ReservationItemGetById(v []byte) *ReservationItemGetRequest {
	return ReservationItemGetRequest_builder{Ref: ReservationItemById(v)}.Build()
}

func (x *AllocationRef) Pick() *AllocationGetRequest {
	return AllocationGetRequest_builder{Ref: x}.Build()
}

func (x *Allocation) Ref() *AllocationRef {
	if v := x.GetId(); len(v) > 0 {
		return AllocationById(v)
	}

	return nil
}

func (x *Allocation) Pick() *AllocationGetRequest {
	return x.Ref().Pick()
}

func (x *AllocationRef) Picks(v *Allocation) bool {
	switch x.WhichKey() {
	case AllocationRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *AllocationGetRequest) WithSelect(f func(s *AllocationSelect)) *AllocationGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&AllocationSelect{})
	}
	f(x.GetSelect())
	return x
}

func AllocationById(v []byte) *AllocationRef {
	x := &AllocationRef{}
	x.SetId(v)
	return x
}

func AllocationGetById(v []byte) *AllocationGetRequest {
	return AllocationGetRequest_builder{Ref: AllocationById(v)}.Build()
}
