// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package rove

import (
	bytes "bytes"
)

func (x *PlacementRef) Pick() *PlacementGetRequest {
	return PlacementGetRequest_builder{Ref: x}.Build()
}

func (x *Placement) Ref() *PlacementRef {
	if v := x.GetId(); len(v) > 0 {
		return PlacementById(v)
	}

	return nil
}

func (x *Placement) Pick() *PlacementGetRequest {
	return x.Ref().Pick()
}

func (x *PlacementRef) Picks(v *Placement) bool {
	switch x.WhichKey() {
	case PlacementRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *PlacementGetRequest) WithSelect(f func(s *PlacementSelect)) *PlacementGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&PlacementSelect{})
	}
	f(x.GetSelect())
	return x
}

func PlacementById(v []byte) *PlacementRef {
	x := &PlacementRef{}
	x.SetId(v)
	return x
}

func PlacementGetById(v []byte) *PlacementGetRequest {
	return PlacementGetRequest_builder{Ref: PlacementById(v)}.Build()
}

func (x *LinkRef) Pick() *LinkGetRequest {
	return LinkGetRequest_builder{Ref: x}.Build()
}

func (x *Link) Ref() *LinkRef {
	if v := x.GetId(); len(v) > 0 {
		return LinkById(v)
	}

	return nil
}

func (x *Link) Pick() *LinkGetRequest {
	return x.Ref().Pick()
}

func (x *LinkRef) Picks(v *Link) bool {
	switch x.WhichKey() {
	case LinkRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *LinkGetRequest) WithSelect(f func(s *LinkSelect)) *LinkGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&LinkSelect{})
	}
	f(x.GetSelect())
	return x
}

func LinkById(v []byte) *LinkRef {
	x := &LinkRef{}
	x.SetId(v)
	return x
}

func LinkGetById(v []byte) *LinkGetRequest {
	return LinkGetRequest_builder{Ref: LinkById(v)}.Build()
}

func (x *StewardshipRef) Pick() *StewardshipGetRequest {
	return StewardshipGetRequest_builder{Ref: x}.Build()
}

func (x *Stewardship) Ref() *StewardshipRef {
	if v := x.GetId(); len(v) > 0 {
		return StewardshipById(v)
	}

	return nil
}

func (x *Stewardship) Pick() *StewardshipGetRequest {
	return x.Ref().Pick()
}

func (x *StewardshipRef) Picks(v *Stewardship) bool {
	switch x.WhichKey() {
	case StewardshipRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *StewardshipGetRequest) WithSelect(f func(s *StewardshipSelect)) *StewardshipGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&StewardshipSelect{})
	}
	f(x.GetSelect())
	return x
}

func StewardshipById(v []byte) *StewardshipRef {
	x := &StewardshipRef{}
	x.SetId(v)
	return x
}

func StewardshipGetById(v []byte) *StewardshipGetRequest {
	return StewardshipGetRequest_builder{Ref: StewardshipById(v)}.Build()
}

func (x *FactRef) Pick() *FactGetRequest {
	return FactGetRequest_builder{Ref: x}.Build()
}

func (x *Fact) Ref() *FactRef {
	if v := x.GetId(); len(v) > 0 {
		return FactById(v)
	}

	return nil
}

func (x *Fact) Pick() *FactGetRequest {
	return x.Ref().Pick()
}

func (x *FactRef) Picks(v *Fact) bool {
	switch x.WhichKey() {
	case FactRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *FactGetRequest) WithSelect(f func(s *FactSelect)) *FactGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&FactSelect{})
	}
	f(x.GetSelect())
	return x
}

func FactById(v []byte) *FactRef {
	x := &FactRef{}
	x.SetId(v)
	return x
}

func FactGetById(v []byte) *FactGetRequest {
	return FactGetRequest_builder{Ref: FactById(v)}.Build()
}

func (x *EventRef) Pick() *EventGetRequest {
	return EventGetRequest_builder{Ref: x}.Build()
}

func (x *Event) Ref() *EventRef {
	if v := x.GetId(); len(v) > 0 {
		return EventById(v)
	}

	return nil
}

func (x *Event) Pick() *EventGetRequest {
	return x.Ref().Pick()
}

func (x *EventRef) Picks(v *Event) bool {
	switch x.WhichKey() {
	case EventRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *EventGetRequest) WithSelect(f func(s *EventSelect)) *EventGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&EventSelect{})
	}
	f(x.GetSelect())
	return x
}

func EventById(v []byte) *EventRef {
	x := &EventRef{}
	x.SetId(v)
	return x
}

func EventGetById(v []byte) *EventGetRequest {
	return EventGetRequest_builder{Ref: EventById(v)}.Build()
}
