// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rove/stock_svc.g.proto

package rove

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockService_Add_FullMethodName   = "/rove.StockService/Add"
	StockService_Get_FullMethodName   = "/rove.StockService/Get"
	StockService_Patch_FullMethodName = "/rove.StockService/Patch"
	StockService_Apply_FullMethodName = "/rove.StockService/Apply"
	StockService_Erase_FullMethodName = "/rove.StockService/Erase"
	StockService_List_FullMethodName  = "/rove.StockService/List"
	StockService_Watch_FullMethodName = "/rove.StockService/Watch"
)

// StockServiceClient is the client API for StockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockServiceClient interface {
	// Add creates a new Stock
	Add(ctx context.Context, in *StockAddRequest, opts ...grpc.CallOption) (*Stock, error)
	// Get retrieves a Stock
	Get(ctx context.Context, in *StockGetRequest, opts ...grpc.CallOption) (*Stock, error)
	// Patch updates an existing Stock
	Patch(ctx context.Context, in *StockPatchRequest, opts ...grpc.CallOption) (*Stock, error)
	// Apply applies a patch document to an existing Stock
	Apply(ctx context.Context, in *StockApplyRequest, opts ...grpc.CallOption) (*Stock, error)
	// Erase deletes a Stock
	Erase(ctx context.Context, in *StockRef, opts ...grpc.CallOption) (*StockEraseResponse, error)
	// List reads Stocks a page at a time.
	List(ctx context.Context, in *StockListRequest, opts ...grpc.CallOption) (*StockListResponse, error)
	// Watch the Stocks this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(ctx context.Context, in *StockWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockWatchResponse], error)
}

type stockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockServiceClient(cc grpc.ClientConnInterface) StockServiceClient {
	return &stockServiceClient{cc}
}

func (c *stockServiceClient) Add(ctx context.Context, in *StockAddRequest, opts ...grpc.CallOption) (*Stock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stock)
	err := c.cc.Invoke(ctx, StockService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) Get(ctx context.Context, in *StockGetRequest, opts ...grpc.CallOption) (*Stock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stock)
	err := c.cc.Invoke(ctx, StockService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) Patch(ctx context.Context, in *StockPatchRequest, opts ...grpc.CallOption) (*Stock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stock)
	err := c.cc.Invoke(ctx, StockService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) Apply(ctx context.Context, in *StockApplyRequest, opts ...grpc.CallOption) (*Stock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stock)
	err := c.cc.Invoke(ctx, StockService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) Erase(ctx context.Context, in *StockRef, opts ...grpc.CallOption) (*StockEraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockEraseResponse)
	err := c.cc.Invoke(ctx, StockService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) List(ctx context.Context, in *StockListRequest, opts ...grpc.CallOption) (*StockListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockListResponse)
	err := c.cc.Invoke(ctx, StockService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) Watch(ctx context.Context, in *StockWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StockService_ServiceDesc.Streams[0], StockService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StockWatchRequest, StockWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_WatchClient = grpc.ServerStreamingClient[StockWatchResponse]

// StockServiceServer is the server API for StockService service.
// All implementations must embed UnimplementedStockServiceServer
// for forward compatibility.
type StockServiceServer interface {
	// Add creates a new Stock
	Add(context.Context, *StockAddRequest) (*Stock, error)
	// Get retrieves a Stock
	Get(context.Context, *StockGetRequest) (*Stock, error)
	// Patch updates an existing Stock
	Patch(context.Context, *StockPatchRequest) (*Stock, error)
	// Apply applies a patch document to an existing Stock
	Apply(context.Context, *StockApplyRequest) (*Stock, error)
	// Erase deletes a Stock
	Erase(context.Context, *StockRef) (*StockEraseResponse, error)
	// List reads Stocks a page at a time.
	List(context.Context, *StockListRequest) (*StockListResponse, error)
	// Watch the Stocks this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(*StockWatchRequest, grpc.ServerStreamingServer[StockWatchResponse]) error
	mustEmbedUnimplementedStockServiceServer()
}

// UnimplementedStockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockServiceServer struct{}

func (UnimplementedStockServiceServer) Add(context.Context, *StockAddRequest) (*Stock, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedStockServiceServer) Get(context.Context, *StockGetRequest) (*Stock, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStockServiceServer) Patch(context.Context, *StockPatchRequest) (*Stock, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedStockServiceServer) Apply(context.Context, *StockApplyRequest) (*Stock, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedStockServiceServer) Erase(context.Context, *StockRef) (*StockEraseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedStockServiceServer) List(context.Context, *StockListRequest) (*StockListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedStockServiceServer) Watch(*StockWatchRequest, grpc.ServerStreamingServer[StockWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedStockServiceServer) mustEmbedUnimplementedStockServiceServer() {}
func (UnimplementedStockServiceServer) testEmbeddedByValue()                      {}

// UnsafeStockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockServiceServer will
// result in compilation errors.
type UnsafeStockServiceServer interface {
	mustEmbedUnimplementedStockServiceServer()
}

func RegisterStockServiceServer(s grpc.ServiceRegistrar, srv StockServiceServer) {
	// If the following call panics, it indicates UnimplementedStockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockService_ServiceDesc, srv)
}

func _StockService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).Add(ctx, req.(*StockAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).Get(ctx, req.(*StockGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).Patch(ctx, req.(*StockPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).Apply(ctx, req.(*StockApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).Erase(ctx, req.(*StockRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).List(ctx, req.(*StockListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StockWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockServiceServer).Watch(m, &grpc.GenericServerStream[StockWatchRequest, StockWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_WatchServer = grpc.ServerStreamingServer[StockWatchResponse]

// StockService_ServiceDesc is the grpc.ServiceDesc for StockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rove.StockService",
	HandlerType: (*StockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _StockService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _StockService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _StockService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _StockService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _StockService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _StockService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _StockService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rove/stock_svc.g.proto",
}

const (
	StockMovementService_Add_FullMethodName   = "/rove.StockMovementService/Add"
	StockMovementService_Get_FullMethodName   = "/rove.StockMovementService/Get"
	StockMovementService_Patch_FullMethodName = "/rove.StockMovementService/Patch"
	StockMovementService_Apply_FullMethodName = "/rove.StockMovementService/Apply"
	StockMovementService_Erase_FullMethodName = "/rove.StockMovementService/Erase"
	StockMovementService_List_FullMethodName  = "/rove.StockMovementService/List"
)

// StockMovementServiceClient is the client API for StockMovementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockMovementServiceClient interface {
	// Add creates a new StockMovement
	Add(ctx context.Context, in *StockMovementAddRequest, opts ...grpc.CallOption) (*StockMovement, error)
	// Get retrieves a StockMovement
	Get(ctx context.Context, in *StockMovementGetRequest, opts ...grpc.CallOption) (*StockMovement, error)
	// Patch updates an existing StockMovement
	Patch(ctx context.Context, in *StockMovementPatchRequest, opts ...grpc.CallOption) (*StockMovement, error)
	// Apply applies a patch document to an existing StockMovement
	Apply(ctx context.Context, in *StockMovementApplyRequest, opts ...grpc.CallOption) (*StockMovement, error)
	// Erase deletes a StockMovement
	Erase(ctx context.Context, in *StockMovementRef, opts ...grpc.CallOption) (*StockMovementEraseResponse, error)
	// List reads StockMovements a page at a time.
	List(ctx context.Context, in *StockMovementListRequest, opts ...grpc.CallOption) (*StockMovementListResponse, error)
}

type stockMovementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockMovementServiceClient(cc grpc.ClientConnInterface) StockMovementServiceClient {
	return &stockMovementServiceClient{cc}
}

func (c *stockMovementServiceClient) Add(ctx context.Context, in *StockMovementAddRequest, opts ...grpc.CallOption) (*StockMovement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockMovement)
	err := c.cc.Invoke(ctx, StockMovementService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockMovementServiceClient) Get(ctx context.Context, in *StockMovementGetRequest, opts ...grpc.CallOption) (*StockMovement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockMovement)
	err := c.cc.Invoke(ctx, StockMovementService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockMovementServiceClient) Patch(ctx context.Context, in *StockMovementPatchRequest, opts ...grpc.CallOption) (*StockMovement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockMovement)
	err := c.cc.Invoke(ctx, StockMovementService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockMovementServiceClient) Apply(ctx context.Context, in *StockMovementApplyRequest, opts ...grpc.CallOption) (*StockMovement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockMovement)
	err := c.cc.Invoke(ctx, StockMovementService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockMovementServiceClient) Erase(ctx context.Context, in *StockMovementRef, opts ...grpc.CallOption) (*StockMovementEraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockMovementEraseResponse)
	err := c.cc.Invoke(ctx, StockMovementService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockMovementServiceClient) List(ctx context.Context, in *StockMovementListRequest, opts ...grpc.CallOption) (*StockMovementListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockMovementListResponse)
	err := c.cc.Invoke(ctx, StockMovementService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockMovementServiceServer is the server API for StockMovementService service.
// All implementations must embed UnimplementedStockMovementServiceServer
// for forward compatibility.
type StockMovementServiceServer interface {
	// Add creates a new StockMovement
	Add(context.Context, *StockMovementAddRequest) (*StockMovement, error)
	// Get retrieves a StockMovement
	Get(context.Context, *StockMovementGetRequest) (*StockMovement, error)
	// Patch updates an existing StockMovement
	Patch(context.Context, *StockMovementPatchRequest) (*StockMovement, error)
	// Apply applies a patch document to an existing StockMovement
	Apply(context.Context, *StockMovementApplyRequest) (*StockMovement, error)
	// Erase deletes a StockMovement
	Erase(context.Context, *StockMovementRef) (*StockMovementEraseResponse, error)
	// List reads StockMovements a page at a time.
	List(context.Context, *StockMovementListRequest) (*StockMovementListResponse, error)
	mustEmbedUnimplementedStockMovementServiceServer()
}

// UnimplementedStockMovementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockMovementServiceServer struct{}

func (UnimplementedStockMovementServiceServer) Add(context.Context, *StockMovementAddRequest) (*StockMovement, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedStockMovementServiceServer) Get(context.Context, *StockMovementGetRequest) (*StockMovement, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStockMovementServiceServer) Patch(context.Context, *StockMovementPatchRequest) (*StockMovement, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedStockMovementServiceServer) Apply(context.Context, *StockMovementApplyRequest) (*StockMovement, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedStockMovementServiceServer) Erase(context.Context, *StockMovementRef) (*StockMovementEraseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedStockMovementServiceServer) List(context.Context, *StockMovementListRequest) (*StockMovementListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedStockMovementServiceServer) mustEmbedUnimplementedStockMovementServiceServer() {}
func (UnimplementedStockMovementServiceServer) testEmbeddedByValue()                              {}

// UnsafeStockMovementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockMovementServiceServer will
// result in compilation errors.
type UnsafeStockMovementServiceServer interface {
	mustEmbedUnimplementedStockMovementServiceServer()
}

func RegisterStockMovementServiceServer(s grpc.ServiceRegistrar, srv StockMovementServiceServer) {
	// If the following call panics, it indicates UnimplementedStockMovementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockMovementService_ServiceDesc, srv)
}

func _StockMovementService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockMovementAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockMovementServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockMovementService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockMovementServiceServer).Add(ctx, req.(*StockMovementAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockMovementService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockMovementGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockMovementServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockMovementService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockMovementServiceServer).Get(ctx, req.(*StockMovementGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockMovementService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockMovementPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockMovementServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockMovementService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockMovementServiceServer).Patch(ctx, req.(*StockMovementPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockMovementService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockMovementApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockMovementServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockMovementService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockMovementServiceServer).Apply(ctx, req.(*StockMovementApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockMovementService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockMovementRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockMovementServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockMovementService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockMovementServiceServer).Erase(ctx, req.(*StockMovementRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockMovementService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockMovementListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockMovementServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockMovementService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockMovementServiceServer).List(ctx, req.(*StockMovementListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockMovementService_ServiceDesc is the grpc.ServiceDesc for StockMovementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockMovementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rove.StockMovementService",
	HandlerType: (*StockMovementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _StockMovementService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _StockMovementService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _StockMovementService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _StockMovementService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _StockMovementService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _StockMovementService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rove/stock_svc.g.proto",
}
