// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rove/work.proto

package rove

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkOrder is a repair, an inspection or maintenance of an asset. One that
// blocks takes the asset's time like a reservation does.
type WorkOrder struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *Tenant                `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Name        string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Asset       *Asset                 `protobuf:"bytes,8,opt,name=asset"`
	xxx_hidden_Kind        string                 `protobuf:"bytes,9,opt,name=kind"`
	xxx_hidden_Status      string                 `protobuf:"bytes,10,opt,name=status"`
	xxx_hidden_BeginsAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=begins_at,json=beginsAt"`
	xxx_hidden_EndsAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=ends_at,json=endsAt"`
	xxx_hidden_DateUpdated *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateErased  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_Vendor      *Party                 `protobuf:"bytes,16,opt,name=vendor"`
	xxx_hidden_Cost        int64                  `protobuf:"varint,17,opt,name=cost"`
	xxx_hidden_Currency    string                 `protobuf:"bytes,18,opt,name=currency"`
	xxx_hidden_CompletedAt *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=completed_at,json=completedAt"`
	xxx_hidden_Blocking    bool                   `protobuf:"varint,20,opt,name=blocking"`
	xxx_hidden_EveryDays   int32                  `protobuf:"varint,21,opt,name=every_days,json=everyDays"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WorkOrder) Reset() {
	*x = WorkOrder{}
	mi := &file_rove_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkOrder) ProtoMessage() {}

func (x *WorkOrder) ProtoReflect() protoreflect.Message {
	mi := &file_rove_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WorkOrder) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *WorkOrder) GetTenant() *Tenant {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *WorkOrder) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *WorkOrder) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *WorkOrder) GetAsset() *Asset {
	if x != nil {
		return x.xxx_hidden_Asset
	}
	return nil
}

func (x *WorkOrder) GetKind() string {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return ""
}

func (x *WorkOrder) GetStatus() string {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ""
}

func (x *WorkOrder) GetBeginsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_BeginsAt
	}
	return nil
}

func (x *WorkOrder) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndsAt
	}
	return nil
}

func (x *WorkOrder) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *WorkOrder) GetDateErased() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return nil
}

func (x *WorkOrder) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *WorkOrder) GetVendor() *Party {
	if x != nil {
		return x.xxx_hidden_Vendor
	}
	return nil
}

func (x *WorkOrder) GetCost() int64 {
	if x != nil {
		return x.xxx_hidden_Cost
	}
	return 0
}

func (x *WorkOrder) GetCurrency() string {
	if x != nil {
		return x.xxx_hidden_Currency
	}
	return ""
}

func (x *WorkOrder) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CompletedAt
	}
	return nil
}

func (x *WorkOrder) GetBlocking() bool {
	if x != nil {
		return x.xxx_hidden_Blocking
	}
	return false
}

func (x *WorkOrder) GetEveryDays() int32 {
	if x != nil {
		return x.xxx_hidden_EveryDays
	}
	return 0
}

func (x *WorkOrder) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *WorkOrder) SetTenant(v *Tenant) {
	x.xxx_hidden_Tenant = v
}

func (x *WorkOrder) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *WorkOrder) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *WorkOrder) SetAsset(v *Asset) {
	x.xxx_hidden_Asset = v
}

func (x *WorkOrder) SetKind(v string) {
	x.xxx_hidden_Kind = v
}

func (x *WorkOrder) SetStatus(v string) {
	x.xxx_hidden_Status = v
}

func (x *WorkOrder) SetBeginsAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_BeginsAt = v
}

func (x *WorkOrder) SetEndsAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndsAt = v
}

func (x *WorkOrder) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *WorkOrder) SetDateErased(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateErased = v
}

func (x *WorkOrder) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *WorkOrder) SetVendor(v *Party) {
	x.xxx_hidden_Vendor = v
}

func (x *WorkOrder) SetCost(v int64) {
	x.xxx_hidden_Cost = v
}

func (x *WorkOrder) SetCurrency(v string) {
	x.xxx_hidden_Currency = v
}

func (x *WorkOrder) SetCompletedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CompletedAt = v
}

func (x *WorkOrder) SetBlocking(v bool) {
	x.xxx_hidden_Blocking = v
}

func (x *WorkOrder) SetEveryDays(v int32) {
	x.xxx_hidden_EveryDays = v
}

func (x *WorkOrder) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *WorkOrder) HasAsset() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Asset != nil
}

func (x *WorkOrder) HasBeginsAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BeginsAt != nil
}

func (x *WorkOrder) HasEndsAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndsAt != nil
}

func (x *WorkOrder) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *WorkOrder) HasDateErased() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateErased != nil
}

func (x *WorkOrder) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *WorkOrder) HasVendor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Vendor != nil
}

func (x *WorkOrder) HasCompletedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CompletedAt != nil
}

func (x *WorkOrder) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *WorkOrder) ClearAsset() {
	x.xxx_hidden_Asset = nil
}

func (x *WorkOrder) ClearBeginsAt() {
	x.xxx_hidden_BeginsAt = nil
}

func (x *WorkOrder) ClearEndsAt() {
	x.xxx_hidden_EndsAt = nil
}

func (x *WorkOrder) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *WorkOrder) ClearDateErased() {
	x.xxx_hidden_DateErased = nil
}

func (x *WorkOrder) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

func (x *WorkOrder) ClearVendor() {
	x.xxx_hidden_Vendor = nil
}

func (x *WorkOrder) ClearCompletedAt() {
	x.xxx_hidden_CompletedAt = nil
}

type WorkOrder_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     []byte
	Tenant *Tenant
	Name   string
	Desc   string
	Asset  *Asset
	// repair | inspection | maintenance | rma
	Kind string
	// open | scheduled | in_progress | done | cancelled
	Status      string
	BeginsAt    *timestamppb.Timestamp
	EndsAt      *timestamppb.Timestamp
	DateUpdated *timestamppb.Timestamp
	DateErased  *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
	Vendor      *Party
	Cost        int64
	Currency    string
	CompletedAt *timestamppb.Timestamp
	Blocking    bool
	// For a recurring inspection: how many days after this one the next is due.
	EveryDays int32
}

func (b0 WorkOrder_builder) Build() *WorkOrder {
	m0 := &WorkOrder{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Asset = b.Asset
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_BeginsAt = b.BeginsAt
	x.xxx_hidden_EndsAt = b.EndsAt
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateErased = b.DateErased
	x.xxx_hidden_DateCreated = b.DateCreated
	x.xxx_hidden_Vendor = b.Vendor
	x.xxx_hidden_Cost = b.Cost
	x.xxx_hidden_Currency = b.Currency
	x.xxx_hidden_CompletedAt = b.CompletedAt
	x.xxx_hidden_Blocking = b.Blocking
	x.xxx_hidden_EveryDays = b.EveryDays
	return m0
}

// Purchase is where assets and stock came from, and what they cost.
type Purchase struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *Tenant                `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Name        string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Vendor      *Party                 `protobuf:"bytes,8,opt,name=vendor"`
	xxx_hidden_Reference   string                 `protobuf:"bytes,9,opt,name=reference"`
	xxx_hidden_Status      string                 `protobuf:"bytes,10,opt,name=status"`
	xxx_hidden_OrderedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=ordered_at,json=orderedAt"`
	xxx_hidden_ReceivedAt  *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=received_at,json=receivedAt"`
	xxx_hidden_DateUpdated *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateErased  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_Currency    string                 `protobuf:"bytes,16,opt,name=currency"`
	xxx_hidden_Total       int64                  `protobuf:"varint,17,opt,name=total"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Purchase) Reset() {
	*x = Purchase{}
	mi := &file_rove_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Purchase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchase) ProtoMessage() {}

func (x *Purchase) ProtoReflect() protoreflect.Message {
	mi := &file_rove_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Purchase) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Purchase) GetTenant() *Tenant {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *Purchase) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Purchase) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *Purchase) GetVendor() *Party {
	if x != nil {
		return x.xxx_hidden_Vendor
	}
	return nil
}

func (x *Purchase) GetReference() string {
	if x != nil {
		return x.xxx_hidden_Reference
	}
	return ""
}

func (x *Purchase) GetStatus() string {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ""
}

func (x *Purchase) GetOrderedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_OrderedAt
	}
	return nil
}

func (x *Purchase) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ReceivedAt
	}
	return nil
}

func (x *Purchase) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *Purchase) GetDateErased() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return nil
}

func (x *Purchase) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Purchase) GetCurrency() string {
	if x != nil {
		return x.xxx_hidden_Currency
	}
	return ""
}

func (x *Purchase) GetTotal() int64 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *Purchase) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Purchase) SetTenant(v *Tenant) {
	x.xxx_hidden_Tenant = v
}

func (x *Purchase) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Purchase) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *Purchase) SetVendor(v *Party) {
	x.xxx_hidden_Vendor = v
}

func (x *Purchase) SetReference(v string) {
	x.xxx_hidden_Reference = v
}

func (x *Purchase) SetStatus(v string) {
	x.xxx_hidden_Status = v
}

func (x *Purchase) SetOrderedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_OrderedAt = v
}

func (x *Purchase) SetReceivedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ReceivedAt = v
}

func (x *Purchase) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *Purchase) SetDateErased(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateErased = v
}

func (x *Purchase) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Purchase) SetCurrency(v string) {
	x.xxx_hidden_Currency = v
}

func (x *Purchase) SetTotal(v int64) {
	x.xxx_hidden_Total = v
}

func (x *Purchase) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *Purchase) HasVendor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Vendor != nil
}

func (x *Purchase) HasOrderedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OrderedAt != nil
}

func (x *Purchase) HasReceivedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ReceivedAt != nil
}

func (x *Purchase) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *Purchase) HasDateErased() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateErased != nil
}

func (x *Purchase) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Purchase) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *Purchase) ClearVendor() {
	x.xxx_hidden_Vendor = nil
}

func (x *Purchase) ClearOrderedAt() {
	x.xxx_hidden_OrderedAt = nil
}

func (x *Purchase) ClearReceivedAt() {
	x.xxx_hidden_ReceivedAt = nil
}

func (x *Purchase) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *Purchase) ClearDateErased() {
	x.xxx_hidden_DateErased = nil
}

func (x *Purchase) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Purchase_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        []byte
	Tenant    *Tenant
	Name      string
	Desc      string
	Vendor    *Party
	Reference string
	// ordered | received | cancelled
	Status      string
	OrderedAt   *timestamppb.Timestamp
	ReceivedAt  *timestamppb.Timestamp
	DateUpdated *timestamppb.Timestamp
	DateErased  *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
	Currency    string
	Total       int64
}

func (b0 Purchase_builder) Build() *Purchase {
	m0 := &Purchase{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Vendor = b.Vendor
	x.xxx_hidden_Reference = b.Reference
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_OrderedAt = b.OrderedAt
	x.xxx_hidden_ReceivedAt = b.ReceivedAt
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateErased = b.DateErased
	x.xxx_hidden_DateCreated = b.DateCreated
	x.xxx_hidden_Currency = b.Currency
	x.xxx_hidden_Total = b.Total
	return m0
}

// PurchaseLine is one thing bought: a model and a quantity, received into
// assets or stock.
type PurchaseLine struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant           *Tenant                `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Desc             string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Purchase         *Purchase              `protobuf:"bytes,8,opt,name=purchase"`
	xxx_hidden_Model            *ItemModel             `protobuf:"bytes,9,opt,name=model"`
	xxx_hidden_Quantity         int64                  `protobuf:"varint,10,opt,name=quantity"`
	xxx_hidden_UnitCost         int64                  `protobuf:"varint,11,opt,name=unit_cost,json=unitCost"`
	xxx_hidden_ReceivedQuantity int64                  `protobuf:"varint,12,opt,name=received_quantity,json=receivedQuantity"`
	xxx_hidden_DateUpdated      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_ReceiveAs        string                 `protobuf:"bytes,16,opt,name=receive_as,json=receiveAs"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *PurchaseLine) Reset() {
	*x = PurchaseLine{}
	mi := &file_rove_work_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseLine) ProtoMessage() {}

func (x *PurchaseLine) ProtoReflect() protoreflect.Message {
	mi := &file_rove_work_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PurchaseLine) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *PurchaseLine) GetTenant() *Tenant {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *PurchaseLine) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *PurchaseLine) GetPurchase() *Purchase {
	if x != nil {
		return x.xxx_hidden_Purchase
	}
	return nil
}

func (x *PurchaseLine) GetModel() *ItemModel {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return nil
}

func (x *PurchaseLine) GetQuantity() int64 {
	if x != nil {
		return x.xxx_hidden_Quantity
	}
	return 0
}

func (x *PurchaseLine) GetUnitCost() int64 {
	if x != nil {
		return x.xxx_hidden_UnitCost
	}
	return 0
}

func (x *PurchaseLine) GetReceivedQuantity() int64 {
	if x != nil {
		return x.xxx_hidden_ReceivedQuantity
	}
	return 0
}

func (x *PurchaseLine) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *PurchaseLine) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *PurchaseLine) GetReceiveAs() string {
	if x != nil {
		return x.xxx_hidden_ReceiveAs
	}
	return ""
}

func (x *PurchaseLine) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *PurchaseLine) SetTenant(v *Tenant) {
	x.xxx_hidden_Tenant = v
}

func (x *PurchaseLine) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *PurchaseLine) SetPurchase(v *Purchase) {
	x.xxx_hidden_Purchase = v
}

func (x *PurchaseLine) SetModel(v *ItemModel) {
	x.xxx_hidden_Model = v
}

func (x *PurchaseLine) SetQuantity(v int64) {
	x.xxx_hidden_Quantity = v
}

func (x *PurchaseLine) SetUnitCost(v int64) {
	x.xxx_hidden_UnitCost = v
}

func (x *PurchaseLine) SetReceivedQuantity(v int64) {
	x.xxx_hidden_ReceivedQuantity = v
}

func (x *PurchaseLine) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *PurchaseLine) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *PurchaseLine) SetReceiveAs(v string) {
	x.xxx_hidden_ReceiveAs = v
}

func (x *PurchaseLine) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *PurchaseLine) HasPurchase() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Purchase != nil
}

func (x *PurchaseLine) HasModel() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Model != nil
}

func (x *PurchaseLine) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *PurchaseLine) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *PurchaseLine) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *PurchaseLine) ClearPurchase() {
	x.xxx_hidden_Purchase = nil
}

func (x *PurchaseLine) ClearModel() {
	x.xxx_hidden_Model = nil
}

func (x *PurchaseLine) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *PurchaseLine) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type PurchaseLine_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id               []byte
	Tenant           *Tenant
	Desc             string
	Purchase         *Purchase
	Model            *ItemModel
	Quantity         int64
	UnitCost         int64
	ReceivedQuantity int64
	DateUpdated      *timestamppb.Timestamp
	DateCreated      *timestamppb.Timestamp
	// received as: asset | stock
	ReceiveAs string
}

func (b0 PurchaseLine_builder) Build() *PurchaseLine {
	m0 := &PurchaseLine{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Purchase = b.Purchase
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_Quantity = b.Quantity
	x.xxx_hidden_UnitCost = b.UnitCost
	x.xxx_hidden_ReceivedQuantity = b.ReceivedQuantity
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateCreated = b.DateCreated
	x.xxx_hidden_ReceiveAs = b.ReceiveAs
	return m0
}

var File_rove_work_proto protoreflect.FileDescriptor

const file_rove_work_proto_rawDesc = "" +
	"\n" +
	"\x0frove/work.proto\x12\x04rove\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\x1a\x10rove/asset.proto\x1a\x12rove/catalog.proto\x1a\x0erove/org.proto\x1a\x18rove/payday/tenant.proto\"\xbc\a\n" +
	"\tWorkOrder\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12,\n" +
	"\x06tenant\x18\x02 \x01(\v2\f.rove.TenantB\x06\xf2\x82\x16\x02@\x01R\x06tenant\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12)\n" +
	"\x05asset\x18\b \x01(\v2\v.rove.AssetB\x06\xf2\x82\x16\x02@\x01R\x05asset\x12\x12\n" +
	"\x04kind\x18\t \x01(\tR\x04kind\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12?\n" +
	"\tbegins_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x028\x01R\bbeginsAt\x12;\n" +
	"\aends_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x028\x01R\x06endsAt\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12D\n" +
	"\vdate_erased\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x92\x01\x00R\n" +
	"dateErased\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated\x12+\n" +
	"\x06vendor\x18\x10 \x01(\v2\v.rove.PartyB\x06\xf2\x82\x16\x028\x01R\x06vendor\x12\x12\n" +
	"\x04cost\x18\x11 \x01(\x03R\x04cost\x12\x1a\n" +
	"\bcurrency\x18\x12 \x01(\tR\bcurrency\x12E\n" +
	"\fcompleted_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x028\x01R\vcompletedAt\x12\x1a\n" +
	"\bblocking\x18\x14 \x01(\bR\bblocking\x12\x1d\n" +
	"\n" +
	"every_days\x18\x15 \x01(\x05R\teveryDays:\xaf\x01\xca\xfc\x15:\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a\x12\x12\x05asset\x1a\t\n" +
	"\x05asset\x10\b\x8a\xbb\x16m\b!2O\n" +
	"\x12\n" +
	"\x0e\n" +
	"\fdate_created\x10\x01\n" +
	"\b\n" +
	"\x04\n" +
	"\x02id\x10\x01\x1a\x05\n" +
	"\x03ref\x1a\a\n" +
	"\x05asset\x1a\b\n" +
	"\x06status\x1a\x06\n" +
	"\x04kind\x1a\b\n" +
	"\x06vendor d(\xf4\x03:\x00\"\x16\n" +
	"\x06tenant\"\fasset.tenant\"\xe7\x05\n" +
	"\bPurchase\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12,\n" +
	"\x06tenant\x18\x02 \x01(\v2\f.rove.TenantB\x06\xf2\x82\x16\x02@\x01R\x06tenant\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12+\n" +
	"\x06vendor\x18\b \x01(\v2\v.rove.PartyB\x06\xf2\x82\x16\x028\x01R\x06vendor\x12\x1c\n" +
	"\treference\x18\t \x01(\tR\treference\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12B\n" +
	"\n" +
	"ordered_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x82\x01\x00R\torderedAt\x12C\n" +
	"\vreceived_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x028\x01R\n" +
	"receivedAt\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12D\n" +
	"\vdate_erased\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x92\x01\x00R\n" +
	"dateErased\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated\x12\x1a\n" +
	"\bcurrency\x18\x10 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05total\x18\x11 \x01(\x03R\x05total:r\xca\xfc\x15&\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x8a\xbb\x16D\b\"2>\n" +
	"\x12\n" +
	"\x0e\n" +
	"\fdate_created\x10\x01\n" +
	"\b\n" +
	"\x04\n" +
	"\x02id\x10\x01\x1a\x05\n" +
	"\x03ref\x1a\b\n" +
	"\x06vendor\x1a\b\n" +
	"\x06status d(\xf4\x03:\x00\"\x91\x05\n" +
	"\fPurchaseLine\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12,\n" +
	"\x06tenant\x18\x02 \x01(\v2\f.rove.TenantB\x06\xf2\x82\x16\x02@\x01R\x06tenant\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x122\n" +
	"\bpurchase\x18\b \x01(\v2\x0e.rove.PurchaseB\x06\xf2\x82\x16\x02@\x01R\bpurchase\x12-\n" +
	"\x05model\x18\t \x01(\v2\x0f.rove.ItemModelB\x06\xf2\x82\x16\x028\x01R\x05model\x12\x1a\n" +
	"\bquantity\x18\n" +
	" \x01(\x03R\bquantity\x12\x1b\n" +
	"\tunit_cost\x18\v \x01(\x03R\bunitCost\x12+\n" +
	"\x11received_quantity\x18\f \x01(\x03R\x10receivedQuantity\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated\x12\x1d\n" +
	"\n" +
	"receive_as\x18\x10 \x01(\tR\treceiveAs:\xa7\x01\xca\xfc\x15@\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a\x18\x12\bpurchase\x1a\f\n" +
	"\bpurchase\x10\b\x8a\xbb\x16_\b#2<\n" +
	"\x10\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x06\n" +
	"\x04\n" +
	"\x02id\x1a\x05\n" +
	"\x03ref\x1a\n" +
	"\n" +
	"\bpurchase\x1a\a\n" +
	"\x05model \xc8\x01(\xe8\aB\x02\n" +
	"\x00\"\x19\n" +
	"\x06tenant\"\x0fpurchase.tenantB\x1fZ\x18github.com/lesomnus/rove\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_rove_work_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rove_work_proto_goTypes = []any{
	(*WorkOrder)(nil),             // 0: rove.WorkOrder
	(*Purchase)(nil),              // 1: rove.Purchase
	(*PurchaseLine)(nil),          // 2: rove.PurchaseLine
	(*Tenant)(nil),                // 3: rove.Tenant
	(*Asset)(nil),                 // 4: rove.Asset
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*Party)(nil),                 // 6: rove.Party
	(*ItemModel)(nil),             // 7: rove.ItemModel
}
var file_rove_work_proto_depIdxs = []int32{
	3,  // 0: rove.WorkOrder.tenant:type_name -> rove.Tenant
	4,  // 1: rove.WorkOrder.asset:type_name -> rove.Asset
	5,  // 2: rove.WorkOrder.begins_at:type_name -> google.protobuf.Timestamp
	5,  // 3: rove.WorkOrder.ends_at:type_name -> google.protobuf.Timestamp
	5,  // 4: rove.WorkOrder.date_updated:type_name -> google.protobuf.Timestamp
	5,  // 5: rove.WorkOrder.date_erased:type_name -> google.protobuf.Timestamp
	5,  // 6: rove.WorkOrder.date_created:type_name -> google.protobuf.Timestamp
	6,  // 7: rove.WorkOrder.vendor:type_name -> rove.Party
	5,  // 8: rove.WorkOrder.completed_at:type_name -> google.protobuf.Timestamp
	3,  // 9: rove.Purchase.tenant:type_name -> rove.Tenant
	6,  // 10: rove.Purchase.vendor:type_name -> rove.Party
	5,  // 11: rove.Purchase.ordered_at:type_name -> google.protobuf.Timestamp
	5,  // 12: rove.Purchase.received_at:type_name -> google.protobuf.Timestamp
	5,  // 13: rove.Purchase.date_updated:type_name -> google.protobuf.Timestamp
	5,  // 14: rove.Purchase.date_erased:type_name -> google.protobuf.Timestamp
	5,  // 15: rove.Purchase.date_created:type_name -> google.protobuf.Timestamp
	3,  // 16: rove.PurchaseLine.tenant:type_name -> rove.Tenant
	1,  // 17: rove.PurchaseLine.purchase:type_name -> rove.Purchase
	7,  // 18: rove.PurchaseLine.model:type_name -> rove.ItemModel
	5,  // 19: rove.PurchaseLine.date_updated:type_name -> google.protobuf.Timestamp
	5,  // 20: rove.PurchaseLine.date_created:type_name -> google.protobuf.Timestamp
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_rove_work_proto_init() }
func file_rove_work_proto_init() {
	if File_rove_work_proto != nil {
		return
	}
	file_rove_asset_proto_init()
	file_rove_catalog_proto_init()
	file_rove_org_proto_init()
	file_rove_payday_tenant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rove_work_proto_rawDesc), len(file_rove_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rove_work_proto_goTypes,
		DependencyIndexes: file_rove_work_proto_depIdxs,
		MessageInfos:      file_rove_work_proto_msgTypes,
	}.Build()
	File_rove_work_proto = out.File
	file_rove_work_proto_goTypes = nil
	file_rove_work_proto_depIdxs = nil
}
