// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: rove/custody.proto

package schema

import (
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	edge "github.com/protobuf-orm/ent/schema/edge"
	field "github.com/protobuf-orm/ent/schema/field"
	index "github.com/protobuf-orm/ent/schema/index"
)

type Custody struct {
	ent.Schema
}

func (Custody) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.String("desc"),
		field.String("kind"),
		field.String("status"),
		field.Time("issued_at").
			Optional(),
		field.Time("due_at").
			Nillable().
			Optional(),
		field.Time("date_updated"),
		field.Time("date_erased").
			Nillable().
			Optional(),
		field.Time("date_created").
			Immutable().
			Optional(),
		field.Time("acknowledged_at").
			Nillable().
			Optional(),
		field.Time("returned_at").
			Nillable().
			Optional(),
		field.Uuid("reservation_id").
			Nillable().
			Optional(),
		field.Uuid("issued_by").
			Nillable().
			Optional(),
		field.Bool("overdue_noticed"),
		field.Uuid("tenant_id").
			Immutable(),
		field.Uuid("party_id").
			Immutable(),
	}
}

func (Custody) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("tenant", Tenant.Type).
			Unique().
			Field("tenant_id").
			Required().
			Immutable(),
		edge.To("party", Party.Type).
			Unique().
			Field("party_id").
			Required().
			Immutable(),
	}
}

func (Custody) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("date_created", "id"),
		index.Fields("issued_at").
			Edges("party"),
	}
}

func (Custody) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "custody"},
	}
}

type CustodyLine struct {
	ent.Schema
}

func (CustodyLine) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.Int64("quantity"),
		field.Int64("returned_quantity"),
		field.Time("date_updated"),
		field.Time("date_created").
			Immutable().
			Optional(),
		field.Time("out_at").
			Optional(),
		field.Time("returned_at").
			Nillable().
			Optional(),
		field.String("condition_out"),
		field.String("condition_in"),
		field.Uuid("tenant_id").
			Immutable(),
		field.Uuid("custody_id").
			Immutable(),
		field.Uuid("asset_id").
			Optional().
			Immutable(),
		field.Uuid("stock_id").
			Optional().
			Immutable(),
	}
}

func (CustodyLine) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("tenant", Tenant.Type).
			Unique().
			Field("tenant_id").
			Required().
			Immutable(),
		edge.To("custody", Custody.Type).
			Unique().
			Field("custody_id").
			Required().
			Immutable(),
		edge.To("asset", Asset.Type).
			Unique().
			Field("asset_id").
			Immutable(),
		edge.To("stock", Stock.Type).
			Unique().
			Field("stock_id").
			Immutable(),
	}
}

func (CustodyLine) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("date_created", "id"),
		index.Edges("custody"),
		index.Edges("asset"),
	}
}

func (CustodyLine) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "custodyline"},
	}
}
