// Code generated by ent, DO NOT EDIT.

package treelock

import (
	"time"
	"uuid"

	"github.com/lesomnus/rove/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldLTE(FieldId, id))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v uint64) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldEQ(FieldVersion, v))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldEQ(FieldDateUpdated, v))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldEQ(FieldDateCreated, v))
}

// TenantId applies equality check predicate on the "tenant_id" field. It's identical to TenantIdEQ.
func TenantId(v uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldEQ(FieldTenantId, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v uint64) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v uint64) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...uint64) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...uint64) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v uint64) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v uint64) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v uint64) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v uint64) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldLTE(FieldVersion, v))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldLTE(FieldDateUpdated, v))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldLTE(FieldDateCreated, v))
}

// DateCreatedIsNil applies the IsNil predicate on the "date_created" field.
func DateCreatedIsNil() predicate.TreeLock {
	return predicate.TreeLock(sql.FieldIsNull(FieldDateCreated))
}

// DateCreatedNotNil applies the NotNil predicate on the "date_created" field.
func DateCreatedNotNil() predicate.TreeLock {
	return predicate.TreeLock(sql.FieldNotNull(FieldDateCreated))
}

// TenantIdEQ applies the EQ predicate on the "tenant_id" field.
func TenantIdEQ(v uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldEQ(FieldTenantId, v))
}

// TenantIdNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIdNEQ(v uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldNEQ(FieldTenantId, v))
}

// TenantIdIn applies the In predicate on the "tenant_id" field.
func TenantIdIn(vs ...uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldIn(FieldTenantId, vs...))
}

// TenantIdNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIdNotIn(vs ...uuid.UUID) predicate.TreeLock {
	return predicate.TreeLock(sql.FieldNotIn(FieldTenantId, vs...))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.TreeLock {
	return predicate.TreeLock(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.TreeLock {
	return predicate.TreeLock(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TreeLock) predicate.TreeLock {
	return predicate.TreeLock(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TreeLock) predicate.TreeLock {
	return predicate.TreeLock(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TreeLock) predicate.TreeLock {
	return predicate.TreeLock(sql.NotPredicates(p))
}
