// Code generated by ent, DO NOT EDIT.

package fact

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the fact type in the database.
	Label = "fact"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldCleared holds the string denoting the cleared field in the database.
	FieldCleared = "cleared"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldValidFrom holds the string denoting the valid_from field in the database.
	FieldValidFrom = "valid_from"
	// FieldEventId holds the string denoting the event_id field in the database.
	FieldEventId = "event_id"
	// FieldSupersededAt holds the string denoting the superseded_at field in the database.
	FieldSupersededAt = "superseded_at"
	// FieldSupersededBy holds the string denoting the superseded_by field in the database.
	FieldSupersededBy = "superseded_by"
	// FieldTenantId holds the string denoting the tenant_id field in the database.
	FieldTenantId = "tenant_id"
	// FieldAssetId holds the string denoting the asset_id field in the database.
	FieldAssetId = "asset_id"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeAsset holds the string denoting the asset edge name in mutations.
	EdgeAsset = "asset"
	// Table holds the table name of the fact in the database.
	Table = "fact"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "fact"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenant"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// AssetTable is the table that holds the asset relation/edge.
	AssetTable = "fact"
	// AssetInverseTable is the table name for the Asset entity.
	// It exists in this package in order to avoid circular dependency with the "asset" package.
	AssetInverseTable = "asset"
	// AssetColumn is the table column denoting the asset relation/edge.
	AssetColumn = "asset_id"
)

// Columns holds all SQL columns for fact fields.
var Columns = []string{
	FieldId,
	FieldKey,
	FieldValue,
	FieldCleared,
	FieldDateUpdated,
	FieldDateCreated,
	FieldValidFrom,
	FieldEventId,
	FieldSupersededAt,
	FieldSupersededBy,
	FieldTenantId,
	FieldAssetId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Fact queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByCleared orders the results by the cleared field.
func ByCleared(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCleared, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByValidFrom orders the results by the valid_from field.
func ByValidFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidFrom, opts...).ToFunc()
}

// ByEventId orders the results by the event_id field.
func ByEventId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventId, opts...).ToFunc()
}

// BySupersededAt orders the results by the superseded_at field.
func BySupersededAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupersededAt, opts...).ToFunc()
}

// BySupersededBy orders the results by the superseded_by field.
func BySupersededBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupersededBy, opts...).ToFunc()
}

// ByTenantId orders the results by the tenant_id field.
func ByTenantId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantId, opts...).ToFunc()
}

// ByAssetId orders the results by the asset_id field.
func ByAssetId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssetId, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByAssetField orders the results by asset field.
func ByAssetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssetStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(TenantInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
	)
}
func newAssetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(AssetInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, AssetTable, AssetColumn),
	)
}
