// Code generated by ent, DO NOT EDIT.

package fact

import (
	"context"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/rove/internal/ent/predicate"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Mutation represents an operation that mutates the Fact nodes in the graph.
type Mutation struct {
	op            ent.Op
	typ           string
	key           *string
	value         *string
	cleared       *bool
	date_updated  *time.Time
	date_created  *time.Time
	valid_from    *time.Time
	event_id      *uuid.UUID
	superseded_at *time.Time
	superseded_by *uuid.UUID
	clearedFields map[string]struct{}
	tenant        *uuid.UUID
	clearedtenant bool
	asset         *uuid.UUID
	clearedasset  bool
	predicates    []predicate.Fact
}

// NewMutation creates a new Mutation for the Fact entity.
func NewMutation(op ent.Op) *Mutation {
	return &Mutation{
		op:            op,
		typ:           "Fact",
		clearedFields: make(map[string]struct{}),
	}
}

// Predicates returns the list of predicates set on the mutation.
func (m *Mutation) Predicates() []predicate.Fact {
	return m.predicates
}

// SetKey sets the "key" field.
func (m *Mutation) SetKey(s string) {
	m.key = &s
}

// Key returns the value of the "key" field in the mutation.
func (m *Mutation) Key() (r string, exists bool) {
	v := m.key
	if v == nil {
		return
	}
	return *v, true
}

// ResetKey resets all changes to the "key" field.
func (m *Mutation) ResetKey() {
	m.key = nil
}

// SetValue sets the "value" field.
func (m *Mutation) SetValue(s string) {
	m.value = &s
}

// Value returns the value of the "value" field in the mutation.
func (m *Mutation) Value() (r string, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// ResetValue resets all changes to the "value" field.
func (m *Mutation) ResetValue() {
	m.value = nil
}

// SetCleared sets the "cleared" field.
func (m *Mutation) SetCleared(b bool) {
	m.cleared = &b
}

// Cleared returns the value of the "cleared" field in the mutation.
func (m *Mutation) Cleared() (r bool, exists bool) {
	v := m.cleared
	if v == nil {
		return
	}
	return *v, true
}

// ResetCleared resets all changes to the "cleared" field.
func (m *Mutation) ResetCleared() {
	m.cleared = nil
}

// SetDateUpdated sets the "date_updated" field.
func (m *Mutation) SetDateUpdated(t time.Time) {
	m.date_updated = &t
}

// DateUpdated returns the value of the "date_updated" field in the mutation.
func (m *Mutation) DateUpdated() (r time.Time, exists bool) {
	v := m.date_updated
	if v == nil {
		return
	}
	return *v, true
}

// ResetDateUpdated resets all changes to the "date_updated" field.
func (m *Mutation) ResetDateUpdated() {
	m.date_updated = nil
}

// SetDateCreated sets the "date_created" field.
func (m *Mutation) SetDateCreated(t time.Time) {
	m.date_created = &t
}

// DateCreated returns the value of the "date_created" field in the mutation.
func (m *Mutation) DateCreated() (r time.Time, exists bool) {
	v := m.date_created
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateCreated clears the value of the "date_created" field.
func (m *Mutation) ClearDateCreated() {
	m.date_created = nil
	m.clearedFields[FieldDateCreated] = struct{}{}
}

// DateCreatedCleared returns if the "date_created" field was cleared in this mutation.
func (m *Mutation) DateCreatedCleared() bool {
	_, ok := m.clearedFields[FieldDateCreated]
	return ok
}

// ResetDateCreated resets all changes to the "date_created" field.
func (m *Mutation) ResetDateCreated() {
	m.date_created = nil
	delete(m.clearedFields, FieldDateCreated)
}

// SetValidFrom sets the "valid_from" field.
func (m *Mutation) SetValidFrom(t time.Time) {
	m.valid_from = &t
}

// ValidFrom returns the value of the "valid_from" field in the mutation.
func (m *Mutation) ValidFrom() (r time.Time, exists bool) {
	v := m.valid_from
	if v == nil {
		return
	}
	return *v, true
}

// ClearValidFrom clears the value of the "valid_from" field.
func (m *Mutation) ClearValidFrom() {
	m.valid_from = nil
	m.clearedFields[FieldValidFrom] = struct{}{}
}

// ValidFromCleared returns if the "valid_from" field was cleared in this mutation.
func (m *Mutation) ValidFromCleared() bool {
	_, ok := m.clearedFields[FieldValidFrom]
	return ok
}

// ResetValidFrom resets all changes to the "valid_from" field.
func (m *Mutation) ResetValidFrom() {
	m.valid_from = nil
	delete(m.clearedFields, FieldValidFrom)
}

// SetEventId sets the "event_id" field.
func (m *Mutation) SetEventId(u uuid.UUID) {
	m.event_id = &u
}

// EventId returns the value of the "event_id" field in the mutation.
func (m *Mutation) EventId() (r uuid.UUID, exists bool) {
	v := m.event_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetEventId resets all changes to the "event_id" field.
func (m *Mutation) ResetEventId() {
	m.event_id = nil
}

// SetSupersededAt sets the "superseded_at" field.
func (m *Mutation) SetSupersededAt(t time.Time) {
	m.superseded_at = &t
}

// SupersededAt returns the value of the "superseded_at" field in the mutation.
func (m *Mutation) SupersededAt() (r time.Time, exists bool) {
	v := m.superseded_at
	if v == nil {
		return
	}
	return *v, true
}

// ClearSupersededAt clears the value of the "superseded_at" field.
func (m *Mutation) ClearSupersededAt() {
	m.superseded_at = nil
	m.clearedFields[FieldSupersededAt] = struct{}{}
}

// SupersededAtCleared returns if the "superseded_at" field was cleared in this mutation.
func (m *Mutation) SupersededAtCleared() bool {
	_, ok := m.clearedFields[FieldSupersededAt]
	return ok
}

// ResetSupersededAt resets all changes to the "superseded_at" field.
func (m *Mutation) ResetSupersededAt() {
	m.superseded_at = nil
	delete(m.clearedFields, FieldSupersededAt)
}

// SetSupersededBy sets the "superseded_by" field.
func (m *Mutation) SetSupersededBy(u uuid.UUID) {
	m.superseded_by = &u
}

// SupersededBy returns the value of the "superseded_by" field in the mutation.
func (m *Mutation) SupersededBy() (r uuid.UUID, exists bool) {
	v := m.superseded_by
	if v == nil {
		return
	}
	return *v, true
}

// ClearSupersededBy clears the value of the "superseded_by" field.
func (m *Mutation) ClearSupersededBy() {
	m.superseded_by = nil
	m.clearedFields[FieldSupersededBy] = struct{}{}
}

// SupersededByCleared returns if the "superseded_by" field was cleared in this mutation.
func (m *Mutation) SupersededByCleared() bool {
	_, ok := m.clearedFields[FieldSupersededBy]
	return ok
}

// ResetSupersededBy resets all changes to the "superseded_by" field.
func (m *Mutation) ResetSupersededBy() {
	m.superseded_by = nil
	delete(m.clearedFields, FieldSupersededBy)
}

// SetTenantId sets the "tenant_id" field.
func (m *Mutation) SetTenantId(u uuid.UUID) {
	m.tenant = &u
}

// TenantId returns the value of the "tenant_id" field in the mutation.
func (m *Mutation) TenantId() (r uuid.UUID, exists bool) {
	v := m.tenant
	if v == nil {
		return
	}
	return *v, true
}

// ResetTenantId resets all changes to the "tenant_id" field.
func (m *Mutation) ResetTenantId() {
	m.tenant = nil
}

// SetAssetId sets the "asset_id" field.
func (m *Mutation) SetAssetId(u uuid.UUID) {
	m.asset = &u
}

// AssetId returns the value of the "asset_id" field in the mutation.
func (m *Mutation) AssetId() (r uuid.UUID, exists bool) {
	v := m.asset
	if v == nil {
		return
	}
	return *v, true
}

// ResetAssetId resets all changes to the "asset_id" field.
func (m *Mutation) ResetAssetId() {
	m.asset = nil
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (m *Mutation) ClearTenant() {
	m.clearedtenant = true
	m.clearedFields[FieldTenantId] = struct{}{}
}

// TenantCleared reports if the "tenant" edge to the Tenant entity was cleared.
func (m *Mutation) TenantCleared() bool {
	return m.clearedtenant
}

// TenantIds returns the "tenant" edge Ids in the mutation.
// Note that Ids always returns len(Ids) <= 1 for unique edges, and you should use
// TenantId instead. It exists only for internal usage by the builders.
func (m *Mutation) TenantIds() (ids []uuid.UUID) {
	if id := m.tenant; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTenant resets all changes to the "tenant" edge.
func (m *Mutation) ResetTenant() {
	m.tenant = nil
	m.clearedtenant = false
}

// ClearAsset clears the "asset" edge to the Asset entity.
func (m *Mutation) ClearAsset() {
	m.clearedasset = true
	m.clearedFields[FieldAssetId] = struct{}{}
}

// AssetCleared reports if the "asset" edge to the Asset entity was cleared.
func (m *Mutation) AssetCleared() bool {
	return m.clearedasset
}

// AssetIds returns the "asset" edge Ids in the mutation.
// Note that Ids always returns len(Ids) <= 1 for unique edges, and you should use
// AssetId instead. It exists only for internal usage by the builders.
func (m *Mutation) AssetIds() (ids []uuid.UUID) {
	if id := m.asset; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAsset resets all changes to the "asset" edge.
func (m *Mutation) ResetAsset() {
	m.asset = nil
	m.clearedasset = false
}

// Where appends a list predicates to the Mutation builder.
func (m *Mutation) Where(ps ...predicate.Fact) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the Mutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *Mutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Fact, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *Mutation) Op() ent.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *Mutation) SetOp(op ent.Op) {
	m.op = op
}

// Type returns the node type of this mutation (Fact).
func (m *Mutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *Mutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.key != nil {
		fields = append(fields, FieldKey)
	}
	if m.value != nil {
		fields = append(fields, FieldValue)
	}
	if m.cleared != nil {
		fields = append(fields, FieldCleared)
	}
	if m.date_updated != nil {
		fields = append(fields, FieldDateUpdated)
	}
	if m.date_created != nil {
		fields = append(fields, FieldDateCreated)
	}
	if m.valid_from != nil {
		fields = append(fields, FieldValidFrom)
	}
	if m.event_id != nil {
		fields = append(fields, FieldEventId)
	}
	if m.superseded_at != nil {
		fields = append(fields, FieldSupersededAt)
	}
	if m.superseded_by != nil {
		fields = append(fields, FieldSupersededBy)
	}
	if m.tenant != nil {
		fields = append(fields, FieldTenantId)
	}
	if m.asset != nil {
		fields = append(fields, FieldAssetId)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *Mutation) Field(name string) (ent.Value, bool) {
	switch name {
	case FieldKey:
		return m.Key()
	case FieldValue:
		return m.Value()
	case FieldCleared:
		return m.Cleared()
	case FieldDateUpdated:
		return m.DateUpdated()
	case FieldDateCreated:
		return m.DateCreated()
	case FieldValidFrom:
		return m.ValidFrom()
	case FieldEventId:
		return m.EventId()
	case FieldSupersededAt:
		return m.SupersededAt()
	case FieldSupersededBy:
		return m.SupersededBy()
	case FieldTenantId:
		return m.TenantId()
	case FieldAssetId:
		return m.AssetId()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *Mutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown Fact field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) SetField(name string, value ent.Value) error {
	switch name {
	case FieldKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKey(v)
		return nil
	case FieldValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	case FieldCleared:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCleared(v)
		return nil
	case FieldDateUpdated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateUpdated(v)
		return nil
	case FieldDateCreated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateCreated(v)
		return nil
	case FieldValidFrom:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValidFrom(v)
		return nil
	case FieldEventId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventId(v)
		return nil
	case FieldSupersededAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSupersededAt(v)
		return nil
	case FieldSupersededBy:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSupersededBy(v)
		return nil
	case FieldTenantId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantId(v)
		return nil
	case FieldAssetId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAssetId(v)
		return nil
	}
	return fmt.Errorf("unknown Fact field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *Mutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *Mutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Fact numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *Mutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(FieldDateCreated) {
		fields = append(fields, FieldDateCreated)
	}
	if m.FieldCleared(FieldValidFrom) {
		fields = append(fields, FieldValidFrom)
	}
	if m.FieldCleared(FieldSupersededAt) {
		fields = append(fields, FieldSupersededAt)
	}
	if m.FieldCleared(FieldSupersededBy) {
		fields = append(fields, FieldSupersededBy)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *Mutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *Mutation) ClearField(name string) error {
	switch name {
	case FieldDateCreated:
		m.ClearDateCreated()
		return nil
	case FieldValidFrom:
		m.ClearValidFrom()
		return nil
	case FieldSupersededAt:
		m.ClearSupersededAt()
		return nil
	case FieldSupersededBy:
		m.ClearSupersededBy()
		return nil
	}
	return fmt.Errorf("unknown Fact nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *Mutation) ResetField(name string) error {
	switch name {
	case FieldKey:
		m.ResetKey()
		return nil
	case FieldValue:
		m.ResetValue()
		return nil
	case FieldCleared:
		m.ResetCleared()
		return nil
	case FieldDateUpdated:
		m.ResetDateUpdated()
		return nil
	case FieldDateCreated:
		m.ResetDateCreated()
		return nil
	case FieldValidFrom:
		m.ResetValidFrom()
		return nil
	case FieldEventId:
		m.ResetEventId()
		return nil
	case FieldSupersededAt:
		m.ResetSupersededAt()
		return nil
	case FieldSupersededBy:
		m.ResetSupersededBy()
		return nil
	case FieldTenantId:
		m.ResetTenantId()
		return nil
	case FieldAssetId:
		m.ResetAssetId()
		return nil
	}
	return fmt.Errorf("unknown Fact field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *Mutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.tenant != nil {
		edges = append(edges, EdgeTenant)
	}
	if m.asset != nil {
		edges = append(edges, EdgeAsset)
	}
	return edges
}

// AddedIds returns all Ids (to other nodes) that were added for the given edge
// name in this mutation.
func (m *Mutation) AddedIds(name string) []ent.Value {
	switch name {
	case EdgeTenant:
		if id := m.tenant; id != nil {
			return []ent.Value{*id}
		}
	case EdgeAsset:
		if id := m.asset; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *Mutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIds returns all Ids (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *Mutation) RemovedIds(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *Mutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedtenant {
		edges = append(edges, EdgeTenant)
	}
	if m.clearedasset {
		edges = append(edges, EdgeAsset)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *Mutation) EdgeCleared(name string) bool {
	switch name {
	case EdgeTenant:
		return m.clearedtenant
	case EdgeAsset:
		return m.clearedasset
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *Mutation) ClearEdge(name string) error {
	switch name {
	case EdgeTenant:
		m.ClearTenant()
		return nil
	case EdgeAsset:
		m.ClearAsset()
		return nil
	}
	return fmt.Errorf("unknown Fact unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *Mutation) ResetEdge(name string) error {
	switch name {
	case EdgeTenant:
		m.ResetTenant()
		return nil
	case EdgeAsset:
		m.ResetAsset()
		return nil
	}
	return fmt.Errorf("unknown Fact edge %s", name)
}
