// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"uuid"

	"github.com/lesomnus/rove/internal/ent/allocation"
	"github.com/lesomnus/rove/internal/ent/asset"
	"github.com/lesomnus/rove/internal/ent/predicate"
	"github.com/lesomnus/rove/internal/ent/tenant"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// AllocationQuery is the builder for querying Allocation entities.
type AllocationQuery struct {
	config
	ctx          *QueryContext
	order        []allocation.OrderOption
	inters       []Interceptor
	predicates   []predicate.Allocation
	withTenant   *TenantQuery
	withResource *AssetQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AllocationQuery builder.
func (_q *AllocationQuery) Where(ps ...predicate.Allocation) *AllocationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AllocationQuery) Limit(limit int) *AllocationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AllocationQuery) Offset(offset int) *AllocationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AllocationQuery) Unique(unique bool) *AllocationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AllocationQuery) Order(o ...allocation.OrderOption) *AllocationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *AllocationQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(allocation.Table, allocation.FieldId, selector),
			sqlgraph.To(tenant.Table, tenant.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, allocation.TenantTable, allocation.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryResource chains the current query on the "resource" edge.
func (_q *AllocationQuery) QueryResource() *AssetQuery {
	query := (&AssetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(allocation.Table, allocation.FieldId, selector),
			sqlgraph.To(asset.Table, asset.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, allocation.ResourceTable, allocation.ResourceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Allocation entity from the query.
// Returns a *NotFoundError when no Allocation was found.
func (_q *AllocationQuery) First(ctx context.Context) (*Allocation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{allocation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AllocationQuery) FirstX(ctx context.Context) *Allocation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstId returns the first Allocation Id from the query.
// Returns a *NotFoundError when no Allocation Id was found.
func (_q *AllocationQuery) FirstId(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).Ids(setContextOp(ctx, _q.ctx, ent.OpQueryFirstId)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{allocation.Label}
		return
	}
	return ids[0], nil
}

// FirstIdX is like FirstId, but panics if an error occurs.
func (_q *AllocationQuery) FirstIdX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstId(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Allocation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Allocation entity is found.
// Returns a *NotFoundError when no Allocation entities are found.
func (_q *AllocationQuery) Only(ctx context.Context) (*Allocation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{allocation.Label}
	default:
		return nil, &NotSingularError{allocation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AllocationQuery) OnlyX(ctx context.Context) *Allocation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyId is like Only, but returns the only Allocation Id in the query.
// Returns a *NotSingularError when more than one Allocation Id is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AllocationQuery) OnlyId(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).Ids(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyId)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{allocation.Label}
	default:
		err = &NotSingularError{allocation.Label}
	}
	return
}

// OnlyIdX is like OnlyId, but panics if an error occurs.
func (_q *AllocationQuery) OnlyIdX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyId(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Allocation entities.
func (_q *AllocationQuery) All(ctx context.Context) ([]*Allocation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Allocation, *AllocationQuery]()
	return withInterceptors[[]*Allocation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AllocationQuery) AllX(ctx context.Context) []*Allocation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Ids executes the query and returns a list of Allocation Ids.
func (_q *AllocationQuery) Ids(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIds)
	if err = _q.Select(allocation.FieldId).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IdsX is like Ids, but panics if an error occurs.
func (_q *AllocationQuery) IdsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.Ids(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AllocationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AllocationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AllocationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AllocationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstId(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AllocationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AllocationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AllocationQuery) Clone() *AllocationQuery {
	if _q == nil {
		return nil
	}
	return &AllocationQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]allocation.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.Allocation{}, _q.predicates...),
		withTenant:   _q.withTenant.Clone(),
		withResource: _q.withResource.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AllocationQuery) WithTenant(opts ...func(*TenantQuery)) *AllocationQuery {
	query := (&TenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// WithResource tells the query-builder to eager-load the nodes that are connected to
// the "resource" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AllocationQuery) WithResource(opts ...func(*AssetQuery)) *AllocationQuery {
	query := (&AssetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withResource = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Kind string `json:"kind,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Allocation.Query().
//		GroupBy(allocation.FieldKind).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AllocationQuery) GroupBy(field string, fields ...string) *AllocationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AllocationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = allocation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Kind string `json:"kind,omitempty"`
//	}
//
//	client.Allocation.Query().
//		Select(allocation.FieldKind).
//		Scan(ctx, &v)
func (_q *AllocationQuery) Select(fields ...string) *AllocationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AllocationSelect{AllocationQuery: _q}
	sbuild.label = allocation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AllocationSelect configured with the given aggregations.
func (_q *AllocationQuery) Aggregate(fns ...AggregateFunc) *AllocationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AllocationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !allocation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AllocationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Allocation, error) {
	var (
		nodes       = []*Allocation{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withTenant != nil,
			_q.withResource != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Allocation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Allocation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *Allocation, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withResource; query != nil {
		if err := _q.loadResource(ctx, query, nodes, nil,
			func(n *Allocation, e *Asset) { n.Edges.Resource = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AllocationQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*Allocation, init func(*Allocation), assign func(*Allocation, *Tenant)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Allocation)
	for i := range nodes {
		fk := nodes[i].TenantId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AllocationQuery) loadResource(ctx context.Context, query *AssetQuery, nodes []*Allocation, init func(*Allocation), assign func(*Allocation, *Asset)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Allocation)
	for i := range nodes {
		fk := nodes[i].ResourceId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(asset.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "resource_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AllocationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AllocationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(allocation.Table, allocation.Columns, sqlgraph.NewFieldSpec(allocation.FieldId, field.TypeUuid))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, allocation.FieldId)
		for i := range fields {
			if fields[i] != allocation.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTenant != nil {
			_spec.Node.AddColumnOnce(allocation.FieldTenantId)
		}
		if _q.withResource != nil {
			_spec.Node.AddColumnOnce(allocation.FieldResourceId)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AllocationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(allocation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = allocation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *AllocationQuery) Modify(modifiers ...func(s *sql.Selector)) *AllocationSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// AllocationGroupBy is the group-by builder for Allocation entities.
type AllocationGroupBy struct {
	selector
	build *AllocationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AllocationGroupBy) Aggregate(fns ...AggregateFunc) *AllocationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AllocationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AllocationQuery, *AllocationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AllocationGroupBy) sqlScan(ctx context.Context, root *AllocationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AllocationSelect is the builder for selecting fields of Allocation entities.
type AllocationSelect struct {
	*AllocationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AllocationSelect) Aggregate(fns ...AggregateFunc) *AllocationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AllocationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AllocationQuery, *AllocationSelect](ctx, _s.AllocationQuery, _s, _s.inters, v)
}

func (_s *AllocationSelect) sqlScan(ctx context.Context, root *AllocationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *AllocationSelect) Modify(modifiers ...func(s *sql.Selector)) *AllocationSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
