// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: rove/payday/audit.proto

package ent

import (
	rove "github.com/lesomnus/rove"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Audit) Proto() *rove.Audit {
	x := &rove.Audit{}
	x.SetId(e.Id[:])
	x.SetTenantId(e.TenantId[:])
	x.SetActorId(e.ActorId[:])
	x.SetTraceId(e.TraceId)
	x.SetAction(e.Action)
	x.SetObjectId(e.ObjectId[:])
	x.SetPatch(e.Patch)
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	x.SetActorTenantId(e.ActorTenantId[:])
	x.SetValue(e.Value)
	if e.CounterpartTenantId != nil {
		x.SetCounterpartTenantId(e.CounterpartTenantId[:])
	}
	x.SetDomain(e.Domain)
	return x
}
