// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/lesomnus/rove/internal/ent/countfinding"
	"github.com/lesomnus/rove/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// CountFindingDelete is the builder for deleting a CountFinding entity.
type CountFindingDelete struct {
	config
	hooks    []Hook
	mutation *CountFindingMutation
}

// Where appends a list predicates to the CountFindingDelete builder.
func (_d *CountFindingDelete) Where(ps ...predicate.CountFinding) *CountFindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CountFindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CountFindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CountFindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(countfinding.Table, sqlgraph.NewFieldSpec(countfinding.FieldId, field.TypeUuid))
	if ps := _d.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CountFindingDeleteOne is the builder for deleting a single CountFinding entity.
type CountFindingDeleteOne struct {
	_d *CountFindingDelete
}

// Where appends a list predicates to the CountFindingDelete builder.
func (_d *CountFindingDeleteOne) Where(ps ...predicate.CountFinding) *CountFindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CountFindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{countfinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CountFindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
