// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"uuid"

	"github.com/lesomnus/rove/internal/ent/custody"
	"github.com/lesomnus/rove/internal/ent/party"
	"github.com/lesomnus/rove/internal/ent/predicate"
	"github.com/lesomnus/rove/internal/ent/tenant"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// CustodyQuery is the builder for querying Custody entities.
type CustodyQuery struct {
	config
	ctx        *QueryContext
	order      []custody.OrderOption
	inters     []Interceptor
	predicates []predicate.Custody
	withTenant *TenantQuery
	withParty  *PartyQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CustodyQuery builder.
func (_q *CustodyQuery) Where(ps ...predicate.Custody) *CustodyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CustodyQuery) Limit(limit int) *CustodyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CustodyQuery) Offset(offset int) *CustodyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CustodyQuery) Unique(unique bool) *CustodyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CustodyQuery) Order(o ...custody.OrderOption) *CustodyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *CustodyQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(custody.Table, custody.FieldId, selector),
			sqlgraph.To(tenant.Table, tenant.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, custody.TenantTable, custody.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParty chains the current query on the "party" edge.
func (_q *CustodyQuery) QueryParty() *PartyQuery {
	query := (&PartyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(custody.Table, custody.FieldId, selector),
			sqlgraph.To(party.Table, party.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, custody.PartyTable, custody.PartyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Custody entity from the query.
// Returns a *NotFoundError when no Custody was found.
func (_q *CustodyQuery) First(ctx context.Context) (*Custody, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{custody.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CustodyQuery) FirstX(ctx context.Context) *Custody {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstId returns the first Custody Id from the query.
// Returns a *NotFoundError when no Custody Id was found.
func (_q *CustodyQuery) FirstId(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).Ids(setContextOp(ctx, _q.ctx, ent.OpQueryFirstId)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{custody.Label}
		return
	}
	return ids[0], nil
}

// FirstIdX is like FirstId, but panics if an error occurs.
func (_q *CustodyQuery) FirstIdX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstId(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Custody entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Custody entity is found.
// Returns a *NotFoundError when no Custody entities are found.
func (_q *CustodyQuery) Only(ctx context.Context) (*Custody, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{custody.Label}
	default:
		return nil, &NotSingularError{custody.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CustodyQuery) OnlyX(ctx context.Context) *Custody {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyId is like Only, but returns the only Custody Id in the query.
// Returns a *NotSingularError when more than one Custody Id is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CustodyQuery) OnlyId(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).Ids(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyId)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{custody.Label}
	default:
		err = &NotSingularError{custody.Label}
	}
	return
}

// OnlyIdX is like OnlyId, but panics if an error occurs.
func (_q *CustodyQuery) OnlyIdX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyId(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Custody entities.
func (_q *CustodyQuery) All(ctx context.Context) ([]*Custody, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Custody, *CustodyQuery]()
	return withInterceptors[[]*Custody](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CustodyQuery) AllX(ctx context.Context) []*Custody {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Ids executes the query and returns a list of Custody Ids.
func (_q *CustodyQuery) Ids(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIds)
	if err = _q.Select(custody.FieldId).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IdsX is like Ids, but panics if an error occurs.
func (_q *CustodyQuery) IdsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.Ids(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CustodyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CustodyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CustodyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CustodyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstId(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CustodyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CustodyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CustodyQuery) Clone() *CustodyQuery {
	if _q == nil {
		return nil
	}
	return &CustodyQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]custody.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.Custody{}, _q.predicates...),
		withTenant: _q.withTenant.Clone(),
		withParty:  _q.withParty.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CustodyQuery) WithTenant(opts ...func(*TenantQuery)) *CustodyQuery {
	query := (&TenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// WithParty tells the query-builder to eager-load the nodes that are connected to
// the "party" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CustodyQuery) WithParty(opts ...func(*PartyQuery)) *CustodyQuery {
	query := (&PartyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParty = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Desc string `json:"desc,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Custody.Query().
//		GroupBy(custody.FieldDesc).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CustodyQuery) GroupBy(field string, fields ...string) *CustodyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CustodyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = custody.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Desc string `json:"desc,omitempty"`
//	}
//
//	client.Custody.Query().
//		Select(custody.FieldDesc).
//		Scan(ctx, &v)
func (_q *CustodyQuery) Select(fields ...string) *CustodySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CustodySelect{CustodyQuery: _q}
	sbuild.label = custody.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CustodySelect configured with the given aggregations.
func (_q *CustodyQuery) Aggregate(fns ...AggregateFunc) *CustodySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CustodyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !custody.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CustodyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Custody, error) {
	var (
		nodes       = []*Custody{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withTenant != nil,
			_q.withParty != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Custody).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Custody{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *Custody, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParty; query != nil {
		if err := _q.loadParty(ctx, query, nodes, nil,
			func(n *Custody, e *Party) { n.Edges.Party = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CustodyQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*Custody, init func(*Custody), assign func(*Custody, *Tenant)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Custody)
	for i := range nodes {
		fk := nodes[i].TenantId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CustodyQuery) loadParty(ctx context.Context, query *PartyQuery, nodes []*Custody, init func(*Custody), assign func(*Custody, *Party)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Custody)
	for i := range nodes {
		fk := nodes[i].PartyId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(party.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "party_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CustodyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CustodyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(custody.Table, custody.Columns, sqlgraph.NewFieldSpec(custody.FieldId, field.TypeUuid))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, custody.FieldId)
		for i := range fields {
			if fields[i] != custody.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTenant != nil {
			_spec.Node.AddColumnOnce(custody.FieldTenantId)
		}
		if _q.withParty != nil {
			_spec.Node.AddColumnOnce(custody.FieldPartyId)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CustodyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(custody.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = custody.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *CustodyQuery) Modify(modifiers ...func(s *sql.Selector)) *CustodySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// CustodyGroupBy is the group-by builder for Custody entities.
type CustodyGroupBy struct {
	selector
	build *CustodyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CustodyGroupBy) Aggregate(fns ...AggregateFunc) *CustodyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CustodyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CustodyQuery, *CustodyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CustodyGroupBy) sqlScan(ctx context.Context, root *CustodyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CustodySelect is the builder for selecting fields of Custody entities.
type CustodySelect struct {
	*CustodyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CustodySelect) Aggregate(fns ...AggregateFunc) *CustodySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CustodySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CustodyQuery, *CustodySelect](ctx, _s.CustodyQuery, _s, _s.inters, v)
}

func (_s *CustodySelect) sqlScan(ctx context.Context, root *CustodyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *CustodySelect) Modify(modifiers ...func(s *sql.Selector)) *CustodySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
