// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/rove/internal/ent/legalhold"
	"github.com/lesomnus/rove/internal/ent/tenant"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// LegalHoldCreate is the builder for creating a LegalHold entity.
type LegalHoldCreate struct {
	config
	mutation *LegalHoldMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *LegalHoldCreate) SetName(v string) *LegalHoldCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDesc sets the "desc" field.
func (_c *LegalHoldCreate) SetDesc(v string) *LegalHoldCreate {
	_c.mutation.SetDesc(v)
	return _c
}

// SetDateLifted sets the "date_lifted" field.
func (_c *LegalHoldCreate) SetDateLifted(v time.Time) *LegalHoldCreate {
	_c.mutation.SetDateLifted(v)
	return _c
}

// SetNillableDateLifted sets the "date_lifted" field if the given value is not nil.
func (_c *LegalHoldCreate) SetNillableDateLifted(v *time.Time) *LegalHoldCreate {
	if v != nil {
		_c.SetDateLifted(*v)
	}
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *LegalHoldCreate) SetDateCreated(v time.Time) *LegalHoldCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *LegalHoldCreate) SetNillableDateCreated(v *time.Time) *LegalHoldCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetTenantId sets the "tenant_id" field.
func (_c *LegalHoldCreate) SetTenantId(v uuid.UUID) *LegalHoldCreate {
	_c.mutation.SetTenantId(v)
	return _c
}

// SetId sets the "id" field.
func (_c *LegalHoldCreate) SetId(v uuid.UUID) *LegalHoldCreate {
	_c.mutation.SetId(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *LegalHoldCreate) SetTenant(v *Tenant) *LegalHoldCreate {
	return _c.SetTenantId(v.Id)
}

// Mutation returns the LegalHoldMutation object of the builder.
func (_c *LegalHoldCreate) Mutation() *LegalHoldMutation {
	return _c.mutation
}

// Save creates the LegalHold in the database.
func (_c *LegalHoldCreate) Save(ctx context.Context) (*LegalHold, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LegalHoldCreate) SaveX(ctx context.Context) *LegalHold {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LegalHoldCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LegalHoldCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LegalHoldCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "LegalHold.name"`)}
	}
	if _, ok := _c.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "LegalHold.desc"`)}
	}
	if _, ok := _c.mutation.TenantId(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "LegalHold.tenant_id"`)}
	}
	if len(_c.mutation.TenantIds()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "LegalHold.tenant"`)}
	}
	return nil
}

func (_c *LegalHoldCreate) sqlSave(ctx context.Context) (*LegalHold, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else {
			var v sql.Null[uuid.UUID]
			if err := v.Scan(_spec.Id.Value); err != nil {
				return nil, err
			}
			_node.Id = v.V
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *LegalHoldCreate) createSpec() (*LegalHold, *sqlgraph.CreateSpec) {
	var (
		_node = &LegalHold{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(legalhold.Table, sqlgraph.NewFieldSpec(legalhold.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(legalhold.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Desc(); ok {
		_spec.SetField(legalhold.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := _c.mutation.DateLifted(); ok {
		_spec.SetField(legalhold.FieldDateLifted, field.TypeTime, value)
		_node.DateLifted = &value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(legalhold.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.TenantIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   legalhold.TenantTable,
			Columns: []string{legalhold.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tenant.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LegalHoldCreateBulk is the builder for creating many LegalHold entities in bulk.
type LegalHoldCreateBulk struct {
	config
	err      error
	builders []*LegalHoldCreate
}

// Save creates the LegalHold entities in the database.
func (_c *LegalHoldCreateBulk) Save(ctx context.Context) ([]*LegalHold, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LegalHold, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LegalHoldMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LegalHoldCreateBulk) SaveX(ctx context.Context) []*LegalHold {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LegalHoldCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LegalHoldCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
