// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/rove/internal/ent/placement"
	"github.com/lesomnus/rove/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// PlacementUpdate is the builder for updating Placement entities.
type PlacementUpdate struct {
	config
	hooks     []Hook
	mutation  *PlacementMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PlacementUpdate builder.
func (_u *PlacementUpdate) Where(ps ...predicate.Placement) *PlacementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMode sets the "mode" field.
func (_u *PlacementUpdate) SetMode(v string) *PlacementUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *PlacementUpdate) SetNillableMode(v *string) *PlacementUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetSlot sets the "slot" field.
func (_u *PlacementUpdate) SetSlot(v string) *PlacementUpdate {
	_u.mutation.SetSlot(v)
	return _u
}

// SetNillableSlot sets the "slot" field if the given value is not nil.
func (_u *PlacementUpdate) SetNillableSlot(v *string) *PlacementUpdate {
	if v != nil {
		_u.SetSlot(*v)
	}
	return _u
}

// SetUFrom sets the "u_from" field.
func (_u *PlacementUpdate) SetUFrom(v int32) *PlacementUpdate {
	_u.mutation.ResetUFrom()
	_u.mutation.SetUFrom(v)
	return _u
}

// SetNillableUFrom sets the "u_from" field if the given value is not nil.
func (_u *PlacementUpdate) SetNillableUFrom(v *int32) *PlacementUpdate {
	if v != nil {
		_u.SetUFrom(*v)
	}
	return _u
}

// AddUFrom adds value to the "u_from" field.
func (_u *PlacementUpdate) AddUFrom(v int32) *PlacementUpdate {
	_u.mutation.AddUFrom(v)
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *PlacementUpdate) SetDateUpdated(v time.Time) *PlacementUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *PlacementUpdate) SetNillableDateUpdated(v *time.Time) *PlacementUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetUTo sets the "u_to" field.
func (_u *PlacementUpdate) SetUTo(v int32) *PlacementUpdate {
	_u.mutation.ResetUTo()
	_u.mutation.SetUTo(v)
	return _u
}

// SetNillableUTo sets the "u_to" field if the given value is not nil.
func (_u *PlacementUpdate) SetNillableUTo(v *int32) *PlacementUpdate {
	if v != nil {
		_u.SetUTo(*v)
	}
	return _u
}

// AddUTo adds value to the "u_to" field.
func (_u *PlacementUpdate) AddUTo(v int32) *PlacementUpdate {
	_u.mutation.AddUTo(v)
	return _u
}

// SetValidFrom sets the "valid_from" field.
func (_u *PlacementUpdate) SetValidFrom(v time.Time) *PlacementUpdate {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *PlacementUpdate) SetNillableValidFrom(v *time.Time) *PlacementUpdate {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// ClearValidFrom clears the value of the "valid_from" field.
func (_u *PlacementUpdate) ClearValidFrom() *PlacementUpdate {
	_u.mutation.ClearValidFrom()
	return _u
}

// SetValidTo sets the "valid_to" field.
func (_u *PlacementUpdate) SetValidTo(v time.Time) *PlacementUpdate {
	_u.mutation.SetValidTo(v)
	return _u
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_u *PlacementUpdate) SetNillableValidTo(v *time.Time) *PlacementUpdate {
	if v != nil {
		_u.SetValidTo(*v)
	}
	return _u
}

// ClearValidTo clears the value of the "valid_to" field.
func (_u *PlacementUpdate) ClearValidTo() *PlacementUpdate {
	_u.mutation.ClearValidTo()
	return _u
}

// SetEventId sets the "event_id" field.
func (_u *PlacementUpdate) SetEventId(v uuid.UUID) *PlacementUpdate {
	_u.mutation.SetEventId(v)
	return _u
}

// SetNillableEventId sets the "event_id" field if the given value is not nil.
func (_u *PlacementUpdate) SetNillableEventId(v *uuid.UUID) *PlacementUpdate {
	if v != nil {
		_u.SetEventId(*v)
	}
	return _u
}

// SetSupersededAt sets the "superseded_at" field.
func (_u *PlacementUpdate) SetSupersededAt(v time.Time) *PlacementUpdate {
	_u.mutation.SetSupersededAt(v)
	return _u
}

// SetNillableSupersededAt sets the "superseded_at" field if the given value is not nil.
func (_u *PlacementUpdate) SetNillableSupersededAt(v *time.Time) *PlacementUpdate {
	if v != nil {
		_u.SetSupersededAt(*v)
	}
	return _u
}

// ClearSupersededAt clears the value of the "superseded_at" field.
func (_u *PlacementUpdate) ClearSupersededAt() *PlacementUpdate {
	_u.mutation.ClearSupersededAt()
	return _u
}

// SetSupersededBy sets the "superseded_by" field.
func (_u *PlacementUpdate) SetSupersededBy(v uuid.UUID) *PlacementUpdate {
	_u.mutation.SetSupersededBy(v)
	return _u
}

// SetNillableSupersededBy sets the "superseded_by" field if the given value is not nil.
func (_u *PlacementUpdate) SetNillableSupersededBy(v *uuid.UUID) *PlacementUpdate {
	if v != nil {
		_u.SetSupersededBy(*v)
	}
	return _u
}

// ClearSupersededBy clears the value of the "superseded_by" field.
func (_u *PlacementUpdate) ClearSupersededBy() *PlacementUpdate {
	_u.mutation.ClearSupersededBy()
	return _u
}

// Mutation returns the PlacementMutation object of the builder.
func (_u *PlacementUpdate) Mutation() *PlacementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlacementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlacementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlacementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlacementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlacementUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Placement.tenant"`)
	}
	if _u.mutation.ChildCleared() && len(_u.mutation.ChildIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Placement.child"`)
	}
	if _u.mutation.ParentCleared() && len(_u.mutation.ParentIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Placement.parent"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PlacementUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PlacementUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PlacementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(placement.Table, placement.Columns, sqlgraph.NewFieldSpec(placement.FieldId, field.TypeUuid))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(placement.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slot(); ok {
		_spec.SetField(placement.FieldSlot, field.TypeString, value)
	}
	if value, ok := _u.mutation.UFrom(); ok {
		_spec.SetField(placement.FieldUFrom, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedUFrom(); ok {
		_spec.AddField(placement.FieldUFrom, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(placement.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(placement.FieldDateCreated, field.TypeTime)
	}
	if value, ok := _u.mutation.UTo(); ok {
		_spec.SetField(placement.FieldUTo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedUTo(); ok {
		_spec.AddField(placement.FieldUTo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(placement.FieldValidFrom, field.TypeTime, value)
	}
	if _u.mutation.ValidFromCleared() {
		_spec.ClearField(placement.FieldValidFrom, field.TypeTime)
	}
	if value, ok := _u.mutation.ValidTo(); ok {
		_spec.SetField(placement.FieldValidTo, field.TypeTime, value)
	}
	if _u.mutation.ValidToCleared() {
		_spec.ClearField(placement.FieldValidTo, field.TypeTime)
	}
	if value, ok := _u.mutation.EventId(); ok {
		_spec.SetField(placement.FieldEventId, field.TypeUuid, value)
	}
	if value, ok := _u.mutation.SupersededAt(); ok {
		_spec.SetField(placement.FieldSupersededAt, field.TypeTime, value)
	}
	if _u.mutation.SupersededAtCleared() {
		_spec.ClearField(placement.FieldSupersededAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SupersededBy(); ok {
		_spec.SetField(placement.FieldSupersededBy, field.TypeUuid, value)
	}
	if _u.mutation.SupersededByCleared() {
		_spec.ClearField(placement.FieldSupersededBy, field.TypeUuid)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{placement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlacementUpdateOne is the builder for updating a single Placement entity.
type PlacementUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PlacementMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetMode sets the "mode" field.
func (_u *PlacementUpdateOne) SetMode(v string) *PlacementUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *PlacementUpdateOne) SetNillableMode(v *string) *PlacementUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetSlot sets the "slot" field.
func (_u *PlacementUpdateOne) SetSlot(v string) *PlacementUpdateOne {
	_u.mutation.SetSlot(v)
	return _u
}

// SetNillableSlot sets the "slot" field if the given value is not nil.
func (_u *PlacementUpdateOne) SetNillableSlot(v *string) *PlacementUpdateOne {
	if v != nil {
		_u.SetSlot(*v)
	}
	return _u
}

// SetUFrom sets the "u_from" field.
func (_u *PlacementUpdateOne) SetUFrom(v int32) *PlacementUpdateOne {
	_u.mutation.ResetUFrom()
	_u.mutation.SetUFrom(v)
	return _u
}

// SetNillableUFrom sets the "u_from" field if the given value is not nil.
func (_u *PlacementUpdateOne) SetNillableUFrom(v *int32) *PlacementUpdateOne {
	if v != nil {
		_u.SetUFrom(*v)
	}
	return _u
}

// AddUFrom adds value to the "u_from" field.
func (_u *PlacementUpdateOne) AddUFrom(v int32) *PlacementUpdateOne {
	_u.mutation.AddUFrom(v)
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *PlacementUpdateOne) SetDateUpdated(v time.Time) *PlacementUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *PlacementUpdateOne) SetNillableDateUpdated(v *time.Time) *PlacementUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetUTo sets the "u_to" field.
func (_u *PlacementUpdateOne) SetUTo(v int32) *PlacementUpdateOne {
	_u.mutation.ResetUTo()
	_u.mutation.SetUTo(v)
	return _u
}

// SetNillableUTo sets the "u_to" field if the given value is not nil.
func (_u *PlacementUpdateOne) SetNillableUTo(v *int32) *PlacementUpdateOne {
	if v != nil {
		_u.SetUTo(*v)
	}
	return _u
}

// AddUTo adds value to the "u_to" field.
func (_u *PlacementUpdateOne) AddUTo(v int32) *PlacementUpdateOne {
	_u.mutation.AddUTo(v)
	return _u
}

// SetValidFrom sets the "valid_from" field.
func (_u *PlacementUpdateOne) SetValidFrom(v time.Time) *PlacementUpdateOne {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *PlacementUpdateOne) SetNillableValidFrom(v *time.Time) *PlacementUpdateOne {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// ClearValidFrom clears the value of the "valid_from" field.
func (_u *PlacementUpdateOne) ClearValidFrom() *PlacementUpdateOne {
	_u.mutation.ClearValidFrom()
	return _u
}

// SetValidTo sets the "valid_to" field.
func (_u *PlacementUpdateOne) SetValidTo(v time.Time) *PlacementUpdateOne {
	_u.mutation.SetValidTo(v)
	return _u
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_u *PlacementUpdateOne) SetNillableValidTo(v *time.Time) *PlacementUpdateOne {
	if v != nil {
		_u.SetValidTo(*v)
	}
	return _u
}

// ClearValidTo clears the value of the "valid_to" field.
func (_u *PlacementUpdateOne) ClearValidTo() *PlacementUpdateOne {
	_u.mutation.ClearValidTo()
	return _u
}

// SetEventId sets the "event_id" field.
func (_u *PlacementUpdateOne) SetEventId(v uuid.UUID) *PlacementUpdateOne {
	_u.mutation.SetEventId(v)
	return _u
}

// SetNillableEventId sets the "event_id" field if the given value is not nil.
func (_u *PlacementUpdateOne) SetNillableEventId(v *uuid.UUID) *PlacementUpdateOne {
	if v != nil {
		_u.SetEventId(*v)
	}
	return _u
}

// SetSupersededAt sets the "superseded_at" field.
func (_u *PlacementUpdateOne) SetSupersededAt(v time.Time) *PlacementUpdateOne {
	_u.mutation.SetSupersededAt(v)
	return _u
}

// SetNillableSupersededAt sets the "superseded_at" field if the given value is not nil.
func (_u *PlacementUpdateOne) SetNillableSupersededAt(v *time.Time) *PlacementUpdateOne {
	if v != nil {
		_u.SetSupersededAt(*v)
	}
	return _u
}

// ClearSupersededAt clears the value of the "superseded_at" field.
func (_u *PlacementUpdateOne) ClearSupersededAt() *PlacementUpdateOne {
	_u.mutation.ClearSupersededAt()
	return _u
}

// SetSupersededBy sets the "superseded_by" field.
func (_u *PlacementUpdateOne) SetSupersededBy(v uuid.UUID) *PlacementUpdateOne {
	_u.mutation.SetSupersededBy(v)
	return _u
}

// SetNillableSupersededBy sets the "superseded_by" field if the given value is not nil.
func (_u *PlacementUpdateOne) SetNillableSupersededBy(v *uuid.UUID) *PlacementUpdateOne {
	if v != nil {
		_u.SetSupersededBy(*v)
	}
	return _u
}

// ClearSupersededBy clears the value of the "superseded_by" field.
func (_u *PlacementUpdateOne) ClearSupersededBy() *PlacementUpdateOne {
	_u.mutation.ClearSupersededBy()
	return _u
}

// Mutation returns the PlacementMutation object of the builder.
func (_u *PlacementUpdateOne) Mutation() *PlacementMutation {
	return _u.mutation
}

// Where appends a list predicates to the PlacementUpdate builder.
func (_u *PlacementUpdateOne) Where(ps ...predicate.Placement) *PlacementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlacementUpdateOne) Select(field string, fields ...string) *PlacementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Placement entity.
func (_u *PlacementUpdateOne) Save(ctx context.Context) (*Placement, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlacementUpdateOne) SaveX(ctx context.Context) *Placement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlacementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlacementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlacementUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Placement.tenant"`)
	}
	if _u.mutation.ChildCleared() && len(_u.mutation.ChildIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Placement.child"`)
	}
	if _u.mutation.ParentCleared() && len(_u.mutation.ParentIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Placement.parent"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PlacementUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PlacementUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PlacementUpdateOne) sqlSave(ctx context.Context) (_node *Placement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(placement.Table, placement.Columns, sqlgraph.NewFieldSpec(placement.FieldId, field.TypeUuid))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Placement.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, placement.FieldId)
		for _, f := range fields {
			if !placement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != placement.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(placement.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slot(); ok {
		_spec.SetField(placement.FieldSlot, field.TypeString, value)
	}
	if value, ok := _u.mutation.UFrom(); ok {
		_spec.SetField(placement.FieldUFrom, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedUFrom(); ok {
		_spec.AddField(placement.FieldUFrom, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(placement.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(placement.FieldDateCreated, field.TypeTime)
	}
	if value, ok := _u.mutation.UTo(); ok {
		_spec.SetField(placement.FieldUTo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedUTo(); ok {
		_spec.AddField(placement.FieldUTo, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(placement.FieldValidFrom, field.TypeTime, value)
	}
	if _u.mutation.ValidFromCleared() {
		_spec.ClearField(placement.FieldValidFrom, field.TypeTime)
	}
	if value, ok := _u.mutation.ValidTo(); ok {
		_spec.SetField(placement.FieldValidTo, field.TypeTime, value)
	}
	if _u.mutation.ValidToCleared() {
		_spec.ClearField(placement.FieldValidTo, field.TypeTime)
	}
	if value, ok := _u.mutation.EventId(); ok {
		_spec.SetField(placement.FieldEventId, field.TypeUuid, value)
	}
	if value, ok := _u.mutation.SupersededAt(); ok {
		_spec.SetField(placement.FieldSupersededAt, field.TypeTime, value)
	}
	if _u.mutation.SupersededAtCleared() {
		_spec.ClearField(placement.FieldSupersededAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SupersededBy(); ok {
		_spec.SetField(placement.FieldSupersededBy, field.TypeUuid, value)
	}
	if _u.mutation.SupersededByCleared() {
		_spec.ClearField(placement.FieldSupersededBy, field.TypeUuid)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Placement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{placement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
