// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/rove/internal/ent/predicate"
	"github.com/lesomnus/rove/internal/ent/reservationitem"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// ReservationItemUpdate is the builder for updating ReservationItem entities.
type ReservationItemUpdate struct {
	config
	hooks     []Hook
	mutation  *ReservationItemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ReservationItemUpdate builder.
func (_u *ReservationItemUpdate) Where(ps ...predicate.ReservationItem) *ReservationItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUnits sets the "units" field.
func (_u *ReservationItemUpdate) SetUnits(v uint32) *ReservationItemUpdate {
	_u.mutation.ResetUnits()
	_u.mutation.SetUnits(v)
	return _u
}

// SetNillableUnits sets the "units" field if the given value is not nil.
func (_u *ReservationItemUpdate) SetNillableUnits(v *uint32) *ReservationItemUpdate {
	if v != nil {
		_u.SetUnits(*v)
	}
	return _u
}

// AddUnits adds value to the "units" field.
func (_u *ReservationItemUpdate) AddUnits(v int32) *ReservationItemUpdate {
	_u.mutation.AddUnits(v)
	return _u
}

// SetAssignedId sets the "assigned_id" field.
func (_u *ReservationItemUpdate) SetAssignedId(v uuid.UUID) *ReservationItemUpdate {
	_u.mutation.SetAssignedId(v)
	return _u
}

// SetNillableAssignedId sets the "assigned_id" field if the given value is not nil.
func (_u *ReservationItemUpdate) SetNillableAssignedId(v *uuid.UUID) *ReservationItemUpdate {
	if v != nil {
		_u.SetAssignedId(*v)
	}
	return _u
}

// ClearAssignedId clears the value of the "assigned_id" field.
func (_u *ReservationItemUpdate) ClearAssignedId() *ReservationItemUpdate {
	_u.mutation.ClearAssignedId()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *ReservationItemUpdate) SetDateUpdated(v time.Time) *ReservationItemUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *ReservationItemUpdate) SetNillableDateUpdated(v *time.Time) *ReservationItemUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the ReservationItemMutation object of the builder.
func (_u *ReservationItemUpdate) Mutation() *ReservationItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReservationItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReservationItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReservationItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReservationItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReservationItemUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReservationItem.tenant"`)
	}
	if _u.mutation.ReservationCleared() && len(_u.mutation.ReservationIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReservationItem.reservation"`)
	}
	if _u.mutation.ResourceCleared() && len(_u.mutation.ResourceIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReservationItem.resource"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ReservationItemUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ReservationItemUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ReservationItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reservationitem.Table, reservationitem.Columns, sqlgraph.NewFieldSpec(reservationitem.FieldId, field.TypeUuid))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Units(); ok {
		_spec.SetField(reservationitem.FieldUnits, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUnits(); ok {
		_spec.AddField(reservationitem.FieldUnits, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AssignedId(); ok {
		_spec.SetField(reservationitem.FieldAssignedId, field.TypeUuid, value)
	}
	if _u.mutation.AssignedIdCleared() {
		_spec.ClearField(reservationitem.FieldAssignedId, field.TypeUuid)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(reservationitem.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(reservationitem.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reservationitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReservationItemUpdateOne is the builder for updating a single ReservationItem entity.
type ReservationItemUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ReservationItemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUnits sets the "units" field.
func (_u *ReservationItemUpdateOne) SetUnits(v uint32) *ReservationItemUpdateOne {
	_u.mutation.ResetUnits()
	_u.mutation.SetUnits(v)
	return _u
}

// SetNillableUnits sets the "units" field if the given value is not nil.
func (_u *ReservationItemUpdateOne) SetNillableUnits(v *uint32) *ReservationItemUpdateOne {
	if v != nil {
		_u.SetUnits(*v)
	}
	return _u
}

// AddUnits adds value to the "units" field.
func (_u *ReservationItemUpdateOne) AddUnits(v int32) *ReservationItemUpdateOne {
	_u.mutation.AddUnits(v)
	return _u
}

// SetAssignedId sets the "assigned_id" field.
func (_u *ReservationItemUpdateOne) SetAssignedId(v uuid.UUID) *ReservationItemUpdateOne {
	_u.mutation.SetAssignedId(v)
	return _u
}

// SetNillableAssignedId sets the "assigned_id" field if the given value is not nil.
func (_u *ReservationItemUpdateOne) SetNillableAssignedId(v *uuid.UUID) *ReservationItemUpdateOne {
	if v != nil {
		_u.SetAssignedId(*v)
	}
	return _u
}

// ClearAssignedId clears the value of the "assigned_id" field.
func (_u *ReservationItemUpdateOne) ClearAssignedId() *ReservationItemUpdateOne {
	_u.mutation.ClearAssignedId()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *ReservationItemUpdateOne) SetDateUpdated(v time.Time) *ReservationItemUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *ReservationItemUpdateOne) SetNillableDateUpdated(v *time.Time) *ReservationItemUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the ReservationItemMutation object of the builder.
func (_u *ReservationItemUpdateOne) Mutation() *ReservationItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReservationItemUpdate builder.
func (_u *ReservationItemUpdateOne) Where(ps ...predicate.ReservationItem) *ReservationItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReservationItemUpdateOne) Select(field string, fields ...string) *ReservationItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReservationItem entity.
func (_u *ReservationItemUpdateOne) Save(ctx context.Context) (*ReservationItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReservationItemUpdateOne) SaveX(ctx context.Context) *ReservationItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReservationItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReservationItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReservationItemUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReservationItem.tenant"`)
	}
	if _u.mutation.ReservationCleared() && len(_u.mutation.ReservationIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReservationItem.reservation"`)
	}
	if _u.mutation.ResourceCleared() && len(_u.mutation.ResourceIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReservationItem.resource"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ReservationItemUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ReservationItemUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ReservationItemUpdateOne) sqlSave(ctx context.Context) (_node *ReservationItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reservationitem.Table, reservationitem.Columns, sqlgraph.NewFieldSpec(reservationitem.FieldId, field.TypeUuid))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReservationItem.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reservationitem.FieldId)
		for _, f := range fields {
			if !reservationitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reservationitem.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Units(); ok {
		_spec.SetField(reservationitem.FieldUnits, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUnits(); ok {
		_spec.AddField(reservationitem.FieldUnits, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AssignedId(); ok {
		_spec.SetField(reservationitem.FieldAssignedId, field.TypeUuid, value)
	}
	if _u.mutation.AssignedIdCleared() {
		_spec.ClearField(reservationitem.FieldAssignedId, field.TypeUuid)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(reservationitem.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(reservationitem.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ReservationItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reservationitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
