// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: rove/payday/tenant.proto

package ent

import (
	rove "github.com/lesomnus/rove"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Tenant) Proto() *rove.Tenant {
	x := &rove.Tenant{}
	x.SetId(e.Id[:])
	x.SetAlias(e.Alias)
	x.SetName(e.Name)
	x.SetDesc(e.Desc)
	x.SetLabels(e.Labels)
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
