// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/lesomnus/rove/internal/ent/predicate"
	"github.com/lesomnus/rove/internal/ent/usagesnapshot"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// UsageSnapshotUpdate is the builder for updating UsageSnapshot entities.
type UsageSnapshotUpdate struct {
	config
	hooks     []Hook
	mutation  *UsageSnapshotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UsageSnapshotUpdate builder.
func (_u *UsageSnapshotUpdate) Where(ps ...predicate.UsageSnapshot) *UsageSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDay sets the "day" field.
func (_u *UsageSnapshotUpdate) SetDay(v string) *UsageSnapshotUpdate {
	_u.mutation.SetDay(v)
	return _u
}

// SetNillableDay sets the "day" field if the given value is not nil.
func (_u *UsageSnapshotUpdate) SetNillableDay(v *string) *UsageSnapshotUpdate {
	if v != nil {
		_u.SetDay(*v)
	}
	return _u
}

// SetMetrics sets the "metrics" field.
func (_u *UsageSnapshotUpdate) SetMetrics(v map[string]string) *UsageSnapshotUpdate {
	_u.mutation.SetMetrics(v)
	return _u
}

// ClearMetrics clears the value of the "metrics" field.
func (_u *UsageSnapshotUpdate) ClearMetrics() *UsageSnapshotUpdate {
	_u.mutation.ClearMetrics()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *UsageSnapshotUpdate) SetDateUpdated(v time.Time) *UsageSnapshotUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *UsageSnapshotUpdate) SetNillableDateUpdated(v *time.Time) *UsageSnapshotUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the UsageSnapshotMutation object of the builder.
func (_u *UsageSnapshotUpdate) Mutation() *UsageSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageSnapshotUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageSnapshot.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UsageSnapshotUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UsageSnapshotUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UsageSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagesnapshot.Table, usagesnapshot.Columns, sqlgraph.NewFieldSpec(usagesnapshot.FieldId, field.TypeUuid))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Day(); ok {
		_spec.SetField(usagesnapshot.FieldDay, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metrics(); ok {
		_spec.SetField(usagesnapshot.FieldMetrics, field.TypeJson, value)
	}
	if _u.mutation.MetricsCleared() {
		_spec.ClearField(usagesnapshot.FieldMetrics, field.TypeJson)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(usagesnapshot.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(usagesnapshot.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagesnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageSnapshotUpdateOne is the builder for updating a single UsageSnapshot entity.
type UsageSnapshotUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UsageSnapshotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDay sets the "day" field.
func (_u *UsageSnapshotUpdateOne) SetDay(v string) *UsageSnapshotUpdateOne {
	_u.mutation.SetDay(v)
	return _u
}

// SetNillableDay sets the "day" field if the given value is not nil.
func (_u *UsageSnapshotUpdateOne) SetNillableDay(v *string) *UsageSnapshotUpdateOne {
	if v != nil {
		_u.SetDay(*v)
	}
	return _u
}

// SetMetrics sets the "metrics" field.
func (_u *UsageSnapshotUpdateOne) SetMetrics(v map[string]string) *UsageSnapshotUpdateOne {
	_u.mutation.SetMetrics(v)
	return _u
}

// ClearMetrics clears the value of the "metrics" field.
func (_u *UsageSnapshotUpdateOne) ClearMetrics() *UsageSnapshotUpdateOne {
	_u.mutation.ClearMetrics()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *UsageSnapshotUpdateOne) SetDateUpdated(v time.Time) *UsageSnapshotUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *UsageSnapshotUpdateOne) SetNillableDateUpdated(v *time.Time) *UsageSnapshotUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the UsageSnapshotMutation object of the builder.
func (_u *UsageSnapshotUpdateOne) Mutation() *UsageSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the UsageSnapshotUpdate builder.
func (_u *UsageSnapshotUpdateOne) Where(ps ...predicate.UsageSnapshot) *UsageSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageSnapshotUpdateOne) Select(field string, fields ...string) *UsageSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageSnapshot entity.
func (_u *UsageSnapshotUpdateOne) Save(ctx context.Context) (*UsageSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageSnapshotUpdateOne) SaveX(ctx context.Context) *UsageSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageSnapshotUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageSnapshot.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UsageSnapshotUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UsageSnapshotUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UsageSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *UsageSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagesnapshot.Table, usagesnapshot.Columns, sqlgraph.NewFieldSpec(usagesnapshot.FieldId, field.TypeUuid))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageSnapshot.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagesnapshot.FieldId)
		for _, f := range fields {
			if !usagesnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagesnapshot.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Day(); ok {
		_spec.SetField(usagesnapshot.FieldDay, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metrics(); ok {
		_spec.SetField(usagesnapshot.FieldMetrics, field.TypeJson, value)
	}
	if _u.mutation.MetricsCleared() {
		_spec.ClearField(usagesnapshot.FieldMetrics, field.TypeJson)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(usagesnapshot.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(usagesnapshot.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UsageSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagesnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
