// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/rove/internal/ent/asset"
	"github.com/lesomnus/rove/internal/ent/party"
	"github.com/lesomnus/rove/internal/ent/tenant"
	"github.com/lesomnus/rove/internal/ent/workorder"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// WorkOrderCreate is the builder for creating a WorkOrder entity.
type WorkOrderCreate struct {
	config
	mutation *WorkOrderMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *WorkOrderCreate) SetName(v string) *WorkOrderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDesc sets the "desc" field.
func (_c *WorkOrderCreate) SetDesc(v string) *WorkOrderCreate {
	_c.mutation.SetDesc(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *WorkOrderCreate) SetKind(v string) *WorkOrderCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *WorkOrderCreate) SetStatus(v string) *WorkOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetBeginsAt sets the "begins_at" field.
func (_c *WorkOrderCreate) SetBeginsAt(v time.Time) *WorkOrderCreate {
	_c.mutation.SetBeginsAt(v)
	return _c
}

// SetNillableBeginsAt sets the "begins_at" field if the given value is not nil.
func (_c *WorkOrderCreate) SetNillableBeginsAt(v *time.Time) *WorkOrderCreate {
	if v != nil {
		_c.SetBeginsAt(*v)
	}
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *WorkOrderCreate) SetEndsAt(v time.Time) *WorkOrderCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_c *WorkOrderCreate) SetNillableEndsAt(v *time.Time) *WorkOrderCreate {
	if v != nil {
		_c.SetEndsAt(*v)
	}
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *WorkOrderCreate) SetDateUpdated(v time.Time) *WorkOrderCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateErased sets the "date_erased" field.
func (_c *WorkOrderCreate) SetDateErased(v time.Time) *WorkOrderCreate {
	_c.mutation.SetDateErased(v)
	return _c
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_c *WorkOrderCreate) SetNillableDateErased(v *time.Time) *WorkOrderCreate {
	if v != nil {
		_c.SetDateErased(*v)
	}
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *WorkOrderCreate) SetDateCreated(v time.Time) *WorkOrderCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *WorkOrderCreate) SetNillableDateCreated(v *time.Time) *WorkOrderCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *WorkOrderCreate) SetCost(v int64) *WorkOrderCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *WorkOrderCreate) SetCurrency(v string) *WorkOrderCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *WorkOrderCreate) SetCompletedAt(v time.Time) *WorkOrderCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *WorkOrderCreate) SetNillableCompletedAt(v *time.Time) *WorkOrderCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetBlocking sets the "blocking" field.
func (_c *WorkOrderCreate) SetBlocking(v bool) *WorkOrderCreate {
	_c.mutation.SetBlocking(v)
	return _c
}

// SetEveryDays sets the "every_days" field.
func (_c *WorkOrderCreate) SetEveryDays(v int32) *WorkOrderCreate {
	_c.mutation.SetEveryDays(v)
	return _c
}

// SetTenantId sets the "tenant_id" field.
func (_c *WorkOrderCreate) SetTenantId(v uuid.UUID) *WorkOrderCreate {
	_c.mutation.SetTenantId(v)
	return _c
}

// SetAssetId sets the "asset_id" field.
func (_c *WorkOrderCreate) SetAssetId(v uuid.UUID) *WorkOrderCreate {
	_c.mutation.SetAssetId(v)
	return _c
}

// SetVendorId sets the "vendor_id" field.
func (_c *WorkOrderCreate) SetVendorId(v uuid.UUID) *WorkOrderCreate {
	_c.mutation.SetVendorId(v)
	return _c
}

// SetNillableVendorId sets the "vendor_id" field if the given value is not nil.
func (_c *WorkOrderCreate) SetNillableVendorId(v *uuid.UUID) *WorkOrderCreate {
	if v != nil {
		_c.SetVendorId(*v)
	}
	return _c
}

// SetId sets the "id" field.
func (_c *WorkOrderCreate) SetId(v uuid.UUID) *WorkOrderCreate {
	_c.mutation.SetId(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *WorkOrderCreate) SetTenant(v *Tenant) *WorkOrderCreate {
	return _c.SetTenantId(v.Id)
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_c *WorkOrderCreate) SetAsset(v *Asset) *WorkOrderCreate {
	return _c.SetAssetId(v.Id)
}

// SetVendor sets the "vendor" edge to the Party entity.
func (_c *WorkOrderCreate) SetVendor(v *Party) *WorkOrderCreate {
	return _c.SetVendorId(v.Id)
}

// Mutation returns the WorkOrderMutation object of the builder.
func (_c *WorkOrderCreate) Mutation() *WorkOrderMutation {
	return _c.mutation
}

// Save creates the WorkOrder in the database.
func (_c *WorkOrderCreate) Save(ctx context.Context) (*WorkOrder, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkOrderCreate) SaveX(ctx context.Context) *WorkOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkOrderCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "WorkOrder.name"`)}
	}
	if _, ok := _c.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "WorkOrder.desc"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "WorkOrder.kind"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WorkOrder.status"`)}
	}
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "WorkOrder.date_updated"`)}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "WorkOrder.cost"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "WorkOrder.currency"`)}
	}
	if _, ok := _c.mutation.Blocking(); !ok {
		return &ValidationError{Name: "blocking", err: errors.New(`ent: missing required field "WorkOrder.blocking"`)}
	}
	if _, ok := _c.mutation.EveryDays(); !ok {
		return &ValidationError{Name: "every_days", err: errors.New(`ent: missing required field "WorkOrder.every_days"`)}
	}
	if _, ok := _c.mutation.TenantId(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "WorkOrder.tenant_id"`)}
	}
	if _, ok := _c.mutation.AssetId(); !ok {
		return &ValidationError{Name: "asset_id", err: errors.New(`ent: missing required field "WorkOrder.asset_id"`)}
	}
	if len(_c.mutation.TenantIds()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "WorkOrder.tenant"`)}
	}
	if len(_c.mutation.AssetIds()) == 0 {
		return &ValidationError{Name: "asset", err: errors.New(`ent: missing required edge "WorkOrder.asset"`)}
	}
	return nil
}

func (_c *WorkOrderCreate) sqlSave(ctx context.Context) (*WorkOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else {
			var v sql.Null[uuid.UUID]
			if err := v.Scan(_spec.Id.Value); err != nil {
				return nil, err
			}
			_node.Id = v.V
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkOrderCreate) createSpec() (*WorkOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workorder.Table, sqlgraph.NewFieldSpec(workorder.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(workorder.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Desc(); ok {
		_spec.SetField(workorder.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(workorder.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(workorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.BeginsAt(); ok {
		_spec.SetField(workorder.FieldBeginsAt, field.TypeTime, value)
		_node.BeginsAt = &value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(workorder.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = &value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(workorder.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateErased(); ok {
		_spec.SetField(workorder.FieldDateErased, field.TypeTime, value)
		_node.DateErased = &value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(workorder.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(workorder.FieldCost, field.TypeInt64, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(workorder.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(workorder.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.Blocking(); ok {
		_spec.SetField(workorder.FieldBlocking, field.TypeBool, value)
		_node.Blocking = value
	}
	if value, ok := _c.mutation.EveryDays(); ok {
		_spec.SetField(workorder.FieldEveryDays, field.TypeInt32, value)
		_node.EveryDays = value
	}
	if nodes := _c.mutation.TenantIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workorder.TenantTable,
			Columns: []string{workorder.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tenant.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssetIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workorder.AssetTable,
			Columns: []string{workorder.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(asset.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssetId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VendorIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workorder.VendorTable,
			Columns: []string{workorder.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(party.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VendorId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WorkOrderCreateBulk is the builder for creating many WorkOrder entities in bulk.
type WorkOrderCreateBulk struct {
	config
	err      error
	builders []*WorkOrderCreate
}

// Save creates the WorkOrder entities in the database.
func (_c *WorkOrderCreateBulk) Save(ctx context.Context) ([]*WorkOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkOrderCreateBulk) SaveX(ctx context.Context) []*WorkOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
