// Code generated by ent, DO NOT EDIT.

package bookable

import (
	"time"
	"uuid"

	"github.com/lesomnus/rove/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldId, id))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldTimezone, v))
}

// BufferBefore applies equality check predicate on the "buffer_before" field. It's identical to BufferBeforeEQ.
func BufferBefore(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldBufferBefore, v))
}

// BufferAfter applies equality check predicate on the "buffer_after" field. It's identical to BufferAfterEQ.
func BufferAfter(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldBufferAfter, v))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldDateUpdated, v))
}

// DateErased applies equality check predicate on the "date_erased" field. It's identical to DateErasedEQ.
func DateErased(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldDateErased, v))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldDateCreated, v))
}

// Approval applies equality check predicate on the "approval" field. It's identical to ApprovalEQ.
func Approval(v bool) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldApproval, v))
}

// MinMinutes applies equality check predicate on the "min_minutes" field. It's identical to MinMinutesEQ.
func MinMinutes(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldMinMinutes, v))
}

// MaxMinutes applies equality check predicate on the "max_minutes" field. It's identical to MaxMinutesEQ.
func MaxMinutes(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldMaxMinutes, v))
}

// HorizonDays applies equality check predicate on the "horizon_days" field. It's identical to HorizonDaysEQ.
func HorizonDays(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldHorizonDays, v))
}

// Units applies equality check predicate on the "units" field. It's identical to UnitsEQ.
func Units(v uint32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldUnits, v))
}

// ExclusiveGroup applies equality check predicate on the "exclusive_group" field. It's identical to ExclusiveGroupEQ.
func ExclusiveGroup(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldExclusiveGroup, v))
}

// ScheduleVersion applies equality check predicate on the "schedule_version" field. It's identical to ScheduleVersionEQ.
func ScheduleVersion(v uint64) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldScheduleVersion, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldEnabled, v))
}

// TenantId applies equality check predicate on the "tenant_id" field. It's identical to TenantIdEQ.
func TenantId(v uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldTenantId, v))
}

// AssetId applies equality check predicate on the "asset_id" field. It's identical to AssetIdEQ.
func AssetId(v uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldAssetId, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldContainsFold(FieldTimezone, v))
}

// HoursIsNil applies the IsNil predicate on the "hours" field.
func HoursIsNil() predicate.Bookable {
	return predicate.Bookable(sql.FieldIsNull(FieldHours))
}

// HoursNotNil applies the NotNil predicate on the "hours" field.
func HoursNotNil() predicate.Bookable {
	return predicate.Bookable(sql.FieldNotNull(FieldHours))
}

// BufferBeforeEQ applies the EQ predicate on the "buffer_before" field.
func BufferBeforeEQ(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldBufferBefore, v))
}

// BufferBeforeNEQ applies the NEQ predicate on the "buffer_before" field.
func BufferBeforeNEQ(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldBufferBefore, v))
}

// BufferBeforeIn applies the In predicate on the "buffer_before" field.
func BufferBeforeIn(vs ...int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldBufferBefore, vs...))
}

// BufferBeforeNotIn applies the NotIn predicate on the "buffer_before" field.
func BufferBeforeNotIn(vs ...int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldBufferBefore, vs...))
}

// BufferBeforeGT applies the GT predicate on the "buffer_before" field.
func BufferBeforeGT(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldBufferBefore, v))
}

// BufferBeforeGTE applies the GTE predicate on the "buffer_before" field.
func BufferBeforeGTE(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldBufferBefore, v))
}

// BufferBeforeLT applies the LT predicate on the "buffer_before" field.
func BufferBeforeLT(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldBufferBefore, v))
}

// BufferBeforeLTE applies the LTE predicate on the "buffer_before" field.
func BufferBeforeLTE(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldBufferBefore, v))
}

// BufferAfterEQ applies the EQ predicate on the "buffer_after" field.
func BufferAfterEQ(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldBufferAfter, v))
}

// BufferAfterNEQ applies the NEQ predicate on the "buffer_after" field.
func BufferAfterNEQ(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldBufferAfter, v))
}

// BufferAfterIn applies the In predicate on the "buffer_after" field.
func BufferAfterIn(vs ...int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldBufferAfter, vs...))
}

// BufferAfterNotIn applies the NotIn predicate on the "buffer_after" field.
func BufferAfterNotIn(vs ...int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldBufferAfter, vs...))
}

// BufferAfterGT applies the GT predicate on the "buffer_after" field.
func BufferAfterGT(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldBufferAfter, v))
}

// BufferAfterGTE applies the GTE predicate on the "buffer_after" field.
func BufferAfterGTE(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldBufferAfter, v))
}

// BufferAfterLT applies the LT predicate on the "buffer_after" field.
func BufferAfterLT(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldBufferAfter, v))
}

// BufferAfterLTE applies the LTE predicate on the "buffer_after" field.
func BufferAfterLTE(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldBufferAfter, v))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldDateUpdated, v))
}

// DateErasedEQ applies the EQ predicate on the "date_erased" field.
func DateErasedEQ(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldDateErased, v))
}

// DateErasedNEQ applies the NEQ predicate on the "date_erased" field.
func DateErasedNEQ(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldDateErased, v))
}

// DateErasedIn applies the In predicate on the "date_erased" field.
func DateErasedIn(vs ...time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldDateErased, vs...))
}

// DateErasedNotIn applies the NotIn predicate on the "date_erased" field.
func DateErasedNotIn(vs ...time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldDateErased, vs...))
}

// DateErasedGT applies the GT predicate on the "date_erased" field.
func DateErasedGT(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldDateErased, v))
}

// DateErasedGTE applies the GTE predicate on the "date_erased" field.
func DateErasedGTE(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldDateErased, v))
}

// DateErasedLT applies the LT predicate on the "date_erased" field.
func DateErasedLT(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldDateErased, v))
}

// DateErasedLTE applies the LTE predicate on the "date_erased" field.
func DateErasedLTE(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldDateErased, v))
}

// DateErasedIsNil applies the IsNil predicate on the "date_erased" field.
func DateErasedIsNil() predicate.Bookable {
	return predicate.Bookable(sql.FieldIsNull(FieldDateErased))
}

// DateErasedNotNil applies the NotNil predicate on the "date_erased" field.
func DateErasedNotNil() predicate.Bookable {
	return predicate.Bookable(sql.FieldNotNull(FieldDateErased))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldDateCreated, v))
}

// DateCreatedIsNil applies the IsNil predicate on the "date_created" field.
func DateCreatedIsNil() predicate.Bookable {
	return predicate.Bookable(sql.FieldIsNull(FieldDateCreated))
}

// DateCreatedNotNil applies the NotNil predicate on the "date_created" field.
func DateCreatedNotNil() predicate.Bookable {
	return predicate.Bookable(sql.FieldNotNull(FieldDateCreated))
}

// ApprovalEQ applies the EQ predicate on the "approval" field.
func ApprovalEQ(v bool) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldApproval, v))
}

// ApprovalNEQ applies the NEQ predicate on the "approval" field.
func ApprovalNEQ(v bool) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldApproval, v))
}

// MinMinutesEQ applies the EQ predicate on the "min_minutes" field.
func MinMinutesEQ(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldMinMinutes, v))
}

// MinMinutesNEQ applies the NEQ predicate on the "min_minutes" field.
func MinMinutesNEQ(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldMinMinutes, v))
}

// MinMinutesIn applies the In predicate on the "min_minutes" field.
func MinMinutesIn(vs ...int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldMinMinutes, vs...))
}

// MinMinutesNotIn applies the NotIn predicate on the "min_minutes" field.
func MinMinutesNotIn(vs ...int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldMinMinutes, vs...))
}

// MinMinutesGT applies the GT predicate on the "min_minutes" field.
func MinMinutesGT(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldMinMinutes, v))
}

// MinMinutesGTE applies the GTE predicate on the "min_minutes" field.
func MinMinutesGTE(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldMinMinutes, v))
}

// MinMinutesLT applies the LT predicate on the "min_minutes" field.
func MinMinutesLT(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldMinMinutes, v))
}

// MinMinutesLTE applies the LTE predicate on the "min_minutes" field.
func MinMinutesLTE(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldMinMinutes, v))
}

// MaxMinutesEQ applies the EQ predicate on the "max_minutes" field.
func MaxMinutesEQ(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldMaxMinutes, v))
}

// MaxMinutesNEQ applies the NEQ predicate on the "max_minutes" field.
func MaxMinutesNEQ(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldMaxMinutes, v))
}

// MaxMinutesIn applies the In predicate on the "max_minutes" field.
func MaxMinutesIn(vs ...int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldMaxMinutes, vs...))
}

// MaxMinutesNotIn applies the NotIn predicate on the "max_minutes" field.
func MaxMinutesNotIn(vs ...int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldMaxMinutes, vs...))
}

// MaxMinutesGT applies the GT predicate on the "max_minutes" field.
func MaxMinutesGT(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldMaxMinutes, v))
}

// MaxMinutesGTE applies the GTE predicate on the "max_minutes" field.
func MaxMinutesGTE(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldMaxMinutes, v))
}

// MaxMinutesLT applies the LT predicate on the "max_minutes" field.
func MaxMinutesLT(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldMaxMinutes, v))
}

// MaxMinutesLTE applies the LTE predicate on the "max_minutes" field.
func MaxMinutesLTE(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldMaxMinutes, v))
}

// HorizonDaysEQ applies the EQ predicate on the "horizon_days" field.
func HorizonDaysEQ(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldHorizonDays, v))
}

// HorizonDaysNEQ applies the NEQ predicate on the "horizon_days" field.
func HorizonDaysNEQ(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldHorizonDays, v))
}

// HorizonDaysIn applies the In predicate on the "horizon_days" field.
func HorizonDaysIn(vs ...int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldHorizonDays, vs...))
}

// HorizonDaysNotIn applies the NotIn predicate on the "horizon_days" field.
func HorizonDaysNotIn(vs ...int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldHorizonDays, vs...))
}

// HorizonDaysGT applies the GT predicate on the "horizon_days" field.
func HorizonDaysGT(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldHorizonDays, v))
}

// HorizonDaysGTE applies the GTE predicate on the "horizon_days" field.
func HorizonDaysGTE(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldHorizonDays, v))
}

// HorizonDaysLT applies the LT predicate on the "horizon_days" field.
func HorizonDaysLT(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldHorizonDays, v))
}

// HorizonDaysLTE applies the LTE predicate on the "horizon_days" field.
func HorizonDaysLTE(v int32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldHorizonDays, v))
}

// UnitsEQ applies the EQ predicate on the "units" field.
func UnitsEQ(v uint32) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldUnits, v))
}

// UnitsNEQ applies the NEQ predicate on the "units" field.
func UnitsNEQ(v uint32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldUnits, v))
}

// UnitsIn applies the In predicate on the "units" field.
func UnitsIn(vs ...uint32) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldUnits, vs...))
}

// UnitsNotIn applies the NotIn predicate on the "units" field.
func UnitsNotIn(vs ...uint32) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldUnits, vs...))
}

// UnitsGT applies the GT predicate on the "units" field.
func UnitsGT(v uint32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldUnits, v))
}

// UnitsGTE applies the GTE predicate on the "units" field.
func UnitsGTE(v uint32) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldUnits, v))
}

// UnitsLT applies the LT predicate on the "units" field.
func UnitsLT(v uint32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldUnits, v))
}

// UnitsLTE applies the LTE predicate on the "units" field.
func UnitsLTE(v uint32) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldUnits, v))
}

// ExclusiveGroupEQ applies the EQ predicate on the "exclusive_group" field.
func ExclusiveGroupEQ(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldExclusiveGroup, v))
}

// ExclusiveGroupNEQ applies the NEQ predicate on the "exclusive_group" field.
func ExclusiveGroupNEQ(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldExclusiveGroup, v))
}

// ExclusiveGroupIn applies the In predicate on the "exclusive_group" field.
func ExclusiveGroupIn(vs ...string) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldExclusiveGroup, vs...))
}

// ExclusiveGroupNotIn applies the NotIn predicate on the "exclusive_group" field.
func ExclusiveGroupNotIn(vs ...string) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldExclusiveGroup, vs...))
}

// ExclusiveGroupGT applies the GT predicate on the "exclusive_group" field.
func ExclusiveGroupGT(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldExclusiveGroup, v))
}

// ExclusiveGroupGTE applies the GTE predicate on the "exclusive_group" field.
func ExclusiveGroupGTE(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldExclusiveGroup, v))
}

// ExclusiveGroupLT applies the LT predicate on the "exclusive_group" field.
func ExclusiveGroupLT(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldExclusiveGroup, v))
}

// ExclusiveGroupLTE applies the LTE predicate on the "exclusive_group" field.
func ExclusiveGroupLTE(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldExclusiveGroup, v))
}

// ExclusiveGroupContains applies the Contains predicate on the "exclusive_group" field.
func ExclusiveGroupContains(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldContains(FieldExclusiveGroup, v))
}

// ExclusiveGroupHasPrefix applies the HasPrefix predicate on the "exclusive_group" field.
func ExclusiveGroupHasPrefix(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldHasPrefix(FieldExclusiveGroup, v))
}

// ExclusiveGroupHasSuffix applies the HasSuffix predicate on the "exclusive_group" field.
func ExclusiveGroupHasSuffix(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldHasSuffix(FieldExclusiveGroup, v))
}

// ExclusiveGroupEqualFold applies the EqualFold predicate on the "exclusive_group" field.
func ExclusiveGroupEqualFold(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldEqualFold(FieldExclusiveGroup, v))
}

// ExclusiveGroupContainsFold applies the ContainsFold predicate on the "exclusive_group" field.
func ExclusiveGroupContainsFold(v string) predicate.Bookable {
	return predicate.Bookable(sql.FieldContainsFold(FieldExclusiveGroup, v))
}

// ScheduleVersionEQ applies the EQ predicate on the "schedule_version" field.
func ScheduleVersionEQ(v uint64) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldScheduleVersion, v))
}

// ScheduleVersionNEQ applies the NEQ predicate on the "schedule_version" field.
func ScheduleVersionNEQ(v uint64) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldScheduleVersion, v))
}

// ScheduleVersionIn applies the In predicate on the "schedule_version" field.
func ScheduleVersionIn(vs ...uint64) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldScheduleVersion, vs...))
}

// ScheduleVersionNotIn applies the NotIn predicate on the "schedule_version" field.
func ScheduleVersionNotIn(vs ...uint64) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldScheduleVersion, vs...))
}

// ScheduleVersionGT applies the GT predicate on the "schedule_version" field.
func ScheduleVersionGT(v uint64) predicate.Bookable {
	return predicate.Bookable(sql.FieldGT(FieldScheduleVersion, v))
}

// ScheduleVersionGTE applies the GTE predicate on the "schedule_version" field.
func ScheduleVersionGTE(v uint64) predicate.Bookable {
	return predicate.Bookable(sql.FieldGTE(FieldScheduleVersion, v))
}

// ScheduleVersionLT applies the LT predicate on the "schedule_version" field.
func ScheduleVersionLT(v uint64) predicate.Bookable {
	return predicate.Bookable(sql.FieldLT(FieldScheduleVersion, v))
}

// ScheduleVersionLTE applies the LTE predicate on the "schedule_version" field.
func ScheduleVersionLTE(v uint64) predicate.Bookable {
	return predicate.Bookable(sql.FieldLTE(FieldScheduleVersion, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldEnabled, v))
}

// TenantIdEQ applies the EQ predicate on the "tenant_id" field.
func TenantIdEQ(v uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldTenantId, v))
}

// TenantIdNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIdNEQ(v uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldTenantId, v))
}

// TenantIdIn applies the In predicate on the "tenant_id" field.
func TenantIdIn(vs ...uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldTenantId, vs...))
}

// TenantIdNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIdNotIn(vs ...uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldTenantId, vs...))
}

// AssetIdEQ applies the EQ predicate on the "asset_id" field.
func AssetIdEQ(v uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldEQ(FieldAssetId, v))
}

// AssetIdNEQ applies the NEQ predicate on the "asset_id" field.
func AssetIdNEQ(v uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldNEQ(FieldAssetId, v))
}

// AssetIdIn applies the In predicate on the "asset_id" field.
func AssetIdIn(vs ...uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldIn(FieldAssetId, vs...))
}

// AssetIdNotIn applies the NotIn predicate on the "asset_id" field.
func AssetIdNotIn(vs ...uuid.UUID) predicate.Bookable {
	return predicate.Bookable(sql.FieldNotIn(FieldAssetId, vs...))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Bookable {
	return predicate.Bookable(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Bookable {
	return predicate.Bookable(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAsset applies the HasEdge predicate on the "asset" edge.
func HasAsset() predicate.Bookable {
	return predicate.Bookable(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, AssetTable, AssetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetWith applies the HasEdge predicate on the "asset" edge with a given conditions (other predicates).
func HasAssetWith(preds ...predicate.Asset) predicate.Bookable {
	return predicate.Bookable(func(s *sql.Selector) {
		step := newAssetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bookable) predicate.Bookable {
	return predicate.Bookable(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bookable) predicate.Bookable {
	return predicate.Bookable(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bookable) predicate.Bookable {
	return predicate.Bookable(sql.NotPredicates(p))
}
