// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: rove/custody.proto

package bare

import (
	context "context"
	errors "errors"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	rove "github.com/lesomnus/rove"
	ent "github.com/lesomnus/rove/internal/ent"
	asset "github.com/lesomnus/rove/internal/ent/asset"
	custody "github.com/lesomnus/rove/internal/ent/custody"
	custodyline "github.com/lesomnus/rove/internal/ent/custodyline"
	party "github.com/lesomnus/rove/internal/ent/party"
	predicate "github.com/lesomnus/rove/internal/ent/predicate"
	stock "github.com/lesomnus/rove/internal/ent/stock"
	ent1 "github.com/protobuf-orm/ent"
	sqlgraph "github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	entuuid "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entuuid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	uuid "uuid"
)

type CustodyServiceServer struct {
	Store

	rove.UnimplementedCustodyServiceServer
}

// NewCustodyServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewCustodyServiceServer(db *ent.Client, opts ...Option) rove.CustodyServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return CustodyServiceServer{Store: s.Store}
}

// CustodyNarrow answers with `p` and everything else that narrows a
// read of a Custody: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func CustodyNarrow(ctx context.Context, scope Scope, p predicate.Custody) (predicate.Custody, error) {
	ps := make([]predicate.Custody, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, custody.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.CustodyScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return custody.And(ps...), nil
	}
}

// narrow is [CustodyNarrow] with this server's own scope.
func (s CustodyServiceServer) narrow(ctx context.Context, p predicate.Custody) (predicate.Custody, error) {
	return CustodyNarrow(ctx, s.Scope, p)
}

func (s CustodyServiceServer) Add(ctx context.Context, req *rove.CustodyAddRequest) (*rove.Custody, error) {
	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *rove.Custody), 0, 2)
	q := st.Db.Custody.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "rove.Custody", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetId(v)
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantId(k)
		ds = append(ds, func(v *rove.Custody) {
			v.SetTenant(rove.Tenant_builder{Id: k[:]}.Build())
		})
	}
	q.SetDesc(req.GetDesc())
	if k, err := PartyGetKey(ctx, st.Db, req.GetParty()); err != nil {
		return nil, err
	} else {
		q.SetPartyId(k)
		ds = append(ds, func(v *rove.Custody) {
			v.SetParty(rove.Party_builder{Id: k[:]}.Build())
		})
	}
	q.SetKind(req.GetKind())
	q.SetStatus(req.GetStatus())
	if req.HasIssuedAt() {
		q.SetIssuedAt(req.GetIssuedAt().AsTime())
	} else {
		q.SetIssuedAt(st.now())
	}
	if req.HasDueAt() {
		q.SetDueAt(req.GetDueAt().AsTime())
	}
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}
	if req.HasAcknowledgedAt() {
		q.SetAcknowledgedAt(req.GetAcknowledgedAt().AsTime())
	}
	if req.HasReturnedAt() {
		q.SetReturnedAt(req.GetReturnedAt().AsTime())
	}
	if req.HasReservationId() {
		if v, err := entuuid.FromBytes(req.GetReservationId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "reservation_id: %s", err)
		} else {
			q.SetReservationId(v)
		}
	}
	if req.HasIssuedBy() {
		if v, err := entuuid.FromBytes(req.GetIssuedBy()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "issued_by: %s", err)
		} else {
			q.SetIssuedBy(v)
		}
	}
	q.SetOverdueNoticed(req.GetOverdueNoticed())

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Custody already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Custody: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  rove.CustodyService_Add_FullMethodName,
		Key: u.Id,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s CustodyServiceServer) Get(ctx context.Context, req *rove.CustodyGetRequest) (*rove.Custody, error) {
	p, err := CustodyPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Custody.Query().Where(p)
	CustodySelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Custody not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectCustodyKey(q *ent.CustodyQuery) {
	q.Select(custody.FieldId)
}

func CustodySelectedFields(m *rove.CustodySelect) []string {
	if m.GetAll() {
		return custody.Columns
	}

	vs := make([]string, 0, len(custody.Columns))
	{
		vs = append(vs, custody.FieldId)
	}
	if m.GetDesc() {
		vs = append(vs, custody.FieldDesc)
	}
	if m.GetKind() {
		vs = append(vs, custody.FieldKind)
	}
	if m.GetStatus() {
		vs = append(vs, custody.FieldStatus)
	}
	if m.GetIssuedAt() {
		vs = append(vs, custody.FieldIssuedAt)
	}
	if m.GetDueAt() {
		vs = append(vs, custody.FieldDueAt)
	}
	if m.GetDateUpdated() {
		vs = append(vs, custody.FieldDateUpdated)
	}
	if m.GetDateErased() {
		vs = append(vs, custody.FieldDateErased)
	}
	if m.GetDateCreated() {
		vs = append(vs, custody.FieldDateCreated)
	}
	if m.GetAcknowledgedAt() {
		vs = append(vs, custody.FieldAcknowledgedAt)
	}
	if m.GetReturnedAt() {
		vs = append(vs, custody.FieldReturnedAt)
	}
	if m.GetReservationId() {
		vs = append(vs, custody.FieldReservationId)
	}
	if m.GetIssuedBy() {
		vs = append(vs, custody.FieldIssuedBy)
	}
	if m.GetOverdueNoticed() {
		vs = append(vs, custody.FieldOverdueNoticed)
	}

	return vs
}

func CustodySelect(q *ent.CustodyQuery, m *rove.CustodySelect) {
	if !m.GetAll() {
		fields := CustodySelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
	if m.HasParty() {
		q.WithParty(func(q *ent.PartyQuery) {
			q.Where(party.DateErasedIsNil())
			PartySelect(q, m.GetParty())
		})
	}
}

func CustodySelectInit(q *ent.CustodyQuery, m *rove.CustodySelect) {
	if m != nil {
		CustodySelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
		q.WithParty(selectPartyKey)
	}
}

func (s CustodyServiceServer) Patch(ctx context.Context, req *rove.CustodyPatchRequest) (*rove.Custody, error) {
	doc, err := ormpatch.FromPatchRequest(custodyOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, rove.CustodyService_Patch_FullMethodName)
}

func CustodyGetKey(ctx context.Context, db *ent.Client, ref *rove.CustodyRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := entuuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := CustodyPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Custody.Query().Where(p).OnlyId(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Custody not found")
		}
		return z, err
	}

	return v, nil
}

var custodyOrmEntity = ormpatch.MustEntityOf(rove.File_rove_custody_proto, "Custody")

var custodyPatchColumns = entpatch.Columns{
	1: custody.FieldId, 2: custody.TenantColumn, 6: custody.FieldDesc, 8: custody.PartyColumn, 9: custody.FieldKind, 10: custody.FieldStatus, 11: custody.FieldIssuedAt, 12: custody.FieldDueAt, 13: custody.FieldDateUpdated, 14: custody.FieldDateErased, 15: custody.FieldDateCreated, 16: custody.FieldAcknowledgedAt, 17: custody.FieldReturnedAt, 18: custody.FieldReservationId, 19: custody.FieldIssuedBy, 20: custody.FieldOverdueNoticed}

func (s CustodyServiceServer) Apply(ctx context.Context, req *rove.CustodyApplyRequest) (*rove.Custody, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), rove.CustodyService_Apply_FullMethodName)
}

func (s CustodyServiceServer) apply(ctx context.Context, ref *rove.CustodyRef, doc *patchpb.Patch, by string) (*rove.Custody, error) {
	plan := &ormpatch.Plan{Entity: custodyOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(custodyOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, custodyPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := CustodyGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &rove.CustodyRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, custody.IdEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Custody.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Custody(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Custody.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Custody not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Custody.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Custody(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Custody already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Custody: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Custody.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Custody not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s CustodyServiceServer) Erase(ctx context.Context, req *rove.CustodyRef) (*rove.CustodyEraseResponse, error) {
	p, err := CustodyPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Custody.Query().Where(p).OnlyId(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &rove.CustodyEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = custody.And(p, custody.IdEQ(v))
	}

	u := st.Db.Custody.Update().Where(p)
	u.SetDateErased(st.now())
	u.SetDateUpdated(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  rove.CustodyService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &rove.CustodyEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// CustodyPick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Custody is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasCustodyWith`, where no narrowing of a Custody
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func CustodyPick(req *rove.CustodyRef) (predicate.Custody, error) {
	p, err := pickCustody(req)
	if err != nil {
		return nil, err
	}

	return custody.And(custody.DateErasedIsNil(), p), nil
}

func pickCustody(req *rove.CustodyRef) (predicate.Custody, error) {
	switch req.WhichKey() {
	case rove.CustodyRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return custody.IdEQ(v), nil
		}
	case rove.CustodyRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Custody")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}

type CustodyLineServiceServer struct {
	Store

	rove.UnimplementedCustodyLineServiceServer
}

// NewCustodyLineServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewCustodyLineServiceServer(db *ent.Client, opts ...Option) rove.CustodyLineServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return CustodyLineServiceServer{Store: s.Store}
}

// CustodyLineNarrow answers with `p` and everything else that narrows a
// read of a CustodyLine, which is whatever `scope` says.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func CustodyLineNarrow(ctx context.Context, scope Scope, p predicate.CustodyLine) (predicate.CustodyLine, error) {
	ps := make([]predicate.CustodyLine, 0, 2)
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.CustodyLineScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return custodyline.And(ps...), nil
	}
}

// narrow is [CustodyLineNarrow] with this server's own scope.
func (s CustodyLineServiceServer) narrow(ctx context.Context, p predicate.CustodyLine) (predicate.CustodyLine, error) {
	return CustodyLineNarrow(ctx, s.Scope, p)
}

func (s CustodyLineServiceServer) Add(ctx context.Context, req *rove.CustodyLineAddRequest) (*rove.CustodyLine, error) {
	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *rove.CustodyLine), 0, 4)
	q := st.Db.CustodyLine.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "rove.CustodyLine", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetId(v)
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantId(k)
		ds = append(ds, func(v *rove.CustodyLine) {
			v.SetTenant(rove.Tenant_builder{Id: k[:]}.Build())
		})
	}
	if k, err := CustodyGetKey(ctx, st.Db, req.GetCustody()); err != nil {
		return nil, err
	} else {
		q.SetCustodyId(k)
		ds = append(ds, func(v *rove.CustodyLine) {
			v.SetCustody(rove.Custody_builder{Id: k[:]}.Build())
		})
	}
	if req.HasAsset() {
		if k, err := AssetGetKey(ctx, st.Db, req.GetAsset()); err != nil {
			return nil, err
		} else {
			q.SetAssetId(k)
			ds = append(ds, func(v *rove.CustodyLine) {
				v.SetAsset(rove.Asset_builder{Id: k[:]}.Build())
			})
		}
	}
	if req.HasStock() {
		if k, err := StockGetKey(ctx, st.Db, req.GetStock()); err != nil {
			return nil, err
		} else {
			q.SetStockId(k)
			ds = append(ds, func(v *rove.CustodyLine) {
				v.SetStock(rove.Stock_builder{Id: k[:]}.Build())
			})
		}
	}
	q.SetQuantity(req.GetQuantity())
	q.SetReturnedQuantity(req.GetReturnedQuantity())
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}
	if req.HasOutAt() {
		q.SetOutAt(req.GetOutAt().AsTime())
	} else {
		q.SetOutAt(st.now())
	}
	if req.HasReturnedAt() {
		q.SetReturnedAt(req.GetReturnedAt().AsTime())
	}
	q.SetConditionOut(req.GetConditionOut())
	q.SetConditionIn(req.GetConditionIn())

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "CustodyLine already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "CustodyLine: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  rove.CustodyLineService_Add_FullMethodName,
		Key: u.Id,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s CustodyLineServiceServer) Get(ctx context.Context, req *rove.CustodyLineGetRequest) (*rove.CustodyLine, error) {
	p, err := CustodyLinePick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.CustodyLine.Query().Where(p)
	CustodyLineSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "CustodyLine not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectCustodyLineKey(q *ent.CustodyLineQuery) {
	q.Select(custodyline.FieldId)
}

func CustodyLineSelectedFields(m *rove.CustodyLineSelect) []string {
	if m.GetAll() {
		return custodyline.Columns
	}

	vs := make([]string, 0, len(custodyline.Columns))
	{
		vs = append(vs, custodyline.FieldId)
	}
	if m.GetQuantity() {
		vs = append(vs, custodyline.FieldQuantity)
	}
	if m.GetReturnedQuantity() {
		vs = append(vs, custodyline.FieldReturnedQuantity)
	}
	if m.GetDateUpdated() {
		vs = append(vs, custodyline.FieldDateUpdated)
	}
	if m.GetDateCreated() {
		vs = append(vs, custodyline.FieldDateCreated)
	}
	if m.GetOutAt() {
		vs = append(vs, custodyline.FieldOutAt)
	}
	if m.GetReturnedAt() {
		vs = append(vs, custodyline.FieldReturnedAt)
	}
	if m.GetConditionOut() {
		vs = append(vs, custodyline.FieldConditionOut)
	}
	if m.GetConditionIn() {
		vs = append(vs, custodyline.FieldConditionIn)
	}

	return vs
}

func CustodyLineSelect(q *ent.CustodyLineQuery, m *rove.CustodyLineSelect) {
	if !m.GetAll() {
		fields := CustodyLineSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
	if m.HasCustody() {
		q.WithCustody(func(q *ent.CustodyQuery) {
			q.Where(custody.DateErasedIsNil())
			CustodySelect(q, m.GetCustody())
		})
	}
	if m.HasAsset() {
		q.WithAsset(func(q *ent.AssetQuery) {
			q.Where(asset.DateErasedIsNil())
			AssetSelect(q, m.GetAsset())
		})
	}
	if m.HasStock() {
		q.WithStock(func(q *ent.StockQuery) {
			q.Where(stock.DateErasedIsNil())
			StockSelect(q, m.GetStock())
		})
	}
}

func CustodyLineSelectInit(q *ent.CustodyLineQuery, m *rove.CustodyLineSelect) {
	if m != nil {
		CustodyLineSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
		q.WithCustody(selectCustodyKey)
		q.WithAsset(selectAssetKey)
		q.WithStock(selectStockKey)
	}
}

func (s CustodyLineServiceServer) Patch(ctx context.Context, req *rove.CustodyLinePatchRequest) (*rove.CustodyLine, error) {
	doc, err := ormpatch.FromPatchRequest(custodyLineOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, rove.CustodyLineService_Patch_FullMethodName)
}

func CustodyLineGetKey(ctx context.Context, db *ent.Client, ref *rove.CustodyLineRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := entuuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := CustodyLinePick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.CustodyLine.Query().Where(p).OnlyId(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "CustodyLine not found")
		}
		return z, err
	}

	return v, nil
}

var custodyLineOrmEntity = ormpatch.MustEntityOf(rove.File_rove_custody_proto, "CustodyLine")

var custodyLinePatchColumns = entpatch.Columns{
	1: custodyline.FieldId, 2: custodyline.TenantColumn, 8: custodyline.CustodyColumn, 9: custodyline.AssetColumn, 10: custodyline.StockColumn, 11: custodyline.FieldQuantity, 12: custodyline.FieldReturnedQuantity, 13: custodyline.FieldDateUpdated, 15: custodyline.FieldDateCreated, 16: custodyline.FieldOutAt, 17: custodyline.FieldReturnedAt, 18: custodyline.FieldConditionOut, 19: custodyline.FieldConditionIn}

func (s CustodyLineServiceServer) Apply(ctx context.Context, req *rove.CustodyLineApplyRequest) (*rove.CustodyLine, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), rove.CustodyLineService_Apply_FullMethodName)
}

func (s CustodyLineServiceServer) apply(ctx context.Context, ref *rove.CustodyLineRef, doc *patchpb.Patch, by string) (*rove.CustodyLine, error) {
	plan := &ormpatch.Plan{Entity: custodyLineOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(custodyLineOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, custodyLinePatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := CustodyLineGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &rove.CustodyLineRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, custodyline.IdEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.CustodyLine.Query().Where(p)
		if pred != nil {
			q.Where(predicate.CustodyLine(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.CustodyLine.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "CustodyLine not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.CustodyLine.Update().Where(p)
		if pred != nil {
			q.Where(predicate.CustodyLine(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "CustodyLine already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "CustodyLine: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.CustodyLine.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "CustodyLine not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s CustodyLineServiceServer) Erase(ctx context.Context, req *rove.CustodyLineRef) (*rove.CustodyLineEraseResponse, error) {
	p, err := CustodyLinePick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.CustodyLine.Query().Where(p).OnlyId(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &rove.CustodyLineEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = custodyline.And(p, custodyline.IdEQ(v))
	}

	n, err := st.Db.CustodyLine.Delete().Where(p).Exec(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  rove.CustodyLineService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &rove.CustodyLineEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

func CustodyLinePick(req *rove.CustodyLineRef) (predicate.CustodyLine, error) {
	switch req.WhichKey() {
	case rove.CustodyLineRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return custodyline.IdEQ(v), nil
		}
	case rove.CustodyLineRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: CustodyLine")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
