// Code generated by ent, DO NOT EDIT.

package custodyline

import (
	"time"
	"uuid"

	"github.com/lesomnus/rove/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLTE(FieldId, id))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldQuantity, v))
}

// ReturnedQuantity applies equality check predicate on the "returned_quantity" field. It's identical to ReturnedQuantityEQ.
func ReturnedQuantity(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldReturnedQuantity, v))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldDateUpdated, v))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldDateCreated, v))
}

// OutAt applies equality check predicate on the "out_at" field. It's identical to OutAtEQ.
func OutAt(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldOutAt, v))
}

// ReturnedAt applies equality check predicate on the "returned_at" field. It's identical to ReturnedAtEQ.
func ReturnedAt(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldReturnedAt, v))
}

// ConditionOut applies equality check predicate on the "condition_out" field. It's identical to ConditionOutEQ.
func ConditionOut(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldConditionOut, v))
}

// ConditionIn applies equality check predicate on the "condition_in" field. It's identical to ConditionInEQ.
func ConditionIn(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldConditionIn, v))
}

// TenantId applies equality check predicate on the "tenant_id" field. It's identical to TenantIdEQ.
func TenantId(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldTenantId, v))
}

// CustodyId applies equality check predicate on the "custody_id" field. It's identical to CustodyIdEQ.
func CustodyId(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldCustodyId, v))
}

// AssetId applies equality check predicate on the "asset_id" field. It's identical to AssetIdEQ.
func AssetId(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldAssetId, v))
}

// StockId applies equality check predicate on the "stock_id" field. It's identical to StockIdEQ.
func StockId(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldStockId, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLTE(FieldQuantity, v))
}

// ReturnedQuantityEQ applies the EQ predicate on the "returned_quantity" field.
func ReturnedQuantityEQ(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldReturnedQuantity, v))
}

// ReturnedQuantityNEQ applies the NEQ predicate on the "returned_quantity" field.
func ReturnedQuantityNEQ(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldReturnedQuantity, v))
}

// ReturnedQuantityIn applies the In predicate on the "returned_quantity" field.
func ReturnedQuantityIn(vs ...int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldReturnedQuantity, vs...))
}

// ReturnedQuantityNotIn applies the NotIn predicate on the "returned_quantity" field.
func ReturnedQuantityNotIn(vs ...int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldReturnedQuantity, vs...))
}

// ReturnedQuantityGT applies the GT predicate on the "returned_quantity" field.
func ReturnedQuantityGT(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGT(FieldReturnedQuantity, v))
}

// ReturnedQuantityGTE applies the GTE predicate on the "returned_quantity" field.
func ReturnedQuantityGTE(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGTE(FieldReturnedQuantity, v))
}

// ReturnedQuantityLT applies the LT predicate on the "returned_quantity" field.
func ReturnedQuantityLT(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLT(FieldReturnedQuantity, v))
}

// ReturnedQuantityLTE applies the LTE predicate on the "returned_quantity" field.
func ReturnedQuantityLTE(v int64) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLTE(FieldReturnedQuantity, v))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLTE(FieldDateUpdated, v))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLTE(FieldDateCreated, v))
}

// DateCreatedIsNil applies the IsNil predicate on the "date_created" field.
func DateCreatedIsNil() predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIsNull(FieldDateCreated))
}

// DateCreatedNotNil applies the NotNil predicate on the "date_created" field.
func DateCreatedNotNil() predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotNull(FieldDateCreated))
}

// OutAtEQ applies the EQ predicate on the "out_at" field.
func OutAtEQ(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldOutAt, v))
}

// OutAtNEQ applies the NEQ predicate on the "out_at" field.
func OutAtNEQ(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldOutAt, v))
}

// OutAtIn applies the In predicate on the "out_at" field.
func OutAtIn(vs ...time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldOutAt, vs...))
}

// OutAtNotIn applies the NotIn predicate on the "out_at" field.
func OutAtNotIn(vs ...time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldOutAt, vs...))
}

// OutAtGT applies the GT predicate on the "out_at" field.
func OutAtGT(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGT(FieldOutAt, v))
}

// OutAtGTE applies the GTE predicate on the "out_at" field.
func OutAtGTE(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGTE(FieldOutAt, v))
}

// OutAtLT applies the LT predicate on the "out_at" field.
func OutAtLT(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLT(FieldOutAt, v))
}

// OutAtLTE applies the LTE predicate on the "out_at" field.
func OutAtLTE(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLTE(FieldOutAt, v))
}

// OutAtIsNil applies the IsNil predicate on the "out_at" field.
func OutAtIsNil() predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIsNull(FieldOutAt))
}

// OutAtNotNil applies the NotNil predicate on the "out_at" field.
func OutAtNotNil() predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotNull(FieldOutAt))
}

// ReturnedAtEQ applies the EQ predicate on the "returned_at" field.
func ReturnedAtEQ(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldReturnedAt, v))
}

// ReturnedAtNEQ applies the NEQ predicate on the "returned_at" field.
func ReturnedAtNEQ(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldReturnedAt, v))
}

// ReturnedAtIn applies the In predicate on the "returned_at" field.
func ReturnedAtIn(vs ...time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldReturnedAt, vs...))
}

// ReturnedAtNotIn applies the NotIn predicate on the "returned_at" field.
func ReturnedAtNotIn(vs ...time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldReturnedAt, vs...))
}

// ReturnedAtGT applies the GT predicate on the "returned_at" field.
func ReturnedAtGT(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGT(FieldReturnedAt, v))
}

// ReturnedAtGTE applies the GTE predicate on the "returned_at" field.
func ReturnedAtGTE(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGTE(FieldReturnedAt, v))
}

// ReturnedAtLT applies the LT predicate on the "returned_at" field.
func ReturnedAtLT(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLT(FieldReturnedAt, v))
}

// ReturnedAtLTE applies the LTE predicate on the "returned_at" field.
func ReturnedAtLTE(v time.Time) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLTE(FieldReturnedAt, v))
}

// ReturnedAtIsNil applies the IsNil predicate on the "returned_at" field.
func ReturnedAtIsNil() predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIsNull(FieldReturnedAt))
}

// ReturnedAtNotNil applies the NotNil predicate on the "returned_at" field.
func ReturnedAtNotNil() predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotNull(FieldReturnedAt))
}

// ConditionOutEQ applies the EQ predicate on the "condition_out" field.
func ConditionOutEQ(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldConditionOut, v))
}

// ConditionOutNEQ applies the NEQ predicate on the "condition_out" field.
func ConditionOutNEQ(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldConditionOut, v))
}

// ConditionOutIn applies the In predicate on the "condition_out" field.
func ConditionOutIn(vs ...string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldConditionOut, vs...))
}

// ConditionOutNotIn applies the NotIn predicate on the "condition_out" field.
func ConditionOutNotIn(vs ...string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldConditionOut, vs...))
}

// ConditionOutGT applies the GT predicate on the "condition_out" field.
func ConditionOutGT(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGT(FieldConditionOut, v))
}

// ConditionOutGTE applies the GTE predicate on the "condition_out" field.
func ConditionOutGTE(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGTE(FieldConditionOut, v))
}

// ConditionOutLT applies the LT predicate on the "condition_out" field.
func ConditionOutLT(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLT(FieldConditionOut, v))
}

// ConditionOutLTE applies the LTE predicate on the "condition_out" field.
func ConditionOutLTE(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLTE(FieldConditionOut, v))
}

// ConditionOutContains applies the Contains predicate on the "condition_out" field.
func ConditionOutContains(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldContains(FieldConditionOut, v))
}

// ConditionOutHasPrefix applies the HasPrefix predicate on the "condition_out" field.
func ConditionOutHasPrefix(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldHasPrefix(FieldConditionOut, v))
}

// ConditionOutHasSuffix applies the HasSuffix predicate on the "condition_out" field.
func ConditionOutHasSuffix(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldHasSuffix(FieldConditionOut, v))
}

// ConditionOutEqualFold applies the EqualFold predicate on the "condition_out" field.
func ConditionOutEqualFold(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEqualFold(FieldConditionOut, v))
}

// ConditionOutContainsFold applies the ContainsFold predicate on the "condition_out" field.
func ConditionOutContainsFold(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldContainsFold(FieldConditionOut, v))
}

// ConditionInEQ applies the EQ predicate on the "condition_in" field.
func ConditionInEQ(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldConditionIn, v))
}

// ConditionInNEQ applies the NEQ predicate on the "condition_in" field.
func ConditionInNEQ(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldConditionIn, v))
}

// ConditionInIn applies the In predicate on the "condition_in" field.
func ConditionInIn(vs ...string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldConditionIn, vs...))
}

// ConditionInNotIn applies the NotIn predicate on the "condition_in" field.
func ConditionInNotIn(vs ...string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldConditionIn, vs...))
}

// ConditionInGT applies the GT predicate on the "condition_in" field.
func ConditionInGT(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGT(FieldConditionIn, v))
}

// ConditionInGTE applies the GTE predicate on the "condition_in" field.
func ConditionInGTE(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldGTE(FieldConditionIn, v))
}

// ConditionInLT applies the LT predicate on the "condition_in" field.
func ConditionInLT(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLT(FieldConditionIn, v))
}

// ConditionInLTE applies the LTE predicate on the "condition_in" field.
func ConditionInLTE(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldLTE(FieldConditionIn, v))
}

// ConditionInContains applies the Contains predicate on the "condition_in" field.
func ConditionInContains(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldContains(FieldConditionIn, v))
}

// ConditionInHasPrefix applies the HasPrefix predicate on the "condition_in" field.
func ConditionInHasPrefix(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldHasPrefix(FieldConditionIn, v))
}

// ConditionInHasSuffix applies the HasSuffix predicate on the "condition_in" field.
func ConditionInHasSuffix(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldHasSuffix(FieldConditionIn, v))
}

// ConditionInEqualFold applies the EqualFold predicate on the "condition_in" field.
func ConditionInEqualFold(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEqualFold(FieldConditionIn, v))
}

// ConditionInContainsFold applies the ContainsFold predicate on the "condition_in" field.
func ConditionInContainsFold(v string) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldContainsFold(FieldConditionIn, v))
}

// TenantIdEQ applies the EQ predicate on the "tenant_id" field.
func TenantIdEQ(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldTenantId, v))
}

// TenantIdNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIdNEQ(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldTenantId, v))
}

// TenantIdIn applies the In predicate on the "tenant_id" field.
func TenantIdIn(vs ...uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldTenantId, vs...))
}

// TenantIdNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIdNotIn(vs ...uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldTenantId, vs...))
}

// CustodyIdEQ applies the EQ predicate on the "custody_id" field.
func CustodyIdEQ(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldCustodyId, v))
}

// CustodyIdNEQ applies the NEQ predicate on the "custody_id" field.
func CustodyIdNEQ(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldCustodyId, v))
}

// CustodyIdIn applies the In predicate on the "custody_id" field.
func CustodyIdIn(vs ...uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldCustodyId, vs...))
}

// CustodyIdNotIn applies the NotIn predicate on the "custody_id" field.
func CustodyIdNotIn(vs ...uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldCustodyId, vs...))
}

// AssetIdEQ applies the EQ predicate on the "asset_id" field.
func AssetIdEQ(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldAssetId, v))
}

// AssetIdNEQ applies the NEQ predicate on the "asset_id" field.
func AssetIdNEQ(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldAssetId, v))
}

// AssetIdIn applies the In predicate on the "asset_id" field.
func AssetIdIn(vs ...uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldAssetId, vs...))
}

// AssetIdNotIn applies the NotIn predicate on the "asset_id" field.
func AssetIdNotIn(vs ...uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldAssetId, vs...))
}

// AssetIdIsNil applies the IsNil predicate on the "asset_id" field.
func AssetIdIsNil() predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIsNull(FieldAssetId))
}

// AssetIdNotNil applies the NotNil predicate on the "asset_id" field.
func AssetIdNotNil() predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotNull(FieldAssetId))
}

// StockIdEQ applies the EQ predicate on the "stock_id" field.
func StockIdEQ(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldEQ(FieldStockId, v))
}

// StockIdNEQ applies the NEQ predicate on the "stock_id" field.
func StockIdNEQ(v uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNEQ(FieldStockId, v))
}

// StockIdIn applies the In predicate on the "stock_id" field.
func StockIdIn(vs ...uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIn(FieldStockId, vs...))
}

// StockIdNotIn applies the NotIn predicate on the "stock_id" field.
func StockIdNotIn(vs ...uuid.UUID) predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotIn(FieldStockId, vs...))
}

// StockIdIsNil applies the IsNil predicate on the "stock_id" field.
func StockIdIsNil() predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldIsNull(FieldStockId))
}

// StockIdNotNil applies the NotNil predicate on the "stock_id" field.
func StockIdNotNil() predicate.CustodyLine {
	return predicate.CustodyLine(sql.FieldNotNull(FieldStockId))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.CustodyLine {
	return predicate.CustodyLine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.CustodyLine {
	return predicate.CustodyLine(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCustody applies the HasEdge predicate on the "custody" edge.
func HasCustody() predicate.CustodyLine {
	return predicate.CustodyLine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, CustodyTable, CustodyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustodyWith applies the HasEdge predicate on the "custody" edge with a given conditions (other predicates).
func HasCustodyWith(preds ...predicate.Custody) predicate.CustodyLine {
	return predicate.CustodyLine(func(s *sql.Selector) {
		step := newCustodyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAsset applies the HasEdge predicate on the "asset" edge.
func HasAsset() predicate.CustodyLine {
	return predicate.CustodyLine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, AssetTable, AssetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetWith applies the HasEdge predicate on the "asset" edge with a given conditions (other predicates).
func HasAssetWith(preds ...predicate.Asset) predicate.CustodyLine {
	return predicate.CustodyLine(func(s *sql.Selector) {
		step := newAssetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStock applies the HasEdge predicate on the "stock" edge.
func HasStock() predicate.CustodyLine {
	return predicate.CustodyLine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, StockTable, StockColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStockWith applies the HasEdge predicate on the "stock" edge with a given conditions (other predicates).
func HasStockWith(preds ...predicate.Stock) predicate.CustodyLine {
	return predicate.CustodyLine(func(s *sql.Selector) {
		step := newStockStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustodyLine) predicate.CustodyLine {
	return predicate.CustodyLine(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustodyLine) predicate.CustodyLine {
	return predicate.CustodyLine(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustodyLine) predicate.CustodyLine {
	return predicate.CustodyLine(sql.NotPredicates(p))
}
