// Code generated by ent, DO NOT EDIT.

package purchaseline

import (
	"time"
	"uuid"

	"github.com/lesomnus/rove/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLTE(FieldId, id))
}

// Desc applies equality check predicate on the "desc" field. It's identical to DescEQ.
func Desc(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldDesc, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldQuantity, v))
}

// UnitCost applies equality check predicate on the "unit_cost" field. It's identical to UnitCostEQ.
func UnitCost(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldUnitCost, v))
}

// ReceivedQuantity applies equality check predicate on the "received_quantity" field. It's identical to ReceivedQuantityEQ.
func ReceivedQuantity(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldReceivedQuantity, v))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldDateUpdated, v))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldDateCreated, v))
}

// ReceiveAs applies equality check predicate on the "receive_as" field. It's identical to ReceiveAsEQ.
func ReceiveAs(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldReceiveAs, v))
}

// TenantId applies equality check predicate on the "tenant_id" field. It's identical to TenantIdEQ.
func TenantId(v uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldTenantId, v))
}

// PurchaseId applies equality check predicate on the "purchase_id" field. It's identical to PurchaseIdEQ.
func PurchaseId(v uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldPurchaseId, v))
}

// ModelId applies equality check predicate on the "model_id" field. It's identical to ModelIdEQ.
func ModelId(v uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldModelId, v))
}

// DescEQ applies the EQ predicate on the "desc" field.
func DescEQ(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldDesc, v))
}

// DescNEQ applies the NEQ predicate on the "desc" field.
func DescNEQ(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNEQ(FieldDesc, v))
}

// DescIn applies the In predicate on the "desc" field.
func DescIn(vs ...string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIn(FieldDesc, vs...))
}

// DescNotIn applies the NotIn predicate on the "desc" field.
func DescNotIn(vs ...string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotIn(FieldDesc, vs...))
}

// DescGT applies the GT predicate on the "desc" field.
func DescGT(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGT(FieldDesc, v))
}

// DescGTE applies the GTE predicate on the "desc" field.
func DescGTE(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGTE(FieldDesc, v))
}

// DescLT applies the LT predicate on the "desc" field.
func DescLT(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLT(FieldDesc, v))
}

// DescLTE applies the LTE predicate on the "desc" field.
func DescLTE(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLTE(FieldDesc, v))
}

// DescContains applies the Contains predicate on the "desc" field.
func DescContains(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldContains(FieldDesc, v))
}

// DescHasPrefix applies the HasPrefix predicate on the "desc" field.
func DescHasPrefix(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldHasPrefix(FieldDesc, v))
}

// DescHasSuffix applies the HasSuffix predicate on the "desc" field.
func DescHasSuffix(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldHasSuffix(FieldDesc, v))
}

// DescEqualFold applies the EqualFold predicate on the "desc" field.
func DescEqualFold(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEqualFold(FieldDesc, v))
}

// DescContainsFold applies the ContainsFold predicate on the "desc" field.
func DescContainsFold(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldContainsFold(FieldDesc, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLTE(FieldQuantity, v))
}

// UnitCostEQ applies the EQ predicate on the "unit_cost" field.
func UnitCostEQ(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldUnitCost, v))
}

// UnitCostNEQ applies the NEQ predicate on the "unit_cost" field.
func UnitCostNEQ(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNEQ(FieldUnitCost, v))
}

// UnitCostIn applies the In predicate on the "unit_cost" field.
func UnitCostIn(vs ...int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIn(FieldUnitCost, vs...))
}

// UnitCostNotIn applies the NotIn predicate on the "unit_cost" field.
func UnitCostNotIn(vs ...int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotIn(FieldUnitCost, vs...))
}

// UnitCostGT applies the GT predicate on the "unit_cost" field.
func UnitCostGT(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGT(FieldUnitCost, v))
}

// UnitCostGTE applies the GTE predicate on the "unit_cost" field.
func UnitCostGTE(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGTE(FieldUnitCost, v))
}

// UnitCostLT applies the LT predicate on the "unit_cost" field.
func UnitCostLT(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLT(FieldUnitCost, v))
}

// UnitCostLTE applies the LTE predicate on the "unit_cost" field.
func UnitCostLTE(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLTE(FieldUnitCost, v))
}

// ReceivedQuantityEQ applies the EQ predicate on the "received_quantity" field.
func ReceivedQuantityEQ(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldReceivedQuantity, v))
}

// ReceivedQuantityNEQ applies the NEQ predicate on the "received_quantity" field.
func ReceivedQuantityNEQ(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNEQ(FieldReceivedQuantity, v))
}

// ReceivedQuantityIn applies the In predicate on the "received_quantity" field.
func ReceivedQuantityIn(vs ...int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIn(FieldReceivedQuantity, vs...))
}

// ReceivedQuantityNotIn applies the NotIn predicate on the "received_quantity" field.
func ReceivedQuantityNotIn(vs ...int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotIn(FieldReceivedQuantity, vs...))
}

// ReceivedQuantityGT applies the GT predicate on the "received_quantity" field.
func ReceivedQuantityGT(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGT(FieldReceivedQuantity, v))
}

// ReceivedQuantityGTE applies the GTE predicate on the "received_quantity" field.
func ReceivedQuantityGTE(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGTE(FieldReceivedQuantity, v))
}

// ReceivedQuantityLT applies the LT predicate on the "received_quantity" field.
func ReceivedQuantityLT(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLT(FieldReceivedQuantity, v))
}

// ReceivedQuantityLTE applies the LTE predicate on the "received_quantity" field.
func ReceivedQuantityLTE(v int64) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLTE(FieldReceivedQuantity, v))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLTE(FieldDateUpdated, v))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLTE(FieldDateCreated, v))
}

// DateCreatedIsNil applies the IsNil predicate on the "date_created" field.
func DateCreatedIsNil() predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIsNull(FieldDateCreated))
}

// DateCreatedNotNil applies the NotNil predicate on the "date_created" field.
func DateCreatedNotNil() predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotNull(FieldDateCreated))
}

// ReceiveAsEQ applies the EQ predicate on the "receive_as" field.
func ReceiveAsEQ(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldReceiveAs, v))
}

// ReceiveAsNEQ applies the NEQ predicate on the "receive_as" field.
func ReceiveAsNEQ(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNEQ(FieldReceiveAs, v))
}

// ReceiveAsIn applies the In predicate on the "receive_as" field.
func ReceiveAsIn(vs ...string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIn(FieldReceiveAs, vs...))
}

// ReceiveAsNotIn applies the NotIn predicate on the "receive_as" field.
func ReceiveAsNotIn(vs ...string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotIn(FieldReceiveAs, vs...))
}

// ReceiveAsGT applies the GT predicate on the "receive_as" field.
func ReceiveAsGT(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGT(FieldReceiveAs, v))
}

// ReceiveAsGTE applies the GTE predicate on the "receive_as" field.
func ReceiveAsGTE(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldGTE(FieldReceiveAs, v))
}

// ReceiveAsLT applies the LT predicate on the "receive_as" field.
func ReceiveAsLT(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLT(FieldReceiveAs, v))
}

// ReceiveAsLTE applies the LTE predicate on the "receive_as" field.
func ReceiveAsLTE(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldLTE(FieldReceiveAs, v))
}

// ReceiveAsContains applies the Contains predicate on the "receive_as" field.
func ReceiveAsContains(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldContains(FieldReceiveAs, v))
}

// ReceiveAsHasPrefix applies the HasPrefix predicate on the "receive_as" field.
func ReceiveAsHasPrefix(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldHasPrefix(FieldReceiveAs, v))
}

// ReceiveAsHasSuffix applies the HasSuffix predicate on the "receive_as" field.
func ReceiveAsHasSuffix(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldHasSuffix(FieldReceiveAs, v))
}

// ReceiveAsEqualFold applies the EqualFold predicate on the "receive_as" field.
func ReceiveAsEqualFold(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEqualFold(FieldReceiveAs, v))
}

// ReceiveAsContainsFold applies the ContainsFold predicate on the "receive_as" field.
func ReceiveAsContainsFold(v string) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldContainsFold(FieldReceiveAs, v))
}

// TenantIdEQ applies the EQ predicate on the "tenant_id" field.
func TenantIdEQ(v uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldTenantId, v))
}

// TenantIdNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIdNEQ(v uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNEQ(FieldTenantId, v))
}

// TenantIdIn applies the In predicate on the "tenant_id" field.
func TenantIdIn(vs ...uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIn(FieldTenantId, vs...))
}

// TenantIdNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIdNotIn(vs ...uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotIn(FieldTenantId, vs...))
}

// PurchaseIdEQ applies the EQ predicate on the "purchase_id" field.
func PurchaseIdEQ(v uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldPurchaseId, v))
}

// PurchaseIdNEQ applies the NEQ predicate on the "purchase_id" field.
func PurchaseIdNEQ(v uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNEQ(FieldPurchaseId, v))
}

// PurchaseIdIn applies the In predicate on the "purchase_id" field.
func PurchaseIdIn(vs ...uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIn(FieldPurchaseId, vs...))
}

// PurchaseIdNotIn applies the NotIn predicate on the "purchase_id" field.
func PurchaseIdNotIn(vs ...uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotIn(FieldPurchaseId, vs...))
}

// ModelIdEQ applies the EQ predicate on the "model_id" field.
func ModelIdEQ(v uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldEQ(FieldModelId, v))
}

// ModelIdNEQ applies the NEQ predicate on the "model_id" field.
func ModelIdNEQ(v uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNEQ(FieldModelId, v))
}

// ModelIdIn applies the In predicate on the "model_id" field.
func ModelIdIn(vs ...uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIn(FieldModelId, vs...))
}

// ModelIdNotIn applies the NotIn predicate on the "model_id" field.
func ModelIdNotIn(vs ...uuid.UUID) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotIn(FieldModelId, vs...))
}

// ModelIdIsNil applies the IsNil predicate on the "model_id" field.
func ModelIdIsNil() predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldIsNull(FieldModelId))
}

// ModelIdNotNil applies the NotNil predicate on the "model_id" field.
func ModelIdNotNil() predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.FieldNotNull(FieldModelId))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.PurchaseLine {
	return predicate.PurchaseLine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.PurchaseLine {
	return predicate.PurchaseLine(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPurchase applies the HasEdge predicate on the "purchase" edge.
func HasPurchase() predicate.PurchaseLine {
	return predicate.PurchaseLine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, PurchaseTable, PurchaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPurchaseWith applies the HasEdge predicate on the "purchase" edge with a given conditions (other predicates).
func HasPurchaseWith(preds ...predicate.Purchase) predicate.PurchaseLine {
	return predicate.PurchaseLine(func(s *sql.Selector) {
		step := newPurchaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasModel applies the HasEdge predicate on the "model" edge.
func HasModel() predicate.PurchaseLine {
	return predicate.PurchaseLine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, ModelTable, ModelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModelWith applies the HasEdge predicate on the "model" edge with a given conditions (other predicates).
func HasModelWith(preds ...predicate.ItemModel) predicate.PurchaseLine {
	return predicate.PurchaseLine(func(s *sql.Selector) {
		step := newModelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PurchaseLine) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PurchaseLine) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PurchaseLine) predicate.PurchaseLine {
	return predicate.PurchaseLine(sql.NotPredicates(p))
}
